template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/channels/app/platform:
    config:
      dir: channels/app/platform/mocks
      filename: "{{.InterfaceName}}.go"
      structname: '{{.InterfaceName}}'
      pkgname: mocks
    interfaces:
      SuiteIFace: {}
