template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/platform/services/searchengine:
    config:
      all: true
      dir: platform/services/searchengine/mocks
      filename: "{{.InterfaceName}}.go"
      structname: '{{.InterfaceName}}'
      pkgname: mocks
