template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/channels/store:
    config:
      dir: channels/store/storetest/mocks
      filename: "{{.InterfaceName}}.go"
      include-interface-regex: .*Store
      structname: "{{.InterfaceName}}"
      pkgname: mocks
