template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/einterfaces:
    config:
      all: true
      dir: einterfaces/mocks
      exclude-subpkg-regex:
        - mocks
      filename: "{{.InterfaceName}}.go"
      structname: '{{.InterfaceName}}'
      pkgname: mocks
      recursive: true
