with-expecter: false
packages:
  github.com/iamleson98/sitename/server/v8/einterfaces:
    config:
      all: true
      dir: "einterfaces/mocks"
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
      outpkg: mocks
      recursive: true
      exclude:
        - mocks
      note: "Regenerate this file using `make einterfaces-mocks`."
