template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/platform/services/sharedchannel:
    config:
      dir: platform/services/sharedchannel
      filename: "mock_{{.InterfaceName}}_test.go"
      structname: "Mock{{.InterfaceName}}"
      pkgname: sharedchannel
    interfaces:
      AppIface: {}
      ServerIface: {}
