output "manager_public_ip" {
  description = "Public IP of the Swarm manager (Traefik entrypoint; SSH host)."
  value       = kamatera_server.manager.public_ips[0]
}

output "manager_ssh" {
  description = "Ready-to-run SSH command for the manager."
  value       = "ssh -i ${local.ssh_private_key} ${local.ssh_user}@${kamatera_server.manager.public_ips[0]}"
}

output "backend_public_ip" { value = kamatera_server.backend.public_ips[0] }
output "db_public_ip"      { value = kamatera_server.db.public_ips[0] }
output "video_public_ip"   { value = kamatera_server.video.public_ips[0] }

output "all_nodes" {
  description = "All node public IPs with their role labels."
  value = {
    manager = kamatera_server.manager.public_ips[0]
    backend = kamatera_server.backend.public_ips[0]
    db      = kamatera_server.db.public_ips[0]
    video   = kamatera_server.video.public_ips[0]
  }
}

output "swarm_check" {
  description = "Run this to verify the cluster formed."
  value       = "ssh -i ${local.ssh_private_key} ${local.ssh_user}@${kamatera_server.manager.public_ips[0]} 'docker node ls'"
}

# Secrets generated by Terraform. Marked sensitive; shown only with -json or
# explicit output. The deploy/secrets-bootstrap.sh can consume these.
output "generated_db_password" {
  description = "Generated PostgreSQL password. Use in secrets-bootstrap.sh."
  value       = random_password.db_password.result
  sensitive   = true
}

output "generated_rustfs_secret_key" {
  value     = random_password.rustfs_secret_key.result
  sensitive = true
}

output "generated_grafana_admin_password" {
  value     = random_password.grafana_admin_password.result
  sensitive = true
}

output "generated_registry_password" {
  description = "Password for the private registry user 'lms'."
  value       = random_password.registry_password.result
  sensitive   = true
}

output "registry_url" {
  description = "In-cluster private registry. Push here, pull as this host from any node."
  value       = "127.0.0.1:5000"
}
