template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/iamleson98/sitename/server/v8/channels/app/email:
    config:
      dir: channels/app/email/mocks
      filename: "{{.InterfaceName}}.go"
      structname: '{{.InterfaceName}}'
      pkgname: mocks
    interfaces:
      ServiceInterface: {}
