// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package lms_models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
	"github.com/shopspring/decimal"
)

// AdditionalFee is an object representing the database table.
type AdditionalFee struct {
	ID        string          `boil:"id" json:"id" toml:"id" yaml:"id"`
	TuitionID string          `boil:"tuition_id" json:"tuition_id" toml:"tuition_id" yaml:"tuition_id"`
	Label     string          `boil:"label" json:"label" toml:"label" yaml:"label"`
	Amount    decimal.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Createat  int64           `boil:"createat" json:"createat" toml:"createat" yaml:"createat"`
	Updateat  int64           `boil:"updateat" json:"updateat" toml:"updateat" yaml:"updateat"`

	R *additionalFeeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L additionalFeeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AdditionalFeeColumns = struct {
	ID        string
	TuitionID string
	Label     string
	Amount    string
	Createat  string
	Updateat  string
}{
	ID:        "id",
	TuitionID: "tuition_id",
	Label:     "label",
	Amount:    "amount",
	Createat:  "createat",
	Updateat:  "updateat",
}

var AdditionalFeeTableColumns = struct {
	ID        string
	TuitionID string
	Label     string
	Amount    string
	Createat  string
	Updateat  string
}{
	ID:        "additional_fees.id",
	TuitionID: "additional_fees.tuition_id",
	Label:     "additional_fees.label",
	Amount:    "additional_fees.amount",
	Createat:  "additional_fees.createat",
	Updateat:  "additional_fees.updateat",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperdecimal_Decimal struct{ field string }

func (w whereHelperdecimal_Decimal) EQ(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperdecimal_Decimal) NEQ(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperdecimal_Decimal) LT(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperdecimal_Decimal) LTE(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperdecimal_Decimal) GT(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperdecimal_Decimal) GTE(x decimal.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var AdditionalFeeWhere = struct {
	ID        whereHelperstring
	TuitionID whereHelperstring
	Label     whereHelperstring
	Amount    whereHelperdecimal_Decimal
	Createat  whereHelperint64
	Updateat  whereHelperint64
}{
	ID:        whereHelperstring{field: "\"additional_fees\".\"id\""},
	TuitionID: whereHelperstring{field: "\"additional_fees\".\"tuition_id\""},
	Label:     whereHelperstring{field: "\"additional_fees\".\"label\""},
	Amount:    whereHelperdecimal_Decimal{field: "\"additional_fees\".\"amount\""},
	Createat:  whereHelperint64{field: "\"additional_fees\".\"createat\""},
	Updateat:  whereHelperint64{field: "\"additional_fees\".\"updateat\""},
}

// AdditionalFeeRels is where relationship names are stored.
var AdditionalFeeRels = struct {
	Tuition string
}{
	Tuition: "Tuition",
}

// additionalFeeR is where relationships are stored.
type additionalFeeR struct {
	Tuition *Tuition `boil:"Tuition" json:"Tuition" toml:"Tuition" yaml:"Tuition"`
}

// NewStruct creates a new relationship struct
func (*additionalFeeR) NewStruct() *additionalFeeR {
	return &additionalFeeR{}
}

func (o *AdditionalFee) GetTuition() *Tuition {
	if o == nil {
		return nil
	}

	return o.R.GetTuition()
}

func (r *additionalFeeR) GetTuition() *Tuition {
	if r == nil {
		return nil
	}

	return r.Tuition
}

// additionalFeeL is where Load methods for each relationship are stored.
type additionalFeeL struct{}

var (
	additionalFeeAllColumns            = []string{"id", "tuition_id", "label", "amount", "createat", "updateat"}
	additionalFeeColumnsWithoutDefault = []string{"id", "tuition_id", "label", "amount", "createat", "updateat"}
	additionalFeeColumnsWithDefault    = []string{}
	additionalFeePrimaryKeyColumns     = []string{"id"}
	additionalFeeGeneratedColumns      = []string{}
)

type (
	// AdditionalFeeSlice is an alias for a slice of pointers to AdditionalFee.
	// This should almost always be used instead of []AdditionalFee.
	AdditionalFeeSlice []*AdditionalFee

	additionalFeeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	additionalFeeType                 = reflect.TypeOf(&AdditionalFee{})
	additionalFeeMapping              = queries.MakeStructMapping(additionalFeeType)
	additionalFeePrimaryKeyMapping, _ = queries.BindMapping(additionalFeeType, additionalFeeMapping, additionalFeePrimaryKeyColumns)
	additionalFeeInsertCacheMut       sync.RWMutex
	additionalFeeInsertCache          = make(map[string]insertCache)
	additionalFeeUpdateCacheMut       sync.RWMutex
	additionalFeeUpdateCache          = make(map[string]updateCache)
	additionalFeeUpsertCacheMut       sync.RWMutex
	additionalFeeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single additionalFee record from the query.
func (q additionalFeeQuery) One(exec boil.Executor) (*AdditionalFee, error) {
	o := &AdditionalFee{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: failed to execute a one query for additional_fees")
	}

	return o, nil
}

// All returns all AdditionalFee records from the query.
func (q additionalFeeQuery) All(exec boil.Executor) (AdditionalFeeSlice, error) {
	var o []*AdditionalFee

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "lms_models: failed to assign all query results to AdditionalFee slice")
	}

	return o, nil
}

// Count returns the count of all AdditionalFee records in the query.
func (q additionalFeeQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to count additional_fees rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q additionalFeeQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: failed to check if additional_fees exists")
	}

	return count > 0, nil
}

// Tuition pointed to by the foreign key.
func (o *AdditionalFee) Tuition(mods ...qm.QueryMod) tuitionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TuitionID),
	}

	queryMods = append(queryMods, mods...)

	return Tuitions(queryMods...)
}

// LoadTuition allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (additionalFeeL) LoadTuition(e boil.Executor, singular bool, maybeAdditionalFee any, mods queries.Applicator) error {
	var slice []*AdditionalFee
	var object *AdditionalFee

	if singular {
		var ok bool
		object, ok = maybeAdditionalFee.(*AdditionalFee)
		if !ok {
			object = new(AdditionalFee)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeAdditionalFee)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeAdditionalFee))
			}
		}
	} else {
		s, ok := maybeAdditionalFee.(*[]*AdditionalFee)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeAdditionalFee)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeAdditionalFee))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &additionalFeeR{}
		}
		args[object.TuitionID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &additionalFeeR{}
			}

			args[obj.TuitionID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tuitions`),
		qm.WhereIn(`tuitions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Tuition")
	}

	var resultSlice []*Tuition
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Tuition")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tuitions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tuitions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Tuition = foreign
		if foreign.R == nil {
			foreign.R = &tuitionR{}
		}
		foreign.R.AdditionalFees = append(foreign.R.AdditionalFees, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TuitionID == foreign.ID {
				local.R.Tuition = foreign
				if foreign.R == nil {
					foreign.R = &tuitionR{}
				}
				foreign.R.AdditionalFees = append(foreign.R.AdditionalFees, local)
				break
			}
		}
	}

	return nil
}

// SetTuition of the additionalFee to the related item.
// Sets o.R.Tuition to related.
// Adds o to related.R.AdditionalFees.
func (o *AdditionalFee) SetTuition(exec boil.Executor, insert bool, related *Tuition) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"additional_fees\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"tuition_id"}),
		strmangle.WhereClause("\"", "\"", 2, additionalFeePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TuitionID = related.ID
	if o.R == nil {
		o.R = &additionalFeeR{
			Tuition: related,
		}
	} else {
		o.R.Tuition = related
	}

	if related.R == nil {
		related.R = &tuitionR{
			AdditionalFees: AdditionalFeeSlice{o},
		}
	} else {
		related.R.AdditionalFees = append(related.R.AdditionalFees, o)
	}

	return nil
}

// AdditionalFees retrieves all the records using an executor.
func AdditionalFees(mods ...qm.QueryMod) additionalFeeQuery {
	mods = append(mods, qm.From("\"additional_fees\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"additional_fees\".*"})
	}

	return additionalFeeQuery{q}
}

// FindAdditionalFee retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAdditionalFee(exec boil.Executor, iD string, selectCols ...string) (*AdditionalFee, error) {
	additionalFeeObj := &AdditionalFee{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"additional_fees\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, additionalFeeObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: unable to select from additional_fees")
	}

	return additionalFeeObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AdditionalFee) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("lms_models: no additional_fees provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(additionalFeeColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	additionalFeeInsertCacheMut.RLock()
	cache, cached := additionalFeeInsertCache[key]
	additionalFeeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			additionalFeeAllColumns,
			additionalFeeColumnsWithDefault,
			additionalFeeColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(additionalFeeType, additionalFeeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(additionalFeeType, additionalFeeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"additional_fees\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"additional_fees\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "lms_models: unable to insert into additional_fees")
	}

	if !cached {
		additionalFeeInsertCacheMut.Lock()
		additionalFeeInsertCache[key] = cache
		additionalFeeInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AdditionalFee.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AdditionalFee) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	additionalFeeUpdateCacheMut.RLock()
	cache, cached := additionalFeeUpdateCache[key]
	additionalFeeUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			additionalFeeAllColumns,
			additionalFeePrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("lms_models: unable to update additional_fees, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"additional_fees\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, additionalFeePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(additionalFeeType, additionalFeeMapping, append(wl, additionalFeePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update additional_fees row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by update for additional_fees")
	}

	if !cached {
		additionalFeeUpdateCacheMut.Lock()
		additionalFeeUpdateCache[key] = cache
		additionalFeeUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q additionalFeeQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all for additional_fees")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected for additional_fees")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AdditionalFeeSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("lms_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), additionalFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"additional_fees\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, additionalFeePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all in additionalFee slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected all in update all additionalFee")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AdditionalFee) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("lms_models: no additional_fees provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(additionalFeeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	additionalFeeUpsertCacheMut.RLock()
	cache, cached := additionalFeeUpsertCache[key]
	additionalFeeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			additionalFeeAllColumns,
			additionalFeeColumnsWithDefault,
			additionalFeeColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			additionalFeeAllColumns,
			additionalFeePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("lms_models: unable to upsert additional_fees, could not build update column list")
		}

		ret := strmangle.SetComplement(additionalFeeAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(additionalFeePrimaryKeyColumns) == 0 {
				return errors.New("lms_models: unable to upsert additional_fees, could not build conflict column list")
			}

			conflict = make([]string, len(additionalFeePrimaryKeyColumns))
			copy(conflict, additionalFeePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"additional_fees\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(additionalFeeType, additionalFeeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(additionalFeeType, additionalFeeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to upsert additional_fees")
	}

	if !cached {
		additionalFeeUpsertCacheMut.Lock()
		additionalFeeUpsertCache[key] = cache
		additionalFeeUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AdditionalFee record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AdditionalFee) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("lms_models: no AdditionalFee provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), additionalFeePrimaryKeyMapping)
	sql := "DELETE FROM \"additional_fees\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete from additional_fees")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by delete for additional_fees")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q additionalFeeQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("lms_models: no additionalFeeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from additional_fees")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for additional_fees")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AdditionalFeeSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), additionalFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"additional_fees\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, additionalFeePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from additionalFee slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for additional_fees")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AdditionalFee) Reload(exec boil.Executor) error {
	ret, err := FindAdditionalFee(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AdditionalFeeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AdditionalFeeSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), additionalFeePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"additional_fees\".* FROM \"additional_fees\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, additionalFeePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to reload all in AdditionalFeeSlice")
	}

	*o = slice

	return nil
}

// AdditionalFeeExists checks if the AdditionalFee row exists.
func AdditionalFeeExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"additional_fees\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: unable to check if additional_fees exists")
	}

	return exists, nil
}

// Exists checks if the AdditionalFee row exists.
func (o *AdditionalFee) Exists(exec boil.Executor) (bool, error) {
	return AdditionalFeeExists(exec, o.ID)
}
