// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package lms_models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ClassMedium is an object representing the database table.
type ClassMedium struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	ClassID      string      `boil:"class_id" json:"class_id" toml:"class_id" yaml:"class_id"`
	SessionID    null.String `boil:"session_id" json:"session_id,omitempty" toml:"session_id" yaml:"session_id,omitempty"`
	Title        null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	FileURL      string      `boil:"file_url" json:"file_url" toml:"file_url" yaml:"file_url"`
	FileType     string      `boil:"file_type" json:"file_type" toml:"file_type" yaml:"file_type"`
	UploadedByID string      `boil:"uploaded_by_id" json:"uploaded_by_id" toml:"uploaded_by_id" yaml:"uploaded_by_id"`
	FileID       string      `boil:"file_id" json:"file_id" toml:"file_id" yaml:"file_id"`
	Createat     int64       `boil:"createat" json:"createat" toml:"createat" yaml:"createat"`
	Updateat     int64       `boil:"updateat" json:"updateat" toml:"updateat" yaml:"updateat"`

	R *classMediumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L classMediumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ClassMediumColumns = struct {
	ID           string
	ClassID      string
	SessionID    string
	Title        string
	FileURL      string
	FileType     string
	UploadedByID string
	FileID       string
	Createat     string
	Updateat     string
}{
	ID:           "id",
	ClassID:      "class_id",
	SessionID:    "session_id",
	Title:        "title",
	FileURL:      "file_url",
	FileType:     "file_type",
	UploadedByID: "uploaded_by_id",
	FileID:       "file_id",
	Createat:     "createat",
	Updateat:     "updateat",
}

var ClassMediumTableColumns = struct {
	ID           string
	ClassID      string
	SessionID    string
	Title        string
	FileURL      string
	FileType     string
	UploadedByID string
	FileID       string
	Createat     string
	Updateat     string
}{
	ID:           "class_media.id",
	ClassID:      "class_media.class_id",
	SessionID:    "class_media.session_id",
	Title:        "class_media.title",
	FileURL:      "class_media.file_url",
	FileType:     "class_media.file_type",
	UploadedByID: "class_media.uploaded_by_id",
	FileID:       "class_media.file_id",
	Createat:     "class_media.createat",
	Updateat:     "class_media.updateat",
}

// Generated where

var ClassMediumWhere = struct {
	ID           whereHelperstring
	ClassID      whereHelperstring
	SessionID    whereHelpernull_String
	Title        whereHelpernull_String
	FileURL      whereHelperstring
	FileType     whereHelperstring
	UploadedByID whereHelperstring
	FileID       whereHelperstring
	Createat     whereHelperint64
	Updateat     whereHelperint64
}{
	ID:           whereHelperstring{field: "\"class_media\".\"id\""},
	ClassID:      whereHelperstring{field: "\"class_media\".\"class_id\""},
	SessionID:    whereHelpernull_String{field: "\"class_media\".\"session_id\""},
	Title:        whereHelpernull_String{field: "\"class_media\".\"title\""},
	FileURL:      whereHelperstring{field: "\"class_media\".\"file_url\""},
	FileType:     whereHelperstring{field: "\"class_media\".\"file_type\""},
	UploadedByID: whereHelperstring{field: "\"class_media\".\"uploaded_by_id\""},
	FileID:       whereHelperstring{field: "\"class_media\".\"file_id\""},
	Createat:     whereHelperint64{field: "\"class_media\".\"createat\""},
	Updateat:     whereHelperint64{field: "\"class_media\".\"updateat\""},
}

// ClassMediumRels is where relationship names are stored.
var ClassMediumRels = struct {
	Class      string
	File       string
	Session    string
	UploadedBy string
}{
	Class:      "Class",
	File:       "File",
	Session:    "Session",
	UploadedBy: "UploadedBy",
}

// classMediumR is where relationships are stored.
type classMediumR struct {
	Class      *Class      `boil:"Class" json:"Class" toml:"Class" yaml:"Class"`
	File       *Fileinfo   `boil:"File" json:"File" toml:"File" yaml:"File"`
	Session    *LMSSession `boil:"Session" json:"Session" toml:"Session" yaml:"Session"`
	UploadedBy *User       `boil:"UploadedBy" json:"UploadedBy" toml:"UploadedBy" yaml:"UploadedBy"`
}

// NewStruct creates a new relationship struct
func (*classMediumR) NewStruct() *classMediumR {
	return &classMediumR{}
}

func (o *ClassMedium) GetClass() *Class {
	if o == nil {
		return nil
	}

	return o.R.GetClass()
}

func (r *classMediumR) GetClass() *Class {
	if r == nil {
		return nil
	}

	return r.Class
}

func (o *ClassMedium) GetFile() *Fileinfo {
	if o == nil {
		return nil
	}

	return o.R.GetFile()
}

func (r *classMediumR) GetFile() *Fileinfo {
	if r == nil {
		return nil
	}

	return r.File
}

func (o *ClassMedium) GetSession() *LMSSession {
	if o == nil {
		return nil
	}

	return o.R.GetSession()
}

func (r *classMediumR) GetSession() *LMSSession {
	if r == nil {
		return nil
	}

	return r.Session
}

func (o *ClassMedium) GetUploadedBy() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUploadedBy()
}

func (r *classMediumR) GetUploadedBy() *User {
	if r == nil {
		return nil
	}

	return r.UploadedBy
}

// classMediumL is where Load methods for each relationship are stored.
type classMediumL struct{}

var (
	classMediumAllColumns            = []string{"id", "class_id", "session_id", "title", "file_url", "file_type", "uploaded_by_id", "file_id", "createat", "updateat"}
	classMediumColumnsWithoutDefault = []string{"id", "class_id", "file_url", "file_type", "uploaded_by_id", "file_id", "createat", "updateat"}
	classMediumColumnsWithDefault    = []string{"session_id", "title"}
	classMediumPrimaryKeyColumns     = []string{"id"}
	classMediumGeneratedColumns      = []string{}
)

type (
	// ClassMediumSlice is an alias for a slice of pointers to ClassMedium.
	// This should almost always be used instead of []ClassMedium.
	ClassMediumSlice []*ClassMedium

	classMediumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	classMediumType                 = reflect.TypeOf(&ClassMedium{})
	classMediumMapping              = queries.MakeStructMapping(classMediumType)
	classMediumPrimaryKeyMapping, _ = queries.BindMapping(classMediumType, classMediumMapping, classMediumPrimaryKeyColumns)
	classMediumInsertCacheMut       sync.RWMutex
	classMediumInsertCache          = make(map[string]insertCache)
	classMediumUpdateCacheMut       sync.RWMutex
	classMediumUpdateCache          = make(map[string]updateCache)
	classMediumUpsertCacheMut       sync.RWMutex
	classMediumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single classMedium record from the query.
func (q classMediumQuery) One(exec boil.Executor) (*ClassMedium, error) {
	o := &ClassMedium{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: failed to execute a one query for class_media")
	}

	return o, nil
}

// All returns all ClassMedium records from the query.
func (q classMediumQuery) All(exec boil.Executor) (ClassMediumSlice, error) {
	var o []*ClassMedium

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "lms_models: failed to assign all query results to ClassMedium slice")
	}

	return o, nil
}

// Count returns the count of all ClassMedium records in the query.
func (q classMediumQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to count class_media rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q classMediumQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: failed to check if class_media exists")
	}

	return count > 0, nil
}

// Class pointed to by the foreign key.
func (o *ClassMedium) Class(mods ...qm.QueryMod) classQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ClassID),
	}

	queryMods = append(queryMods, mods...)

	return Classes(queryMods...)
}

// File pointed to by the foreign key.
func (o *ClassMedium) File(mods ...qm.QueryMod) fileinfoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FileID),
	}

	queryMods = append(queryMods, mods...)

	return Fileinfos(queryMods...)
}

// Session pointed to by the foreign key.
func (o *ClassMedium) Session(mods ...qm.QueryMod) lmsSessionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SessionID),
	}

	queryMods = append(queryMods, mods...)

	return LMSSessions(queryMods...)
}

// UploadedBy pointed to by the foreign key.
func (o *ClassMedium) UploadedBy(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UploadedByID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadClass allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classMediumL) LoadClass(e boil.Executor, singular bool, maybeClassMedium any, mods queries.Applicator) error {
	var slice []*ClassMedium
	var object *ClassMedium

	if singular {
		var ok bool
		object, ok = maybeClassMedium.(*ClassMedium)
		if !ok {
			object = new(ClassMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassMedium))
			}
		}
	} else {
		s, ok := maybeClassMedium.(*[]*ClassMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassMedium))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &classMediumR{}
		}
		args[object.ClassID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classMediumR{}
			}

			args[obj.ClassID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`classes`),
		qm.WhereIn(`classes.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Class")
	}

	var resultSlice []*Class
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Class")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for classes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for classes")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Class = foreign
		if foreign.R == nil {
			foreign.R = &classR{}
		}
		foreign.R.ClassMedia = append(foreign.R.ClassMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ClassID == foreign.ID {
				local.R.Class = foreign
				if foreign.R == nil {
					foreign.R = &classR{}
				}
				foreign.R.ClassMedia = append(foreign.R.ClassMedia, local)
				break
			}
		}
	}

	return nil
}

// LoadFile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classMediumL) LoadFile(e boil.Executor, singular bool, maybeClassMedium any, mods queries.Applicator) error {
	var slice []*ClassMedium
	var object *ClassMedium

	if singular {
		var ok bool
		object, ok = maybeClassMedium.(*ClassMedium)
		if !ok {
			object = new(ClassMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassMedium))
			}
		}
	} else {
		s, ok := maybeClassMedium.(*[]*ClassMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassMedium))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &classMediumR{}
		}
		args[object.FileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classMediumR{}
			}

			args[obj.FileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`fileinfo`),
		qm.WhereIn(`fileinfo.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Fileinfo")
	}

	var resultSlice []*Fileinfo
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Fileinfo")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for fileinfo")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for fileinfo")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.File = foreign
		if foreign.R == nil {
			foreign.R = &fileinfoR{}
		}
		foreign.R.FileClassMedia = append(foreign.R.FileClassMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FileID == foreign.ID {
				local.R.File = foreign
				if foreign.R == nil {
					foreign.R = &fileinfoR{}
				}
				foreign.R.FileClassMedia = append(foreign.R.FileClassMedia, local)
				break
			}
		}
	}

	return nil
}

// LoadSession allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classMediumL) LoadSession(e boil.Executor, singular bool, maybeClassMedium any, mods queries.Applicator) error {
	var slice []*ClassMedium
	var object *ClassMedium

	if singular {
		var ok bool
		object, ok = maybeClassMedium.(*ClassMedium)
		if !ok {
			object = new(ClassMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassMedium))
			}
		}
	} else {
		s, ok := maybeClassMedium.(*[]*ClassMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassMedium))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &classMediumR{}
		}
		if !queries.IsNil(object.SessionID) {
			args[object.SessionID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classMediumR{}
			}

			if !queries.IsNil(obj.SessionID) {
				args[obj.SessionID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`lms_sessions`),
		qm.WhereIn(`lms_sessions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load LMSSession")
	}

	var resultSlice []*LMSSession
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice LMSSession")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for lms_sessions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for lms_sessions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Session = foreign
		if foreign.R == nil {
			foreign.R = &lmsSessionR{}
		}
		foreign.R.SessionClassMedia = append(foreign.R.SessionClassMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.SessionID, foreign.ID) {
				local.R.Session = foreign
				if foreign.R == nil {
					foreign.R = &lmsSessionR{}
				}
				foreign.R.SessionClassMedia = append(foreign.R.SessionClassMedia, local)
				break
			}
		}
	}

	return nil
}

// LoadUploadedBy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (classMediumL) LoadUploadedBy(e boil.Executor, singular bool, maybeClassMedium any, mods queries.Applicator) error {
	var slice []*ClassMedium
	var object *ClassMedium

	if singular {
		var ok bool
		object, ok = maybeClassMedium.(*ClassMedium)
		if !ok {
			object = new(ClassMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeClassMedium))
			}
		}
	} else {
		s, ok := maybeClassMedium.(*[]*ClassMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeClassMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeClassMedium))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &classMediumR{}
		}
		args[object.UploadedByID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &classMediumR{}
			}

			args[obj.UploadedByID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UploadedBy = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UploadedByClassMedia = append(foreign.R.UploadedByClassMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UploadedByID == foreign.ID {
				local.R.UploadedBy = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UploadedByClassMedia = append(foreign.R.UploadedByClassMedia, local)
				break
			}
		}
	}

	return nil
}

// SetClass of the classMedium to the related item.
// Sets o.R.Class to related.
// Adds o to related.R.ClassMedia.
func (o *ClassMedium) SetClass(exec boil.Executor, insert bool, related *Class) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"class_id"}),
		strmangle.WhereClause("\"", "\"", 2, classMediumPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ClassID = related.ID
	if o.R == nil {
		o.R = &classMediumR{
			Class: related,
		}
	} else {
		o.R.Class = related
	}

	if related.R == nil {
		related.R = &classR{
			ClassMedia: ClassMediumSlice{o},
		}
	} else {
		related.R.ClassMedia = append(related.R.ClassMedia, o)
	}

	return nil
}

// SetFile of the classMedium to the related item.
// Sets o.R.File to related.
// Adds o to related.R.FileClassMedia.
func (o *ClassMedium) SetFile(exec boil.Executor, insert bool, related *Fileinfo) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
		strmangle.WhereClause("\"", "\"", 2, classMediumPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FileID = related.ID
	if o.R == nil {
		o.R = &classMediumR{
			File: related,
		}
	} else {
		o.R.File = related
	}

	if related.R == nil {
		related.R = &fileinfoR{
			FileClassMedia: ClassMediumSlice{o},
		}
	} else {
		related.R.FileClassMedia = append(related.R.FileClassMedia, o)
	}

	return nil
}

// SetSession of the classMedium to the related item.
// Sets o.R.Session to related.
// Adds o to related.R.SessionClassMedia.
func (o *ClassMedium) SetSession(exec boil.Executor, insert bool, related *LMSSession) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"session_id"}),
		strmangle.WhereClause("\"", "\"", 2, classMediumPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.SessionID, related.ID)
	if o.R == nil {
		o.R = &classMediumR{
			Session: related,
		}
	} else {
		o.R.Session = related
	}

	if related.R == nil {
		related.R = &lmsSessionR{
			SessionClassMedia: ClassMediumSlice{o},
		}
	} else {
		related.R.SessionClassMedia = append(related.R.SessionClassMedia, o)
	}

	return nil
}

// RemoveSession relationship.
// Sets o.R.Session to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ClassMedium) RemoveSession(exec boil.Executor, related *LMSSession) error {
	var err error

	queries.SetScanner(&o.SessionID, nil)
	if _, err = o.Update(exec, boil.Whitelist("session_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Session = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.SessionClassMedia {
		if queries.Equal(o.SessionID, ri.SessionID) {
			continue
		}

		ln := len(related.R.SessionClassMedia)
		if ln > 1 && i < ln-1 {
			related.R.SessionClassMedia[i] = related.R.SessionClassMedia[ln-1]
		}
		related.R.SessionClassMedia = related.R.SessionClassMedia[:ln-1]
		break
	}
	return nil
}

// SetUploadedBy of the classMedium to the related item.
// Sets o.R.UploadedBy to related.
// Adds o to related.R.UploadedByClassMedia.
func (o *ClassMedium) SetUploadedBy(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"class_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"uploaded_by_id"}),
		strmangle.WhereClause("\"", "\"", 2, classMediumPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UploadedByID = related.ID
	if o.R == nil {
		o.R = &classMediumR{
			UploadedBy: related,
		}
	} else {
		o.R.UploadedBy = related
	}

	if related.R == nil {
		related.R = &userR{
			UploadedByClassMedia: ClassMediumSlice{o},
		}
	} else {
		related.R.UploadedByClassMedia = append(related.R.UploadedByClassMedia, o)
	}

	return nil
}

// ClassMedia retrieves all the records using an executor.
func ClassMedia(mods ...qm.QueryMod) classMediumQuery {
	mods = append(mods, qm.From("\"class_media\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"class_media\".*"})
	}

	return classMediumQuery{q}
}

// FindClassMedium retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindClassMedium(exec boil.Executor, iD string, selectCols ...string) (*ClassMedium, error) {
	classMediumObj := &ClassMedium{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"class_media\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, classMediumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: unable to select from class_media")
	}

	return classMediumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ClassMedium) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("lms_models: no class_media provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(classMediumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	classMediumInsertCacheMut.RLock()
	cache, cached := classMediumInsertCache[key]
	classMediumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			classMediumAllColumns,
			classMediumColumnsWithDefault,
			classMediumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(classMediumType, classMediumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(classMediumType, classMediumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"class_media\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"class_media\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "lms_models: unable to insert into class_media")
	}

	if !cached {
		classMediumInsertCacheMut.Lock()
		classMediumInsertCache[key] = cache
		classMediumInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the ClassMedium.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ClassMedium) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	classMediumUpdateCacheMut.RLock()
	cache, cached := classMediumUpdateCache[key]
	classMediumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			classMediumAllColumns,
			classMediumPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("lms_models: unable to update class_media, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"class_media\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, classMediumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(classMediumType, classMediumMapping, append(wl, classMediumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update class_media row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by update for class_media")
	}

	if !cached {
		classMediumUpdateCacheMut.Lock()
		classMediumUpdateCache[key] = cache
		classMediumUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q classMediumQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all for class_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected for class_media")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ClassMediumSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("lms_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"class_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, classMediumPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all in classMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected all in update all classMedium")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ClassMedium) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("lms_models: no class_media provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(classMediumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	classMediumUpsertCacheMut.RLock()
	cache, cached := classMediumUpsertCache[key]
	classMediumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			classMediumAllColumns,
			classMediumColumnsWithDefault,
			classMediumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			classMediumAllColumns,
			classMediumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("lms_models: unable to upsert class_media, could not build update column list")
		}

		ret := strmangle.SetComplement(classMediumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(classMediumPrimaryKeyColumns) == 0 {
				return errors.New("lms_models: unable to upsert class_media, could not build conflict column list")
			}

			conflict = make([]string, len(classMediumPrimaryKeyColumns))
			copy(conflict, classMediumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"class_media\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(classMediumType, classMediumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(classMediumType, classMediumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to upsert class_media")
	}

	if !cached {
		classMediumUpsertCacheMut.Lock()
		classMediumUpsertCache[key] = cache
		classMediumUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single ClassMedium record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ClassMedium) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("lms_models: no ClassMedium provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), classMediumPrimaryKeyMapping)
	sql := "DELETE FROM \"class_media\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete from class_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by delete for class_media")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q classMediumQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("lms_models: no classMediumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from class_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for class_media")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ClassMediumSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"class_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classMediumPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from classMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for class_media")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ClassMedium) Reload(exec boil.Executor) error {
	ret, err := FindClassMedium(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ClassMediumSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ClassMediumSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), classMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"class_media\".* FROM \"class_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, classMediumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to reload all in ClassMediumSlice")
	}

	*o = slice

	return nil
}

// ClassMediumExists checks if the ClassMedium row exists.
func ClassMediumExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"class_media\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: unable to check if class_media exists")
	}

	return exists, nil
}

// Exists checks if the ClassMedium row exists.
func (o *ClassMedium) Exists(exec boil.Executor) (bool, error) {
	return ClassMediumExists(exec, o.ID)
}
