// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package lms_models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// CourseLesson is an object representing the database table.
type CourseLesson struct {
	ID            string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	CourseID      string      `boil:"course_id" json:"course_id" toml:"course_id" yaml:"course_id"`
	SessionNumber int         `boil:"session_number" json:"session_number" toml:"session_number" yaml:"session_number"`
	Title         null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	Unit          null.String `boil:"unit" json:"unit,omitempty" toml:"unit" yaml:"unit,omitempty"`
	Pages         null.String `boil:"pages" json:"pages,omitempty" toml:"pages" yaml:"pages,omitempty"`
	Objectives    null.String `boil:"objectives" json:"objectives,omitempty" toml:"objectives" yaml:"objectives,omitempty"`
	Createat      int64       `boil:"createat" json:"createat" toml:"createat" yaml:"createat"`
	Updateat      int64       `boil:"updateat" json:"updateat" toml:"updateat" yaml:"updateat"`

	R *courseLessonR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L courseLessonL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var CourseLessonColumns = struct {
	ID            string
	CourseID      string
	SessionNumber string
	Title         string
	Unit          string
	Pages         string
	Objectives    string
	Createat      string
	Updateat      string
}{
	ID:            "id",
	CourseID:      "course_id",
	SessionNumber: "session_number",
	Title:         "title",
	Unit:          "unit",
	Pages:         "pages",
	Objectives:    "objectives",
	Createat:      "createat",
	Updateat:      "updateat",
}

var CourseLessonTableColumns = struct {
	ID            string
	CourseID      string
	SessionNumber string
	Title         string
	Unit          string
	Pages         string
	Objectives    string
	Createat      string
	Updateat      string
}{
	ID:            "course_lessons.id",
	CourseID:      "course_lessons.course_id",
	SessionNumber: "course_lessons.session_number",
	Title:         "course_lessons.title",
	Unit:          "course_lessons.unit",
	Pages:         "course_lessons.pages",
	Objectives:    "course_lessons.objectives",
	Createat:      "course_lessons.createat",
	Updateat:      "course_lessons.updateat",
}

// Generated where

var CourseLessonWhere = struct {
	ID            whereHelperstring
	CourseID      whereHelperstring
	SessionNumber whereHelperint
	Title         whereHelpernull_String
	Unit          whereHelpernull_String
	Pages         whereHelpernull_String
	Objectives    whereHelpernull_String
	Createat      whereHelperint64
	Updateat      whereHelperint64
}{
	ID:            whereHelperstring{field: "\"course_lessons\".\"id\""},
	CourseID:      whereHelperstring{field: "\"course_lessons\".\"course_id\""},
	SessionNumber: whereHelperint{field: "\"course_lessons\".\"session_number\""},
	Title:         whereHelpernull_String{field: "\"course_lessons\".\"title\""},
	Unit:          whereHelpernull_String{field: "\"course_lessons\".\"unit\""},
	Pages:         whereHelpernull_String{field: "\"course_lessons\".\"pages\""},
	Objectives:    whereHelpernull_String{field: "\"course_lessons\".\"objectives\""},
	Createat:      whereHelperint64{field: "\"course_lessons\".\"createat\""},
	Updateat:      whereHelperint64{field: "\"course_lessons\".\"updateat\""},
}

// CourseLessonRels is where relationship names are stored.
var CourseLessonRels = struct {
	Course            string
	LessonLMSSessions string
}{
	Course:            "Course",
	LessonLMSSessions: "LessonLMSSessions",
}

// courseLessonR is where relationships are stored.
type courseLessonR struct {
	Course            *Course         `boil:"Course" json:"Course" toml:"Course" yaml:"Course"`
	LessonLMSSessions LMSSessionSlice `boil:"LessonLMSSessions" json:"LessonLMSSessions" toml:"LessonLMSSessions" yaml:"LessonLMSSessions"`
}

// NewStruct creates a new relationship struct
func (*courseLessonR) NewStruct() *courseLessonR {
	return &courseLessonR{}
}

func (o *CourseLesson) GetCourse() *Course {
	if o == nil {
		return nil
	}

	return o.R.GetCourse()
}

func (r *courseLessonR) GetCourse() *Course {
	if r == nil {
		return nil
	}

	return r.Course
}

func (o *CourseLesson) GetLessonLMSSessions() LMSSessionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLessonLMSSessions()
}

func (r *courseLessonR) GetLessonLMSSessions() LMSSessionSlice {
	if r == nil {
		return nil
	}

	return r.LessonLMSSessions
}

// courseLessonL is where Load methods for each relationship are stored.
type courseLessonL struct{}

var (
	courseLessonAllColumns            = []string{"id", "course_id", "session_number", "title", "unit", "pages", "objectives", "createat", "updateat"}
	courseLessonColumnsWithoutDefault = []string{"id", "course_id", "session_number", "createat", "updateat"}
	courseLessonColumnsWithDefault    = []string{"title", "unit", "pages", "objectives"}
	courseLessonPrimaryKeyColumns     = []string{"id"}
	courseLessonGeneratedColumns      = []string{}
)

type (
	// CourseLessonSlice is an alias for a slice of pointers to CourseLesson.
	// This should almost always be used instead of []CourseLesson.
	CourseLessonSlice []*CourseLesson

	courseLessonQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	courseLessonType                 = reflect.TypeOf(&CourseLesson{})
	courseLessonMapping              = queries.MakeStructMapping(courseLessonType)
	courseLessonPrimaryKeyMapping, _ = queries.BindMapping(courseLessonType, courseLessonMapping, courseLessonPrimaryKeyColumns)
	courseLessonInsertCacheMut       sync.RWMutex
	courseLessonInsertCache          = make(map[string]insertCache)
	courseLessonUpdateCacheMut       sync.RWMutex
	courseLessonUpdateCache          = make(map[string]updateCache)
	courseLessonUpsertCacheMut       sync.RWMutex
	courseLessonUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single courseLesson record from the query.
func (q courseLessonQuery) One(exec boil.Executor) (*CourseLesson, error) {
	o := &CourseLesson{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: failed to execute a one query for course_lessons")
	}

	return o, nil
}

// All returns all CourseLesson records from the query.
func (q courseLessonQuery) All(exec boil.Executor) (CourseLessonSlice, error) {
	var o []*CourseLesson

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "lms_models: failed to assign all query results to CourseLesson slice")
	}

	return o, nil
}

// Count returns the count of all CourseLesson records in the query.
func (q courseLessonQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to count course_lessons rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q courseLessonQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: failed to check if course_lessons exists")
	}

	return count > 0, nil
}

// Course pointed to by the foreign key.
func (o *CourseLesson) Course(mods ...qm.QueryMod) courseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CourseID),
	}

	queryMods = append(queryMods, mods...)

	return Courses(queryMods...)
}

// LessonLMSSessions retrieves all the lms_session's LMSSessions with an executor via lesson_id column.
func (o *CourseLesson) LessonLMSSessions(mods ...qm.QueryMod) lmsSessionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"lms_sessions\".\"lesson_id\"=?", o.ID),
	)

	return LMSSessions(queryMods...)
}

// LoadCourse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (courseLessonL) LoadCourse(e boil.Executor, singular bool, maybeCourseLesson any, mods queries.Applicator) error {
	var slice []*CourseLesson
	var object *CourseLesson

	if singular {
		var ok bool
		object, ok = maybeCourseLesson.(*CourseLesson)
		if !ok {
			object = new(CourseLesson)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourseLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourseLesson))
			}
		}
	} else {
		s, ok := maybeCourseLesson.(*[]*CourseLesson)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourseLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourseLesson))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &courseLessonR{}
		}
		args[object.CourseID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseLessonR{}
			}

			args[obj.CourseID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`courses`),
		qm.WhereIn(`courses.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Course")
	}

	var resultSlice []*Course
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Course")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for courses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for courses")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Course = foreign
		if foreign.R == nil {
			foreign.R = &courseR{}
		}
		foreign.R.CourseLessons = append(foreign.R.CourseLessons, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CourseID == foreign.ID {
				local.R.Course = foreign
				if foreign.R == nil {
					foreign.R = &courseR{}
				}
				foreign.R.CourseLessons = append(foreign.R.CourseLessons, local)
				break
			}
		}
	}

	return nil
}

// LoadLessonLMSSessions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (courseLessonL) LoadLessonLMSSessions(e boil.Executor, singular bool, maybeCourseLesson any, mods queries.Applicator) error {
	var slice []*CourseLesson
	var object *CourseLesson

	if singular {
		var ok bool
		object, ok = maybeCourseLesson.(*CourseLesson)
		if !ok {
			object = new(CourseLesson)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeCourseLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeCourseLesson))
			}
		}
	} else {
		s, ok := maybeCourseLesson.(*[]*CourseLesson)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeCourseLesson)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeCourseLesson))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &courseLessonR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &courseLessonR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`lms_sessions`),
		qm.WhereIn(`lms_sessions.lesson_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load lms_sessions")
	}

	var resultSlice []*LMSSession
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice lms_sessions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on lms_sessions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for lms_sessions")
	}

	if singular {
		object.R.LessonLMSSessions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &lmsSessionR{}
			}
			foreign.R.Lesson = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.LessonID {
				local.R.LessonLMSSessions = append(local.R.LessonLMSSessions, foreign)
				if foreign.R == nil {
					foreign.R = &lmsSessionR{}
				}
				foreign.R.Lesson = local
				break
			}
		}
	}

	return nil
}

// SetCourse of the courseLesson to the related item.
// Sets o.R.Course to related.
// Adds o to related.R.CourseLessons.
func (o *CourseLesson) SetCourse(exec boil.Executor, insert bool, related *Course) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"course_lessons\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
		strmangle.WhereClause("\"", "\"", 2, courseLessonPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CourseID = related.ID
	if o.R == nil {
		o.R = &courseLessonR{
			Course: related,
		}
	} else {
		o.R.Course = related
	}

	if related.R == nil {
		related.R = &courseR{
			CourseLessons: CourseLessonSlice{o},
		}
	} else {
		related.R.CourseLessons = append(related.R.CourseLessons, o)
	}

	return nil
}

// AddLessonLMSSessions adds the given related objects to the existing relationships
// of the course_lesson, optionally inserting them as new records.
// Appends related to o.R.LessonLMSSessions.
// Sets related.R.Lesson appropriately.
func (o *CourseLesson) AddLessonLMSSessions(exec boil.Executor, insert bool, related ...*LMSSession) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.LessonID = o.ID
			if err = rel.Insert(exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"lms_sessions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"lesson_id"}),
				strmangle.WhereClause("\"", "\"", 2, lmsSessionPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}
			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.LessonID = o.ID
		}
	}

	if o.R == nil {
		o.R = &courseLessonR{
			LessonLMSSessions: related,
		}
	} else {
		o.R.LessonLMSSessions = append(o.R.LessonLMSSessions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &lmsSessionR{
				Lesson: o,
			}
		} else {
			rel.R.Lesson = o
		}
	}
	return nil
}

// CourseLessons retrieves all the records using an executor.
func CourseLessons(mods ...qm.QueryMod) courseLessonQuery {
	mods = append(mods, qm.From("\"course_lessons\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"course_lessons\".*"})
	}

	return courseLessonQuery{q}
}

// FindCourseLesson retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCourseLesson(exec boil.Executor, iD string, selectCols ...string) (*CourseLesson, error) {
	courseLessonObj := &CourseLesson{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"course_lessons\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, courseLessonObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: unable to select from course_lessons")
	}

	return courseLessonObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *CourseLesson) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("lms_models: no course_lessons provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(courseLessonColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	courseLessonInsertCacheMut.RLock()
	cache, cached := courseLessonInsertCache[key]
	courseLessonInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			courseLessonAllColumns,
			courseLessonColumnsWithDefault,
			courseLessonColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(courseLessonType, courseLessonMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(courseLessonType, courseLessonMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"course_lessons\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"course_lessons\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "lms_models: unable to insert into course_lessons")
	}

	if !cached {
		courseLessonInsertCacheMut.Lock()
		courseLessonInsertCache[key] = cache
		courseLessonInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the CourseLesson.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *CourseLesson) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	courseLessonUpdateCacheMut.RLock()
	cache, cached := courseLessonUpdateCache[key]
	courseLessonUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			courseLessonAllColumns,
			courseLessonPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("lms_models: unable to update course_lessons, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"course_lessons\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, courseLessonPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(courseLessonType, courseLessonMapping, append(wl, courseLessonPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update course_lessons row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by update for course_lessons")
	}

	if !cached {
		courseLessonUpdateCacheMut.Lock()
		courseLessonUpdateCache[key] = cache
		courseLessonUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q courseLessonQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all for course_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected for course_lessons")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CourseLessonSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("lms_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"course_lessons\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, courseLessonPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all in courseLesson slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected all in update all courseLesson")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *CourseLesson) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("lms_models: no course_lessons provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(courseLessonColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	courseLessonUpsertCacheMut.RLock()
	cache, cached := courseLessonUpsertCache[key]
	courseLessonUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			courseLessonAllColumns,
			courseLessonColumnsWithDefault,
			courseLessonColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			courseLessonAllColumns,
			courseLessonPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("lms_models: unable to upsert course_lessons, could not build update column list")
		}

		ret := strmangle.SetComplement(courseLessonAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(courseLessonPrimaryKeyColumns) == 0 {
				return errors.New("lms_models: unable to upsert course_lessons, could not build conflict column list")
			}

			conflict = make([]string, len(courseLessonPrimaryKeyColumns))
			copy(conflict, courseLessonPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"course_lessons\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(courseLessonType, courseLessonMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(courseLessonType, courseLessonMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to upsert course_lessons")
	}

	if !cached {
		courseLessonUpsertCacheMut.Lock()
		courseLessonUpsertCache[key] = cache
		courseLessonUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single CourseLesson record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *CourseLesson) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("lms_models: no CourseLesson provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), courseLessonPrimaryKeyMapping)
	sql := "DELETE FROM \"course_lessons\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete from course_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by delete for course_lessons")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q courseLessonQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("lms_models: no courseLessonQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from course_lessons")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for course_lessons")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CourseLessonSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"course_lessons\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, courseLessonPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from courseLesson slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for course_lessons")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *CourseLesson) Reload(exec boil.Executor) error {
	ret, err := FindCourseLesson(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CourseLessonSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := CourseLessonSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), courseLessonPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"course_lessons\".* FROM \"course_lessons\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, courseLessonPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to reload all in CourseLessonSlice")
	}

	*o = slice

	return nil
}

// CourseLessonExists checks if the CourseLesson row exists.
func CourseLessonExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"course_lessons\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: unable to check if course_lessons exists")
	}

	return exists, nil
}

// Exists checks if the CourseLesson row exists.
func (o *CourseLesson) Exists(exec boil.Executor) (bool, error) {
	return CourseLessonExists(exec, o.ID)
}
