// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package lms_models

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Material is an object representing the database table.
type Material struct {
	ID           string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Title        string      `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description  null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	CourseID     string      `boil:"course_id" json:"course_id" toml:"course_id" yaml:"course_id"`
	Unit         null.String `boil:"unit" json:"unit,omitempty" toml:"unit" yaml:"unit,omitempty"`
	Visibility   string      `boil:"visibility" json:"visibility" toml:"visibility" yaml:"visibility"`
	FileID       string      `boil:"file_id" json:"file_id" toml:"file_id" yaml:"file_id"`
	UploadedByID string      `boil:"uploaded_by_id" json:"uploaded_by_id" toml:"uploaded_by_id" yaml:"uploaded_by_id"`
	Version      int         `boil:"version" json:"version" toml:"version" yaml:"version"`
	Createat     int64       `boil:"createat" json:"createat" toml:"createat" yaml:"createat"`
	Updateat     int64       `boil:"updateat" json:"updateat" toml:"updateat" yaml:"updateat"`

	R *materialR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L materialL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MaterialColumns = struct {
	ID           string
	Title        string
	Description  string
	CourseID     string
	Unit         string
	Visibility   string
	FileID       string
	UploadedByID string
	Version      string
	Createat     string
	Updateat     string
}{
	ID:           "id",
	Title:        "title",
	Description:  "description",
	CourseID:     "course_id",
	Unit:         "unit",
	Visibility:   "visibility",
	FileID:       "file_id",
	UploadedByID: "uploaded_by_id",
	Version:      "version",
	Createat:     "createat",
	Updateat:     "updateat",
}

var MaterialTableColumns = struct {
	ID           string
	Title        string
	Description  string
	CourseID     string
	Unit         string
	Visibility   string
	FileID       string
	UploadedByID string
	Version      string
	Createat     string
	Updateat     string
}{
	ID:           "materials.id",
	Title:        "materials.title",
	Description:  "materials.description",
	CourseID:     "materials.course_id",
	Unit:         "materials.unit",
	Visibility:   "materials.visibility",
	FileID:       "materials.file_id",
	UploadedByID: "materials.uploaded_by_id",
	Version:      "materials.version",
	Createat:     "materials.createat",
	Updateat:     "materials.updateat",
}

// Generated where

var MaterialWhere = struct {
	ID           whereHelperstring
	Title        whereHelperstring
	Description  whereHelpernull_String
	CourseID     whereHelperstring
	Unit         whereHelpernull_String
	Visibility   whereHelperstring
	FileID       whereHelperstring
	UploadedByID whereHelperstring
	Version      whereHelperint
	Createat     whereHelperint64
	Updateat     whereHelperint64
}{
	ID:           whereHelperstring{field: "\"materials\".\"id\""},
	Title:        whereHelperstring{field: "\"materials\".\"title\""},
	Description:  whereHelpernull_String{field: "\"materials\".\"description\""},
	CourseID:     whereHelperstring{field: "\"materials\".\"course_id\""},
	Unit:         whereHelpernull_String{field: "\"materials\".\"unit\""},
	Visibility:   whereHelperstring{field: "\"materials\".\"visibility\""},
	FileID:       whereHelperstring{field: "\"materials\".\"file_id\""},
	UploadedByID: whereHelperstring{field: "\"materials\".\"uploaded_by_id\""},
	Version:      whereHelperint{field: "\"materials\".\"version\""},
	Createat:     whereHelperint64{field: "\"materials\".\"createat\""},
	Updateat:     whereHelperint64{field: "\"materials\".\"updateat\""},
}

// MaterialRels is where relationship names are stored.
var MaterialRels = struct {
	Course     string
	File       string
	UploadedBy string
}{
	Course:     "Course",
	File:       "File",
	UploadedBy: "UploadedBy",
}

// materialR is where relationships are stored.
type materialR struct {
	Course     *Course   `boil:"Course" json:"Course" toml:"Course" yaml:"Course"`
	File       *Fileinfo `boil:"File" json:"File" toml:"File" yaml:"File"`
	UploadedBy *User     `boil:"UploadedBy" json:"UploadedBy" toml:"UploadedBy" yaml:"UploadedBy"`
}

// NewStruct creates a new relationship struct
func (*materialR) NewStruct() *materialR {
	return &materialR{}
}

func (o *Material) GetCourse() *Course {
	if o == nil {
		return nil
	}

	return o.R.GetCourse()
}

func (r *materialR) GetCourse() *Course {
	if r == nil {
		return nil
	}

	return r.Course
}

func (o *Material) GetFile() *Fileinfo {
	if o == nil {
		return nil
	}

	return o.R.GetFile()
}

func (r *materialR) GetFile() *Fileinfo {
	if r == nil {
		return nil
	}

	return r.File
}

func (o *Material) GetUploadedBy() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUploadedBy()
}

func (r *materialR) GetUploadedBy() *User {
	if r == nil {
		return nil
	}

	return r.UploadedBy
}

// materialL is where Load methods for each relationship are stored.
type materialL struct{}

var (
	materialAllColumns            = []string{"id", "title", "description", "course_id", "unit", "visibility", "file_id", "uploaded_by_id", "version", "createat", "updateat"}
	materialColumnsWithoutDefault = []string{"id", "title", "course_id", "file_id", "uploaded_by_id", "createat", "updateat"}
	materialColumnsWithDefault    = []string{"description", "unit", "visibility", "version"}
	materialPrimaryKeyColumns     = []string{"id"}
	materialGeneratedColumns      = []string{}
)

type (
	// MaterialSlice is an alias for a slice of pointers to Material.
	// This should almost always be used instead of []Material.
	MaterialSlice []*Material

	materialQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	materialType                 = reflect.TypeOf(&Material{})
	materialMapping              = queries.MakeStructMapping(materialType)
	materialPrimaryKeyMapping, _ = queries.BindMapping(materialType, materialMapping, materialPrimaryKeyColumns)
	materialInsertCacheMut       sync.RWMutex
	materialInsertCache          = make(map[string]insertCache)
	materialUpdateCacheMut       sync.RWMutex
	materialUpdateCache          = make(map[string]updateCache)
	materialUpsertCacheMut       sync.RWMutex
	materialUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single material record from the query.
func (q materialQuery) One(exec boil.Executor) (*Material, error) {
	o := &Material{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: failed to execute a one query for materials")
	}

	return o, nil
}

// All returns all Material records from the query.
func (q materialQuery) All(exec boil.Executor) (MaterialSlice, error) {
	var o []*Material

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "lms_models: failed to assign all query results to Material slice")
	}

	return o, nil
}

// Count returns the count of all Material records in the query.
func (q materialQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to count materials rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q materialQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: failed to check if materials exists")
	}

	return count > 0, nil
}

// Course pointed to by the foreign key.
func (o *Material) Course(mods ...qm.QueryMod) courseQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CourseID),
	}

	queryMods = append(queryMods, mods...)

	return Courses(queryMods...)
}

// File pointed to by the foreign key.
func (o *Material) File(mods ...qm.QueryMod) fileinfoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FileID),
	}

	queryMods = append(queryMods, mods...)

	return Fileinfos(queryMods...)
}

// UploadedBy pointed to by the foreign key.
func (o *Material) UploadedBy(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UploadedByID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadCourse allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (materialL) LoadCourse(e boil.Executor, singular bool, maybeMaterial any, mods queries.Applicator) error {
	var slice []*Material
	var object *Material

	if singular {
		var ok bool
		object, ok = maybeMaterial.(*Material)
		if !ok {
			object = new(Material)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMaterial))
			}
		}
	} else {
		s, ok := maybeMaterial.(*[]*Material)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMaterial))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &materialR{}
		}
		args[object.CourseID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &materialR{}
			}

			args[obj.CourseID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`courses`),
		qm.WhereIn(`courses.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Course")
	}

	var resultSlice []*Course
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Course")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for courses")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for courses")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Course = foreign
		if foreign.R == nil {
			foreign.R = &courseR{}
		}
		foreign.R.Materials = append(foreign.R.Materials, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CourseID == foreign.ID {
				local.R.Course = foreign
				if foreign.R == nil {
					foreign.R = &courseR{}
				}
				foreign.R.Materials = append(foreign.R.Materials, local)
				break
			}
		}
	}

	return nil
}

// LoadFile allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (materialL) LoadFile(e boil.Executor, singular bool, maybeMaterial any, mods queries.Applicator) error {
	var slice []*Material
	var object *Material

	if singular {
		var ok bool
		object, ok = maybeMaterial.(*Material)
		if !ok {
			object = new(Material)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMaterial))
			}
		}
	} else {
		s, ok := maybeMaterial.(*[]*Material)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMaterial))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &materialR{}
		}
		args[object.FileID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &materialR{}
			}

			args[obj.FileID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`fileinfo`),
		qm.WhereIn(`fileinfo.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Fileinfo")
	}

	var resultSlice []*Fileinfo
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Fileinfo")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for fileinfo")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for fileinfo")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.File = foreign
		if foreign.R == nil {
			foreign.R = &fileinfoR{}
		}
		foreign.R.FileMaterials = append(foreign.R.FileMaterials, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FileID == foreign.ID {
				local.R.File = foreign
				if foreign.R == nil {
					foreign.R = &fileinfoR{}
				}
				foreign.R.FileMaterials = append(foreign.R.FileMaterials, local)
				break
			}
		}
	}

	return nil
}

// LoadUploadedBy allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (materialL) LoadUploadedBy(e boil.Executor, singular bool, maybeMaterial any, mods queries.Applicator) error {
	var slice []*Material
	var object *Material

	if singular {
		var ok bool
		object, ok = maybeMaterial.(*Material)
		if !ok {
			object = new(Material)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMaterial))
			}
		}
	} else {
		s, ok := maybeMaterial.(*[]*Material)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMaterial)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMaterial))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &materialR{}
		}
		args[object.UploadedByID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &materialR{}
			}

			args[obj.UploadedByID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UploadedBy = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UploadedByMaterials = append(foreign.R.UploadedByMaterials, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UploadedByID == foreign.ID {
				local.R.UploadedBy = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UploadedByMaterials = append(foreign.R.UploadedByMaterials, local)
				break
			}
		}
	}

	return nil
}

// SetCourse of the material to the related item.
// Sets o.R.Course to related.
// Adds o to related.R.Materials.
func (o *Material) SetCourse(exec boil.Executor, insert bool, related *Course) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"materials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"course_id"}),
		strmangle.WhereClause("\"", "\"", 2, materialPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CourseID = related.ID
	if o.R == nil {
		o.R = &materialR{
			Course: related,
		}
	} else {
		o.R.Course = related
	}

	if related.R == nil {
		related.R = &courseR{
			Materials: MaterialSlice{o},
		}
	} else {
		related.R.Materials = append(related.R.Materials, o)
	}

	return nil
}

// SetFile of the material to the related item.
// Sets o.R.File to related.
// Adds o to related.R.FileMaterials.
func (o *Material) SetFile(exec boil.Executor, insert bool, related *Fileinfo) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"materials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"file_id"}),
		strmangle.WhereClause("\"", "\"", 2, materialPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FileID = related.ID
	if o.R == nil {
		o.R = &materialR{
			File: related,
		}
	} else {
		o.R.File = related
	}

	if related.R == nil {
		related.R = &fileinfoR{
			FileMaterials: MaterialSlice{o},
		}
	} else {
		related.R.FileMaterials = append(related.R.FileMaterials, o)
	}

	return nil
}

// SetUploadedBy of the material to the related item.
// Sets o.R.UploadedBy to related.
// Adds o to related.R.UploadedByMaterials.
func (o *Material) SetUploadedBy(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"materials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"uploaded_by_id"}),
		strmangle.WhereClause("\"", "\"", 2, materialPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UploadedByID = related.ID
	if o.R == nil {
		o.R = &materialR{
			UploadedBy: related,
		}
	} else {
		o.R.UploadedBy = related
	}

	if related.R == nil {
		related.R = &userR{
			UploadedByMaterials: MaterialSlice{o},
		}
	} else {
		related.R.UploadedByMaterials = append(related.R.UploadedByMaterials, o)
	}

	return nil
}

// Materials retrieves all the records using an executor.
func Materials(mods ...qm.QueryMod) materialQuery {
	mods = append(mods, qm.From("\"materials\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"materials\".*"})
	}

	return materialQuery{q}
}

// FindMaterial retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMaterial(exec boil.Executor, iD string, selectCols ...string) (*Material, error) {
	materialObj := &Material{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"materials\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, materialObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "lms_models: unable to select from materials")
	}

	return materialObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Material) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("lms_models: no materials provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(materialColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	materialInsertCacheMut.RLock()
	cache, cached := materialInsertCache[key]
	materialInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			materialAllColumns,
			materialColumnsWithDefault,
			materialColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(materialType, materialMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(materialType, materialMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"materials\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"materials\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "lms_models: unable to insert into materials")
	}

	if !cached {
		materialInsertCacheMut.Lock()
		materialInsertCache[key] = cache
		materialInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Material.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Material) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	materialUpdateCacheMut.RLock()
	cache, cached := materialUpdateCache[key]
	materialUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			materialAllColumns,
			materialPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("lms_models: unable to update materials, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"materials\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, materialPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(materialType, materialMapping, append(wl, materialPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update materials row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by update for materials")
	}

	if !cached {
		materialUpdateCacheMut.Lock()
		materialUpdateCache[key] = cache
		materialUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q materialQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all for materials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected for materials")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MaterialSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("lms_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), materialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"materials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, materialPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to update all in material slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to retrieve rows affected all in update all material")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Material) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("lms_models: no materials provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(materialColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	materialUpsertCacheMut.RLock()
	cache, cached := materialUpsertCache[key]
	materialUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			materialAllColumns,
			materialColumnsWithDefault,
			materialColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			materialAllColumns,
			materialPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("lms_models: unable to upsert materials, could not build update column list")
		}

		ret := strmangle.SetComplement(materialAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(materialPrimaryKeyColumns) == 0 {
				return errors.New("lms_models: unable to upsert materials, could not build conflict column list")
			}

			conflict = make([]string, len(materialPrimaryKeyColumns))
			copy(conflict, materialPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"materials\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(materialType, materialMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(materialType, materialMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to upsert materials")
	}

	if !cached {
		materialUpsertCacheMut.Lock()
		materialUpsertCache[key] = cache
		materialUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Material record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Material) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("lms_models: no Material provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), materialPrimaryKeyMapping)
	sql := "DELETE FROM \"materials\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete from materials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by delete for materials")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q materialQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("lms_models: no materialQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from materials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for materials")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MaterialSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), materialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"materials\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, materialPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: unable to delete all from material slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "lms_models: failed to get rows affected by deleteall for materials")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Material) Reload(exec boil.Executor) error {
	ret, err := FindMaterial(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MaterialSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MaterialSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), materialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"materials\".* FROM \"materials\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, materialPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "lms_models: unable to reload all in MaterialSlice")
	}

	*o = slice

	return nil
}

// MaterialExists checks if the Material row exists.
func MaterialExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"materials\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "lms_models: unable to check if materials exists")
	}

	return exists, nil
}

// Exists checks if the Material row exists.
func (o *Material) Exists(exec boil.Executor) (bool, error) {
	return MaterialExists(exec, o.ID)
}
