// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	mock "github.com/stretchr/testify/mock"
)

// AttendanceStore is an autogenerated mock type for the AttendanceStore type
type AttendanceStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *AttendanceStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteBySession provides a mock function with given fields: sessionID
func (_m *AttendanceStore) DeleteBySession(sessionID string) error {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *AttendanceStore) Get(id string) (*lms_models.Attendance, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.Attendance, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.Attendance); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySession provides a mock function with given fields: sessionID
func (_m *AttendanceStore) GetBySession(sessionID string) ([]*lms_models.Attendance, error) {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySession")
	}

	var r0 []*lms_models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*lms_models.Attendance, error)); ok {
		return rf(sessionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*lms_models.Attendance); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySessionAndStudent provides a mock function with given fields: sessionID, studentID
func (_m *AttendanceStore) GetBySessionAndStudent(sessionID string, studentID string) (*lms_models.Attendance, error) {
	ret := _m.Called(sessionID, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySessionAndStudent")
	}

	var r0 *lms_models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*lms_models.Attendance, error)); ok {
		return rf(sessionID, studentID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *lms_models.Attendance); ok {
		r0 = rf(sessionID, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(sessionID, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: attendance
func (_m *AttendanceStore) Save(attendance *lms_models.Attendance) (*lms_models.Attendance, error) {
	ret := _m.Called(attendance)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Attendance) (*lms_models.Attendance, error)); ok {
		return rf(attendance)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Attendance) *lms_models.Attendance); ok {
		r0 = rf(attendance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Attendance) error); ok {
		r1 = rf(attendance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAttendanceStore creates a new instance of AttendanceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceStore {
	mock := &AttendanceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
