// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAutoTranslationStore creates a new instance of AutoTranslationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoTranslationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoTranslationStore {
	mock := &AutoTranslationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AutoTranslationStore is an autogenerated mock type for the AutoTranslationStore type
type AutoTranslationStore struct {
	mock.Mock
}

type AutoTranslationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoTranslationStore) EXPECT() *AutoTranslationStore_Expecter {
	return &AutoTranslationStore_Expecter{mock: &_m.Mock}
}

// ClearCaches provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) ClearCaches() {
	_mock.Called()
	return
}

// AutoTranslationStore_ClearCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCaches'
type AutoTranslationStore_ClearCaches_Call struct {
	*mock.Call
}

// ClearCaches is a helper method to define mock.On call
func (_e *AutoTranslationStore_Expecter) ClearCaches() *AutoTranslationStore_ClearCaches_Call {
	return &AutoTranslationStore_ClearCaches_Call{Call: _e.mock.On("ClearCaches")}
}

func (_c *AutoTranslationStore_ClearCaches_Call) Run(run func()) *AutoTranslationStore_ClearCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AutoTranslationStore_ClearCaches_Call) Return() *AutoTranslationStore_ClearCaches_Call {
	_c.Call.Return()
	return _c
}

func (_c *AutoTranslationStore_ClearCaches_Call) RunAndReturn(run func()) *AutoTranslationStore_ClearCaches_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) Get(objectType string, objectID string, dstLang string) (*model.Translation, error) {
	ret := _mock.Called(objectType, objectID, dstLang)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*model.Translation, error)); ok {
		return returnFunc(objectType, objectID, dstLang)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *model.Translation); ok {
		r0 = returnFunc(objectType, objectID, dstLang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(objectType, objectID, dstLang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type AutoTranslationStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - objectType string
//   - objectID string
//   - dstLang string
func (_e *AutoTranslationStore_Expecter) Get(objectType any, objectID any, dstLang any) *AutoTranslationStore_Get_Call {
	return &AutoTranslationStore_Get_Call{Call: _e.mock.On("Get", objectType, objectID, dstLang)}
}

func (_c *AutoTranslationStore_Get_Call) Run(run func(objectType string, objectID string, dstLang string)) *AutoTranslationStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_Get_Call) Return(translation *model.Translation, err error) *AutoTranslationStore_Get_Call {
	_c.Call.Return(translation, err)
	return _c
}

func (_c *AutoTranslationStore_Get_Call) RunAndReturn(run func(objectType string, objectID string, dstLang string) (*model.Translation, error)) *AutoTranslationStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveDestinationLanguages provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetActiveDestinationLanguages(channelID string, excludeUserID string, filterUserIDs []string) ([]string, error) {
	ret := _mock.Called(channelID, excludeUserID, filterUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveDestinationLanguages")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) ([]string, error)); ok {
		return returnFunc(channelID, excludeUserID, filterUserIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) []string); ok {
		r0 = returnFunc(channelID, excludeUserID, filterUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(channelID, excludeUserID, filterUserIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetActiveDestinationLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveDestinationLanguages'
type AutoTranslationStore_GetActiveDestinationLanguages_Call struct {
	*mock.Call
}

// GetActiveDestinationLanguages is a helper method to define mock.On call
//   - channelID string
//   - excludeUserID string
//   - filterUserIDs []string
func (_e *AutoTranslationStore_Expecter) GetActiveDestinationLanguages(channelID any, excludeUserID any, filterUserIDs any) *AutoTranslationStore_GetActiveDestinationLanguages_Call {
	return &AutoTranslationStore_GetActiveDestinationLanguages_Call{Call: _e.mock.On("GetActiveDestinationLanguages", channelID, excludeUserID, filterUserIDs)}
}

func (_c *AutoTranslationStore_GetActiveDestinationLanguages_Call) Run(run func(channelID string, excludeUserID string, filterUserIDs []string)) *AutoTranslationStore_GetActiveDestinationLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetActiveDestinationLanguages_Call) Return(strings []string, err error) *AutoTranslationStore_GetActiveDestinationLanguages_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *AutoTranslationStore_GetActiveDestinationLanguages_Call) RunAndReturn(run func(channelID string, excludeUserID string, filterUserIDs []string) ([]string, error)) *AutoTranslationStore_GetActiveDestinationLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByStatePage provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetAllByStatePage(state model.TranslationState, offset int, limit int) ([]*model.Translation, error) {
	ret := _mock.Called(state, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByStatePage")
	}

	var r0 []*model.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.TranslationState, int, int) ([]*model.Translation, error)); ok {
		return returnFunc(state, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(model.TranslationState, int, int) []*model.Translation); ok {
		r0 = returnFunc(state, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.TranslationState, int, int) error); ok {
		r1 = returnFunc(state, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetAllByStatePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByStatePage'
type AutoTranslationStore_GetAllByStatePage_Call struct {
	*mock.Call
}

// GetAllByStatePage is a helper method to define mock.On call
//   - state model.TranslationState
//   - offset int
//   - limit int
func (_e *AutoTranslationStore_Expecter) GetAllByStatePage(state any, offset any, limit any) *AutoTranslationStore_GetAllByStatePage_Call {
	return &AutoTranslationStore_GetAllByStatePage_Call{Call: _e.mock.On("GetAllByStatePage", state, offset, limit)}
}

func (_c *AutoTranslationStore_GetAllByStatePage_Call) Run(run func(state model.TranslationState, offset int, limit int)) *AutoTranslationStore_GetAllByStatePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.TranslationState
		if args[0] != nil {
			arg0 = args[0].(model.TranslationState)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetAllByStatePage_Call) Return(translations []*model.Translation, err error) *AutoTranslationStore_GetAllByStatePage_Call {
	_c.Call.Return(translations, err)
	return _c
}

func (_c *AutoTranslationStore_GetAllByStatePage_Call) RunAndReturn(run func(state model.TranslationState, offset int, limit int) ([]*model.Translation, error)) *AutoTranslationStore_GetAllByStatePage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllForObject provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetAllForObject(objectType string, objectID string) ([]*model.Translation, error) {
	ret := _mock.Called(objectType, objectID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllForObject")
	}

	var r0 []*model.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]*model.Translation, error)); ok {
		return returnFunc(objectType, objectID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []*model.Translation); ok {
		r0 = returnFunc(objectType, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(objectType, objectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetAllForObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllForObject'
type AutoTranslationStore_GetAllForObject_Call struct {
	*mock.Call
}

// GetAllForObject is a helper method to define mock.On call
//   - objectType string
//   - objectID string
func (_e *AutoTranslationStore_Expecter) GetAllForObject(objectType any, objectID any) *AutoTranslationStore_GetAllForObject_Call {
	return &AutoTranslationStore_GetAllForObject_Call{Call: _e.mock.On("GetAllForObject", objectType, objectID)}
}

func (_c *AutoTranslationStore_GetAllForObject_Call) Run(run func(objectType string, objectID string)) *AutoTranslationStore_GetAllForObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetAllForObject_Call) Return(translations []*model.Translation, err error) *AutoTranslationStore_GetAllForObject_Call {
	_c.Call.Return(translations, err)
	return _c
}

func (_c *AutoTranslationStore_GetAllForObject_Call) RunAndReturn(run func(objectType string, objectID string) ([]*model.Translation, error)) *AutoTranslationStore_GetAllForObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetBatch(objectType string, objectIDs []string, dstLang string) (map[string]*model.Translation, error) {
	ret := _mock.Called(objectType, objectIDs, dstLang)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 map[string]*model.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, string) (map[string]*model.Translation, error)); ok {
		return returnFunc(objectType, objectIDs, dstLang)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, string) map[string]*model.Translation); ok {
		r0 = returnFunc(objectType, objectIDs, dstLang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, string) error); ok {
		r1 = returnFunc(objectType, objectIDs, dstLang)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type AutoTranslationStore_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - objectType string
//   - objectIDs []string
//   - dstLang string
func (_e *AutoTranslationStore_Expecter) GetBatch(objectType any, objectIDs any, dstLang any) *AutoTranslationStore_GetBatch_Call {
	return &AutoTranslationStore_GetBatch_Call{Call: _e.mock.On("GetBatch", objectType, objectIDs, dstLang)}
}

func (_c *AutoTranslationStore_GetBatch_Call) Run(run func(objectType string, objectIDs []string, dstLang string)) *AutoTranslationStore_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetBatch_Call) Return(stringToTranslation map[string]*model.Translation, err error) *AutoTranslationStore_GetBatch_Call {
	_c.Call.Return(stringToTranslation, err)
	return _c
}

func (_c *AutoTranslationStore_GetBatch_Call) RunAndReturn(run func(objectType string, objectIDs []string, dstLang string) (map[string]*model.Translation, error)) *AutoTranslationStore_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStateOlderThan provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetByStateOlderThan(state model.TranslationState, olderThanMillis int64, limit int) ([]*model.Translation, error) {
	ret := _mock.Called(state, olderThanMillis, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByStateOlderThan")
	}

	var r0 []*model.Translation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.TranslationState, int64, int) ([]*model.Translation, error)); ok {
		return returnFunc(state, olderThanMillis, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(model.TranslationState, int64, int) []*model.Translation); ok {
		r0 = returnFunc(state, olderThanMillis, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Translation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.TranslationState, int64, int) error); ok {
		r1 = returnFunc(state, olderThanMillis, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetByStateOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStateOlderThan'
type AutoTranslationStore_GetByStateOlderThan_Call struct {
	*mock.Call
}

// GetByStateOlderThan is a helper method to define mock.On call
//   - state model.TranslationState
//   - olderThanMillis int64
//   - limit int
func (_e *AutoTranslationStore_Expecter) GetByStateOlderThan(state any, olderThanMillis any, limit any) *AutoTranslationStore_GetByStateOlderThan_Call {
	return &AutoTranslationStore_GetByStateOlderThan_Call{Call: _e.mock.On("GetByStateOlderThan", state, olderThanMillis, limit)}
}

func (_c *AutoTranslationStore_GetByStateOlderThan_Call) Run(run func(state model.TranslationState, olderThanMillis int64, limit int)) *AutoTranslationStore_GetByStateOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.TranslationState
		if args[0] != nil {
			arg0 = args[0].(model.TranslationState)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetByStateOlderThan_Call) Return(translations []*model.Translation, err error) *AutoTranslationStore_GetByStateOlderThan_Call {
	_c.Call.Return(translations, err)
	return _c
}

func (_c *AutoTranslationStore_GetByStateOlderThan_Call) RunAndReturn(run func(state model.TranslationState, olderThanMillis int64, limit int) ([]*model.Translation, error)) *AutoTranslationStore_GetByStateOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserLanguage provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) GetUserLanguage(userID string, channelID string) (string, error) {
	ret := _mock.Called(userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLanguage")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(userID, channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(userID, channelID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_GetUserLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserLanguage'
type AutoTranslationStore_GetUserLanguage_Call struct {
	*mock.Call
}

// GetUserLanguage is a helper method to define mock.On call
//   - userID string
//   - channelID string
func (_e *AutoTranslationStore_Expecter) GetUserLanguage(userID any, channelID any) *AutoTranslationStore_GetUserLanguage_Call {
	return &AutoTranslationStore_GetUserLanguage_Call{Call: _e.mock.On("GetUserLanguage", userID, channelID)}
}

func (_c *AutoTranslationStore_GetUserLanguage_Call) Run(run func(userID string, channelID string)) *AutoTranslationStore_GetUserLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_GetUserLanguage_Call) Return(s string, err error) *AutoTranslationStore_GetUserLanguage_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AutoTranslationStore_GetUserLanguage_Call) RunAndReturn(run func(userID string, channelID string) (string, error)) *AutoTranslationStore_GetUserLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateUserAutoTranslation provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) InvalidateUserAutoTranslation(userID string, channelID string) {
	_mock.Called(userID, channelID)
	return
}

// AutoTranslationStore_InvalidateUserAutoTranslation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserAutoTranslation'
type AutoTranslationStore_InvalidateUserAutoTranslation_Call struct {
	*mock.Call
}

// InvalidateUserAutoTranslation is a helper method to define mock.On call
//   - userID string
//   - channelID string
func (_e *AutoTranslationStore_Expecter) InvalidateUserAutoTranslation(userID any, channelID any) *AutoTranslationStore_InvalidateUserAutoTranslation_Call {
	return &AutoTranslationStore_InvalidateUserAutoTranslation_Call{Call: _e.mock.On("InvalidateUserAutoTranslation", userID, channelID)}
}

func (_c *AutoTranslationStore_InvalidateUserAutoTranslation_Call) Run(run func(userID string, channelID string)) *AutoTranslationStore_InvalidateUserAutoTranslation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_InvalidateUserAutoTranslation_Call) Return() *AutoTranslationStore_InvalidateUserAutoTranslation_Call {
	_c.Call.Return()
	return _c
}

func (_c *AutoTranslationStore_InvalidateUserAutoTranslation_Call) RunAndReturn(run func(userID string, channelID string)) *AutoTranslationStore_InvalidateUserAutoTranslation_Call {
	_c.Run(run)
	return _c
}

// InvalidateUserLocaleCache provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) InvalidateUserLocaleCache(userID string) {
	_mock.Called(userID)
	return
}

// AutoTranslationStore_InvalidateUserLocaleCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateUserLocaleCache'
type AutoTranslationStore_InvalidateUserLocaleCache_Call struct {
	*mock.Call
}

// InvalidateUserLocaleCache is a helper method to define mock.On call
//   - userID string
func (_e *AutoTranslationStore_Expecter) InvalidateUserLocaleCache(userID any) *AutoTranslationStore_InvalidateUserLocaleCache_Call {
	return &AutoTranslationStore_InvalidateUserLocaleCache_Call{Call: _e.mock.On("InvalidateUserLocaleCache", userID)}
}

func (_c *AutoTranslationStore_InvalidateUserLocaleCache_Call) Run(run func(userID string)) *AutoTranslationStore_InvalidateUserLocaleCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_InvalidateUserLocaleCache_Call) Return() *AutoTranslationStore_InvalidateUserLocaleCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *AutoTranslationStore_InvalidateUserLocaleCache_Call) RunAndReturn(run func(userID string)) *AutoTranslationStore_InvalidateUserLocaleCache_Call {
	_c.Run(run)
	return _c
}

// IsUserEnabled provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) IsUserEnabled(userID string, channelID string) (bool, error) {
	ret := _mock.Called(userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserEnabled")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(userID, channelID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(userID, channelID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, channelID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AutoTranslationStore_IsUserEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserEnabled'
type AutoTranslationStore_IsUserEnabled_Call struct {
	*mock.Call
}

// IsUserEnabled is a helper method to define mock.On call
//   - userID string
//   - channelID string
func (_e *AutoTranslationStore_Expecter) IsUserEnabled(userID any, channelID any) *AutoTranslationStore_IsUserEnabled_Call {
	return &AutoTranslationStore_IsUserEnabled_Call{Call: _e.mock.On("IsUserEnabled", userID, channelID)}
}

func (_c *AutoTranslationStore_IsUserEnabled_Call) Run(run func(userID string, channelID string)) *AutoTranslationStore_IsUserEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_IsUserEnabled_Call) Return(b bool, err error) *AutoTranslationStore_IsUserEnabled_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *AutoTranslationStore_IsUserEnabled_Call) RunAndReturn(run func(userID string, channelID string) (bool, error)) *AutoTranslationStore_IsUserEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type AutoTranslationStore
func (_mock *AutoTranslationStore) Save(translation *model.Translation) error {
	ret := _mock.Called(translation)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Translation) error); ok {
		r0 = returnFunc(translation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AutoTranslationStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type AutoTranslationStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - translation *model.Translation
func (_e *AutoTranslationStore_Expecter) Save(translation any) *AutoTranslationStore_Save_Call {
	return &AutoTranslationStore_Save_Call{Call: _e.mock.On("Save", translation)}
}

func (_c *AutoTranslationStore_Save_Call) Run(run func(translation *model.Translation)) *AutoTranslationStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Translation
		if args[0] != nil {
			arg0 = args[0].(*model.Translation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AutoTranslationStore_Save_Call) Return(err error) *AutoTranslationStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AutoTranslationStore_Save_Call) RunAndReturn(run func(translation *model.Translation) error) *AutoTranslationStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
