// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	mock "github.com/stretchr/testify/mock"
)

// BannerStore is an autogenerated mock type for the BannerStore type
type BannerStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *BannerStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *BannerStore) Get(id string) (*lms_models.Banner, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.Banner, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.Banner); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with no fields
func (_m *BannerStore) GetAll() ([]*lms_models.Banner, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*lms_models.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*lms_models.Banner, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*lms_models.Banner); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: banner
func (_m *BannerStore) Save(banner *lms_models.Banner) (*lms_models.Banner, error) {
	ret := _m.Called(banner)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Banner) (*lms_models.Banner, error)); ok {
		return rf(banner)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Banner) *lms_models.Banner); ok {
		r0 = rf(banner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Banner) error); ok {
		r1 = rf(banner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: banner
func (_m *BannerStore) Update(banner *lms_models.Banner) (*lms_models.Banner, error) {
	ret := _m.Called(banner)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *lms_models.Banner
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Banner) (*lms_models.Banner, error)); ok {
		return rf(banner)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Banner) *lms_models.Banner); ok {
		r0 = rf(banner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Banner)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Banner) error); ok {
		r1 = rf(banner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBannerStore creates a new instance of BannerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBannerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BannerStore {
	mock := &BannerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
