// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	modelhelper "github.com/iamleson98/sitename/server/public/model_helper"
	mock "github.com/stretchr/testify/mock"
)

// BlogPostStore is an autogenerated mock type for the BlogPostStore type
type BlogPostStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *BlogPostStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *BlogPostStore) Get(id string) (*lms_models.BlogPost, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.BlogPost, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.BlogPost); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: opts
func (_m *BlogPostStore) GetAll(opts modelhelper.BlogPostFilterOpts) ([]*lms_models.BlogPost, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*lms_models.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(modelhelper.BlogPostFilterOpts) ([]*lms_models.BlogPost, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(modelhelper.BlogPostFilterOpts) []*lms_models.BlogPost); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(modelhelper.BlogPostFilterOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPublished provides a mock function with no fields
func (_m *BlogPostStore) GetPublished() ([]*lms_models.BlogPost, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublished")
	}

	var r0 []*lms_models.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*lms_models.BlogPost, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*lms_models.BlogPost); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: post
func (_m *BlogPostStore) Save(post *lms_models.BlogPost) (*lms_models.BlogPost, error) {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.BlogPost) (*lms_models.BlogPost, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.BlogPost) *lms_models.BlogPost); ok {
		r0 = rf(post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.BlogPost) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: post
func (_m *BlogPostStore) Update(post *lms_models.BlogPost) (*lms_models.BlogPost, error) {
	ret := _m.Called(post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *lms_models.BlogPost
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.BlogPost) (*lms_models.BlogPost, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.BlogPost) *lms_models.BlogPost); ok {
		r0 = rf(post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.BlogPost)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.BlogPost) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: opts
func (_m *BlogPostStore) Count(opts modelhelper.BlogPostFilterOpts) (int64, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(modelhelper.BlogPostFilterOpts) (int64, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(modelhelper.BlogPostFilterOpts) int64); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(modelhelper.BlogPostFilterOpts) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBlogPostStore creates a new instance of BlogPostStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlogPostStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlogPostStore {
	mock := &BlogPostStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
