// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCallSessionStore creates a new instance of CallSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCallSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CallSessionStore {
	mock := &CallSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CallSessionStore is an autogenerated mock type for the CallSessionStore type
type CallSessionStore struct {
	mock.Mock
}

type CallSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CallSessionStore) EXPECT() *CallSessionStore_Expecter {
	return &CallSessionStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) Delete(sessionID string) error {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CallSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CallSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - sessionID string
func (_e *CallSessionStore_Expecter) Delete(sessionID any) *CallSessionStore_Delete_Call {
	return &CallSessionStore_Delete_Call{Call: _e.mock.On("Delete", sessionID)}
}

func (_c *CallSessionStore_Delete_Call) Run(run func(sessionID string)) *CallSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CallSessionStore_Delete_Call) Return(err error) *CallSessionStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CallSessionStore_Delete_Call) RunAndReturn(run func(sessionID string) error) *CallSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) Get(sessionID string) (*model.CallSession, error) {
	ret := _mock.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.CallSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.CallSession, error)); ok {
		return returnFunc(sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.CallSession); ok {
		r0 = returnFunc(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CallSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CallSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CallSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - sessionID string
func (_e *CallSessionStore_Expecter) Get(sessionID any) *CallSessionStore_Get_Call {
	return &CallSessionStore_Get_Call{Call: _e.mock.On("Get", sessionID)}
}

func (_c *CallSessionStore_Get_Call) Run(run func(sessionID string)) *CallSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CallSessionStore_Get_Call) Return(callSession *model.CallSession, err error) *CallSessionStore_Get_Call {
	_c.Call.Return(callSession, err)
	return _c
}

func (_c *CallSessionStore_Get_Call) RunAndReturn(run func(sessionID string) (*model.CallSession, error)) *CallSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCall provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) GetByCall(callID string) ([]*model.CallSession, error) {
	ret := _mock.Called(callID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCall")
	}

	var r0 []*model.CallSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*model.CallSession, error)); ok {
		return returnFunc(callID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*model.CallSession); ok {
		r0 = returnFunc(callID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CallSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(callID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CallSessionStore_GetByCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCall'
type CallSessionStore_GetByCall_Call struct {
	*mock.Call
}

// GetByCall is a helper method to define mock.On call
//   - callID string
func (_e *CallSessionStore_Expecter) GetByCall(callID any) *CallSessionStore_GetByCall_Call {
	return &CallSessionStore_GetByCall_Call{Call: _e.mock.On("GetByCall", callID)}
}

func (_c *CallSessionStore_GetByCall_Call) Run(run func(callID string)) *CallSessionStore_GetByCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CallSessionStore_GetByCall_Call) Return(callSessions []*model.CallSession, err error) *CallSessionStore_GetByCall_Call {
	_c.Call.Return(callSessions, err)
	return _c
}

func (_c *CallSessionStore_GetByCall_Call) RunAndReturn(run func(callID string) ([]*model.CallSession, error)) *CallSessionStore_GetByCall_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCallAndUser provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) GetByCallAndUser(callID string, userID string) (*model.CallSession, error) {
	ret := _mock.Called(callID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCallAndUser")
	}

	var r0 *model.CallSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.CallSession, error)); ok {
		return returnFunc(callID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.CallSession); ok {
		r0 = returnFunc(callID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CallSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(callID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CallSessionStore_GetByCallAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCallAndUser'
type CallSessionStore_GetByCallAndUser_Call struct {
	*mock.Call
}

// GetByCallAndUser is a helper method to define mock.On call
//   - callID string
//   - userID string
func (_e *CallSessionStore_Expecter) GetByCallAndUser(callID any, userID any) *CallSessionStore_GetByCallAndUser_Call {
	return &CallSessionStore_GetByCallAndUser_Call{Call: _e.mock.On("GetByCallAndUser", callID, userID)}
}

func (_c *CallSessionStore_GetByCallAndUser_Call) Run(run func(callID string, userID string)) *CallSessionStore_GetByCallAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CallSessionStore_GetByCallAndUser_Call) Return(callSession *model.CallSession, err error) *CallSessionStore_GetByCallAndUser_Call {
	_c.Call.Return(callSession, err)
	return _c
}

func (_c *CallSessionStore_GetByCallAndUser_Call) RunAndReturn(run func(callID string, userID string) (*model.CallSession, error)) *CallSessionStore_GetByCallAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) Save(session *model.CallSession) (*model.CallSession, error) {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.CallSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.CallSession) (*model.CallSession, error)); ok {
		return returnFunc(session)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.CallSession) *model.CallSession); ok {
		r0 = returnFunc(session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CallSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.CallSession) error); ok {
		r1 = returnFunc(session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CallSessionStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CallSessionStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - session *model.CallSession
func (_e *CallSessionStore_Expecter) Save(session any) *CallSessionStore_Save_Call {
	return &CallSessionStore_Save_Call{Call: _e.mock.On("Save", session)}
}

func (_c *CallSessionStore_Save_Call) Run(run func(session *model.CallSession)) *CallSessionStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.CallSession
		if args[0] != nil {
			arg0 = args[0].(*model.CallSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CallSessionStore_Save_Call) Return(callSession *model.CallSession, err error) *CallSessionStore_Save_Call {
	_c.Call.Return(callSession, err)
	return _c
}

func (_c *CallSessionStore_Save_Call) RunAndReturn(run func(session *model.CallSession) (*model.CallSession, error)) *CallSessionStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CallSessionStore
func (_mock *CallSessionStore) Update(session *model.CallSession) (*model.CallSession, error) {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.CallSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.CallSession) (*model.CallSession, error)); ok {
		return returnFunc(session)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.CallSession) *model.CallSession); ok {
		r0 = returnFunc(session)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CallSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.CallSession) error); ok {
		r1 = returnFunc(session)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CallSessionStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CallSessionStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - session *model.CallSession
func (_e *CallSessionStore_Expecter) Update(session any) *CallSessionStore_Update_Call {
	return &CallSessionStore_Update_Call{Call: _e.mock.On("Update", session)}
}

func (_c *CallSessionStore_Update_Call) Run(run func(session *model.CallSession)) *CallSessionStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.CallSession
		if args[0] != nil {
			arg0 = args[0].(*model.CallSession)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CallSessionStore_Update_Call) Return(callSession *model.CallSession, err error) *CallSessionStore_Update_Call {
	_c.Call.Return(callSession, err)
	return _c
}

func (_c *CallSessionStore_Update_Call) RunAndReturn(run func(session *model.CallSession) (*model.CallSession, error)) *CallSessionStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
