// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/lms_models"
	"github.com/iamleson98/sitename/server/public/model_helper"
	mock "github.com/stretchr/testify/mock"
)

// NewClassMediaStore creates a new instance of ClassMediaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassMediaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassMediaStore {
	mock := &ClassMediaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClassMediaStore is an autogenerated mock type for the ClassMediaStore type
type ClassMediaStore struct {
	mock.Mock
}

type ClassMediaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ClassMediaStore) EXPECT() *ClassMediaStore_Expecter {
	return &ClassMediaStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type ClassMediaStore
func (_mock *ClassMediaStore) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClassMediaStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClassMediaStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *ClassMediaStore_Expecter) Delete(id any) *ClassMediaStore_Delete_Call {
	return &ClassMediaStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *ClassMediaStore_Delete_Call) Run(run func(id string)) *ClassMediaStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClassMediaStore_Delete_Call) Return(err error) *ClassMediaStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClassMediaStore_Delete_Call) RunAndReturn(run func(id string) error) *ClassMediaStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ClassMediaStore
func (_mock *ClassMediaStore) Get(id string) (*lms_models.ClassMedium, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.ClassMedium
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*lms_models.ClassMedium, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *lms_models.ClassMedium); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.ClassMedium)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClassMediaStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ClassMediaStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *ClassMediaStore_Expecter) Get(id any) *ClassMediaStore_Get_Call {
	return &ClassMediaStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *ClassMediaStore_Get_Call) Run(run func(id string)) *ClassMediaStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClassMediaStore_Get_Call) Return(classMedium *lms_models.ClassMedium, err error) *ClassMediaStore_Get_Call {
	_c.Call.Return(classMedium, err)
	return _c
}

func (_c *ClassMediaStore_Get_Call) RunAndReturn(run func(id string) (*lms_models.ClassMedium, error)) *ClassMediaStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type ClassMediaStore
func (_mock *ClassMediaStore) Save(cm *lms_models.ClassMedium) (*lms_models.ClassMedium, error) {
	ret := _mock.Called(cm)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.ClassMedium
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lms_models.ClassMedium) (*lms_models.ClassMedium, error)); ok {
		return returnFunc(cm)
	}
	if returnFunc, ok := ret.Get(0).(func(*lms_models.ClassMedium) *lms_models.ClassMedium); ok {
		r0 = returnFunc(cm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.ClassMedium)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lms_models.ClassMedium) error); ok {
		r1 = returnFunc(cm)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClassMediaStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type ClassMediaStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - cm *lms_models.ClassMedium
func (_e *ClassMediaStore_Expecter) Save(cm any) *ClassMediaStore_Save_Call {
	return &ClassMediaStore_Save_Call{Call: _e.mock.On("Save", cm)}
}

func (_c *ClassMediaStore_Save_Call) Run(run func(cm *lms_models.ClassMedium)) *ClassMediaStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lms_models.ClassMedium
		if args[0] != nil {
			arg0 = args[0].(*lms_models.ClassMedium)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClassMediaStore_Save_Call) Return(classMedium *lms_models.ClassMedium, err error) *ClassMediaStore_Save_Call {
	_c.Call.Return(classMedium, err)
	return _c
}

func (_c *ClassMediaStore_Save_Call) RunAndReturn(run func(cm *lms_models.ClassMedium) (*lms_models.ClassMedium, error)) *ClassMediaStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type ClassMediaStore
func (_mock *ClassMediaStore) Search(opts modelhelper.ClassMediaFilterOpts) ([]*lms_models.ClassMedium, int64, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*lms_models.ClassMedium
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(modelhelper.ClassMediaFilterOpts) ([]*lms_models.ClassMedium, int64, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(modelhelper.ClassMediaFilterOpts) []*lms_models.ClassMedium); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.ClassMedium)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(modelhelper.ClassMediaFilterOpts) int64); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(modelhelper.ClassMediaFilterOpts) error); ok {
		r2 = returnFunc(opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ClassMediaStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type ClassMediaStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - opts modelhelper.ClassMediaFilterOpts
func (_e *ClassMediaStore_Expecter) Search(opts any) *ClassMediaStore_Search_Call {
	return &ClassMediaStore_Search_Call{Call: _e.mock.On("Search", opts)}
}

func (_c *ClassMediaStore_Search_Call) Run(run func(opts modelhelper.ClassMediaFilterOpts)) *ClassMediaStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 modelhelper.ClassMediaFilterOpts
		if args[0] != nil {
			arg0 = args[0].(modelhelper.ClassMediaFilterOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClassMediaStore_Search_Call) Return(classMediums []*lms_models.ClassMedium, n int64, err error) *ClassMediaStore_Search_Call {
	_c.Call.Return(classMediums, n, err)
	return _c
}

func (_c *ClassMediaStore_Search_Call) RunAndReturn(run func(opts modelhelper.ClassMediaFilterOpts) ([]*lms_models.ClassMedium, int64, error)) *ClassMediaStore_Search_Call {
	_c.Call.Return(run)
	return _c
}
