// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// DashboardStore is an autogenerated mock type for the DashboardStore type
type DashboardStore struct {
	mock.Mock
}

// CountStudents provides a mock function with given fields:
func (_m *DashboardStore) CountStudents() (int64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountStudents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChildrenByParentID provides a mock function with given fields: parentID
func (_m *DashboardStore) GetChildrenByParentID(parentID string) ([]*model.User, error) {
	ret := _m.Called(parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildrenByParentID")
	}

	var r0 []*model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.User, error)); ok {
		return rf(parentID)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.User); ok {
		r0 = rf(parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDashboardStore creates a new instance of DashboardStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardStore {
	mock := &DashboardStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
