// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewDesktopTokensStore creates a new instance of DesktopTokensStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDesktopTokensStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DesktopTokensStore {
	mock := &DesktopTokensStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DesktopTokensStore is an autogenerated mock type for the DesktopTokensStore type
type DesktopTokensStore struct {
	mock.Mock
}

type DesktopTokensStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DesktopTokensStore) EXPECT() *DesktopTokensStore_Expecter {
	return &DesktopTokensStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type DesktopTokensStore
func (_mock *DesktopTokensStore) Delete(token string) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DesktopTokensStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DesktopTokensStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *DesktopTokensStore_Expecter) Delete(token any) *DesktopTokensStore_Delete_Call {
	return &DesktopTokensStore_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *DesktopTokensStore_Delete_Call) Run(run func(token string)) *DesktopTokensStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DesktopTokensStore_Delete_Call) Return(err error) *DesktopTokensStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DesktopTokensStore_Delete_Call) RunAndReturn(run func(token string) error) *DesktopTokensStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserId provides a mock function for the type DesktopTokensStore
func (_mock *DesktopTokensStore) DeleteByUserId(userID string) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DesktopTokensStore_DeleteByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserId'
type DesktopTokensStore_DeleteByUserId_Call struct {
	*mock.Call
}

// DeleteByUserId is a helper method to define mock.On call
//   - userID string
func (_e *DesktopTokensStore_Expecter) DeleteByUserId(userID any) *DesktopTokensStore_DeleteByUserId_Call {
	return &DesktopTokensStore_DeleteByUserId_Call{Call: _e.mock.On("DeleteByUserId", userID)}
}

func (_c *DesktopTokensStore_DeleteByUserId_Call) Run(run func(userID string)) *DesktopTokensStore_DeleteByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DesktopTokensStore_DeleteByUserId_Call) Return(err error) *DesktopTokensStore_DeleteByUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DesktopTokensStore_DeleteByUserId_Call) RunAndReturn(run func(userID string) error) *DesktopTokensStore_DeleteByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThan provides a mock function for the type DesktopTokensStore
func (_mock *DesktopTokensStore) DeleteOlderThan(minCreatedAt int64) error {
	ret := _mock.Called(minCreatedAt)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64) error); ok {
		r0 = returnFunc(minCreatedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DesktopTokensStore_DeleteOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThan'
type DesktopTokensStore_DeleteOlderThan_Call struct {
	*mock.Call
}

// DeleteOlderThan is a helper method to define mock.On call
//   - minCreatedAt int64
func (_e *DesktopTokensStore_Expecter) DeleteOlderThan(minCreatedAt any) *DesktopTokensStore_DeleteOlderThan_Call {
	return &DesktopTokensStore_DeleteOlderThan_Call{Call: _e.mock.On("DeleteOlderThan", minCreatedAt)}
}

func (_c *DesktopTokensStore_DeleteOlderThan_Call) Run(run func(minCreatedAt int64)) *DesktopTokensStore_DeleteOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DesktopTokensStore_DeleteOlderThan_Call) Return(err error) *DesktopTokensStore_DeleteOlderThan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DesktopTokensStore_DeleteOlderThan_Call) RunAndReturn(run func(minCreatedAt int64) error) *DesktopTokensStore_DeleteOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserId provides a mock function for the type DesktopTokensStore
func (_mock *DesktopTokensStore) GetUserId(token string, minCreatedAt int64) (*string, error) {
	ret := _mock.Called(token, minCreatedAt)

	if len(ret) == 0 {
		panic("no return value specified for GetUserId")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int64) (*string, error)); ok {
		return returnFunc(token, minCreatedAt)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int64) *string); ok {
		r0 = returnFunc(token, minCreatedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = returnFunc(token, minCreatedAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DesktopTokensStore_GetUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserId'
type DesktopTokensStore_GetUserId_Call struct {
	*mock.Call
}

// GetUserId is a helper method to define mock.On call
//   - token string
//   - minCreatedAt int64
func (_e *DesktopTokensStore_Expecter) GetUserId(token any, minCreatedAt any) *DesktopTokensStore_GetUserId_Call {
	return &DesktopTokensStore_GetUserId_Call{Call: _e.mock.On("GetUserId", token, minCreatedAt)}
}

func (_c *DesktopTokensStore_GetUserId_Call) Run(run func(token string, minCreatedAt int64)) *DesktopTokensStore_GetUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DesktopTokensStore_GetUserId_Call) Return(s *string, err error) *DesktopTokensStore_GetUserId_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *DesktopTokensStore_GetUserId_Call) RunAndReturn(run func(token string, minCreatedAt int64) (*string, error)) *DesktopTokensStore_GetUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type DesktopTokensStore
func (_mock *DesktopTokensStore) Insert(token string, createAt int64, userID string) error {
	ret := _mock.Called(token, createAt, userID)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, string) error); ok {
		r0 = returnFunc(token, createAt, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DesktopTokensStore_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type DesktopTokensStore_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - token string
//   - createAt int64
//   - userID string
func (_e *DesktopTokensStore_Expecter) Insert(token any, createAt any, userID any) *DesktopTokensStore_Insert_Call {
	return &DesktopTokensStore_Insert_Call{Call: _e.mock.On("Insert", token, createAt, userID)}
}

func (_c *DesktopTokensStore_Insert_Call) Run(run func(token string, createAt int64, userID string)) *DesktopTokensStore_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DesktopTokensStore_Insert_Call) Return(err error) *DesktopTokensStore_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DesktopTokensStore_Insert_Call) RunAndReturn(run func(token string, createAt int64, userID string) error) *DesktopTokensStore_Insert_Call {
	_c.Call.Return(run)
	return _c
}
