// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewDraftStore creates a new instance of DraftStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDraftStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DraftStore {
	mock := &DraftStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DraftStore is an autogenerated mock type for the DraftStore type
type DraftStore struct {
	mock.Mock
}

type DraftStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DraftStore) EXPECT() *DraftStore_Expecter {
	return &DraftStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type DraftStore
func (_mock *DraftStore) Delete(userID string, channelID string, rootID string) error {
	ret := _mock.Called(userID, channelID, rootID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(userID, channelID, rootID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DraftStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DraftStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID string
//   - channelID string
//   - rootID string
func (_e *DraftStore_Expecter) Delete(userID any, channelID any, rootID any) *DraftStore_Delete_Call {
	return &DraftStore_Delete_Call{Call: _e.mock.On("Delete", userID, channelID, rootID)}
}

func (_c *DraftStore_Delete_Call) Run(run func(userID string, channelID string, rootID string)) *DraftStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DraftStore_Delete_Call) Return(err error) *DraftStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DraftStore_Delete_Call) RunAndReturn(run func(userID string, channelID string, rootID string) error) *DraftStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDraftsAssociatedWithPost provides a mock function for the type DraftStore
func (_mock *DraftStore) DeleteDraftsAssociatedWithPost(channelID string, rootID string) error {
	ret := _mock.Called(channelID, rootID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDraftsAssociatedWithPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(channelID, rootID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DraftStore_DeleteDraftsAssociatedWithPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDraftsAssociatedWithPost'
type DraftStore_DeleteDraftsAssociatedWithPost_Call struct {
	*mock.Call
}

// DeleteDraftsAssociatedWithPost is a helper method to define mock.On call
//   - channelID string
//   - rootID string
func (_e *DraftStore_Expecter) DeleteDraftsAssociatedWithPost(channelID any, rootID any) *DraftStore_DeleteDraftsAssociatedWithPost_Call {
	return &DraftStore_DeleteDraftsAssociatedWithPost_Call{Call: _e.mock.On("DeleteDraftsAssociatedWithPost", channelID, rootID)}
}

func (_c *DraftStore_DeleteDraftsAssociatedWithPost_Call) Run(run func(channelID string, rootID string)) *DraftStore_DeleteDraftsAssociatedWithPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DraftStore_DeleteDraftsAssociatedWithPost_Call) Return(err error) *DraftStore_DeleteDraftsAssociatedWithPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DraftStore_DeleteDraftsAssociatedWithPost_Call) RunAndReturn(run func(channelID string, rootID string) error) *DraftStore_DeleteDraftsAssociatedWithPost_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEmptyDraftsByCreateAtAndUserId provides a mock function for the type DraftStore
func (_mock *DraftStore) DeleteEmptyDraftsByCreateAtAndUserId(createAt int64, userID string) error {
	ret := _mock.Called(createAt, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmptyDraftsByCreateAtAndUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = returnFunc(createAt, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmptyDraftsByCreateAtAndUserId'
type DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call struct {
	*mock.Call
}

// DeleteEmptyDraftsByCreateAtAndUserId is a helper method to define mock.On call
//   - createAt int64
//   - userID string
func (_e *DraftStore_Expecter) DeleteEmptyDraftsByCreateAtAndUserId(createAt any, userID any) *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call {
	return &DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call{Call: _e.mock.On("DeleteEmptyDraftsByCreateAtAndUserId", createAt, userID)}
}

func (_c *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call) Run(run func(createAt int64, userID string)) *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call) Return(err error) *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call) RunAndReturn(run func(createAt int64, userID string) error) *DraftStore_DeleteEmptyDraftsByCreateAtAndUserId_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrphanDraftsByCreateAtAndUserId provides a mock function for the type DraftStore
func (_mock *DraftStore) DeleteOrphanDraftsByCreateAtAndUserId(createAt int64, userID string) error {
	ret := _mock.Called(createAt, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrphanDraftsByCreateAtAndUserId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = returnFunc(createAt, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrphanDraftsByCreateAtAndUserId'
type DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call struct {
	*mock.Call
}

// DeleteOrphanDraftsByCreateAtAndUserId is a helper method to define mock.On call
//   - createAt int64
//   - userID string
func (_e *DraftStore_Expecter) DeleteOrphanDraftsByCreateAtAndUserId(createAt any, userID any) *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call {
	return &DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call{Call: _e.mock.On("DeleteOrphanDraftsByCreateAtAndUserId", createAt, userID)}
}

func (_c *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call) Run(run func(createAt int64, userID string)) *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call) Return(err error) *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call) RunAndReturn(run func(createAt int64, userID string) error) *DraftStore_DeleteOrphanDraftsByCreateAtAndUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type DraftStore
func (_mock *DraftStore) Get(userID string, channelID string, rootID string, includeDeleted bool) (*model.Draft, error) {
	ret := _mock.Called(userID, channelID, rootID, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Draft
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool) (*model.Draft, error)); ok {
		return returnFunc(userID, channelID, rootID, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool) *model.Draft); ok {
		r0 = returnFunc(userID, channelID, rootID, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Draft)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, bool) error); ok {
		r1 = returnFunc(userID, channelID, rootID, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DraftStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type DraftStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
//   - channelID string
//   - rootID string
//   - includeDeleted bool
func (_e *DraftStore_Expecter) Get(userID any, channelID any, rootID any, includeDeleted any) *DraftStore_Get_Call {
	return &DraftStore_Get_Call{Call: _e.mock.On("Get", userID, channelID, rootID, includeDeleted)}
}

func (_c *DraftStore_Get_Call) Run(run func(userID string, channelID string, rootID string, includeDeleted bool)) *DraftStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DraftStore_Get_Call) Return(draft *model.Draft, err error) *DraftStore_Get_Call {
	_c.Call.Return(draft, err)
	return _c
}

func (_c *DraftStore_Get_Call) RunAndReturn(run func(userID string, channelID string, rootID string, includeDeleted bool) (*model.Draft, error)) *DraftStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetDraftsForUser provides a mock function for the type DraftStore
func (_mock *DraftStore) GetDraftsForUser(userID string, teamID string) ([]*model.Draft, error) {
	ret := _mock.Called(userID, teamID)

	if len(ret) == 0 {
		panic("no return value specified for GetDraftsForUser")
	}

	var r0 []*model.Draft
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]*model.Draft, error)); ok {
		return returnFunc(userID, teamID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []*model.Draft); ok {
		r0 = returnFunc(userID, teamID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Draft)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, teamID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DraftStore_GetDraftsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDraftsForUser'
type DraftStore_GetDraftsForUser_Call struct {
	*mock.Call
}

// GetDraftsForUser is a helper method to define mock.On call
//   - userID string
//   - teamID string
func (_e *DraftStore_Expecter) GetDraftsForUser(userID any, teamID any) *DraftStore_GetDraftsForUser_Call {
	return &DraftStore_GetDraftsForUser_Call{Call: _e.mock.On("GetDraftsForUser", userID, teamID)}
}

func (_c *DraftStore_GetDraftsForUser_Call) Run(run func(userID string, teamID string)) *DraftStore_GetDraftsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DraftStore_GetDraftsForUser_Call) Return(drafts []*model.Draft, err error) *DraftStore_GetDraftsForUser_Call {
	_c.Call.Return(drafts, err)
	return _c
}

func (_c *DraftStore_GetDraftsForUser_Call) RunAndReturn(run func(userID string, teamID string) ([]*model.Draft, error)) *DraftStore_GetDraftsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration provides a mock function for the type DraftStore
func (_mock *DraftStore) GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration(createAt int64, userID string) (int64, string, error) {
	ret := _mock.Called(createAt, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (int64, string, error)); ok {
		return returnFunc(createAt, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) int64); ok {
		r0 = returnFunc(createAt, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) string); ok {
		r1 = returnFunc(createAt, userID)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(int64, string) error); ok {
		r2 = returnFunc(createAt, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration'
type DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call struct {
	*mock.Call
}

// GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration is a helper method to define mock.On call
//   - createAt int64
//   - userID string
func (_e *DraftStore_Expecter) GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration(createAt any, userID any) *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call {
	return &DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call{Call: _e.mock.On("GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration", createAt, userID)}
}

func (_c *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call) Run(run func(createAt int64, userID string)) *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call) Return(n int64, s string, err error) *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call) RunAndReturn(run func(createAt int64, userID string) (int64, string, error)) *DraftStore_GetLastCreateAtAndUserIdValuesForEmptyDraftsMigration_Call {
	_c.Call.Return(run)
	return _c
}

// PermanentDeleteByUser provides a mock function for the type DraftStore
func (_mock *DraftStore) PermanentDeleteByUser(userId string) error {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for PermanentDeleteByUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DraftStore_PermanentDeleteByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PermanentDeleteByUser'
type DraftStore_PermanentDeleteByUser_Call struct {
	*mock.Call
}

// PermanentDeleteByUser is a helper method to define mock.On call
//   - userId string
func (_e *DraftStore_Expecter) PermanentDeleteByUser(userId any) *DraftStore_PermanentDeleteByUser_Call {
	return &DraftStore_PermanentDeleteByUser_Call{Call: _e.mock.On("PermanentDeleteByUser", userId)}
}

func (_c *DraftStore_PermanentDeleteByUser_Call) Run(run func(userId string)) *DraftStore_PermanentDeleteByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DraftStore_PermanentDeleteByUser_Call) Return(err error) *DraftStore_PermanentDeleteByUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DraftStore_PermanentDeleteByUser_Call) RunAndReturn(run func(userId string) error) *DraftStore_PermanentDeleteByUser_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type DraftStore
func (_mock *DraftStore) Upsert(d *model.Draft) (*model.Draft, error) {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *model.Draft
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Draft) (*model.Draft, error)); ok {
		return returnFunc(d)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Draft) *model.Draft); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Draft)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Draft) error); ok {
		r1 = returnFunc(d)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DraftStore_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type DraftStore_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - d *model.Draft
func (_e *DraftStore_Expecter) Upsert(d any) *DraftStore_Upsert_Call {
	return &DraftStore_Upsert_Call{Call: _e.mock.On("Upsert", d)}
}

func (_c *DraftStore_Upsert_Call) Run(run func(d *model.Draft)) *DraftStore_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Draft
		if args[0] != nil {
			arg0 = args[0].(*model.Draft)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DraftStore_Upsert_Call) Return(draft *model.Draft, err error) *DraftStore_Upsert_Call {
	_c.Call.Return(draft, err)
	return _c
}

func (_c *DraftStore_Upsert_Call) RunAndReturn(run func(d *model.Draft) (*model.Draft, error)) *DraftStore_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
