// Code generated by mockery v2.53.6. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	mock "github.com/stretchr/testify/mock"
)

// FeeRefundStore is an autogenerated mock type for the FeeRefundStore type
type FeeRefundStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *FeeRefundStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *FeeRefundStore) Get(id string) (*lms_models.FeeRefund, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.FeeRefund
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.FeeRefund, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.FeeRefund); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.FeeRefund)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTuition provides a mock function with given fields: tuitionID
func (_m *FeeRefundStore) GetByTuition(tuitionID string) ([]*lms_models.FeeRefund, error) {
	ret := _m.Called(tuitionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTuition")
	}

	var r0 []*lms_models.FeeRefund
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*lms_models.FeeRefund, error)); ok {
		return rf(tuitionID)
	}
	if rf, ok := ret.Get(0).(func(string) []*lms_models.FeeRefund); ok {
		r0 = rf(tuitionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.FeeRefund)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tuitionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: refund
func (_m *FeeRefundStore) Save(refund *lms_models.FeeRefund) (*lms_models.FeeRefund, error) {
	ret := _m.Called(refund)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.FeeRefund
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.FeeRefund) (*lms_models.FeeRefund, error)); ok {
		return rf(refund)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.FeeRefund) *lms_models.FeeRefund); ok {
		r0 = rf(refund)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.FeeRefund)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.FeeRefund) error); ok {
		r1 = rf(refund)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFeeRefundStore creates a new instance of FeeRefundStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeeRefundStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeeRefundStore {
	mock := &FeeRefundStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
