// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	"github.com/iamleson98/sitename/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// NewJobStore creates a new instance of JobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobStore {
	mock := &JobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobStore is an autogenerated mock type for the JobStore type
type JobStore struct {
	mock.Mock
}

type JobStore_Expecter struct {
	mock *mock.Mock
}

func (_m *JobStore) EXPECT() *JobStore_Expecter {
	return &JobStore_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type JobStore
func (_mock *JobStore) Cleanup(expiryTime int64, batchSize int) error {
	ret := _mock.Called(expiryTime, batchSize)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) error); ok {
		r0 = returnFunc(expiryTime, batchSize)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobStore_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type JobStore_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - expiryTime int64
//   - batchSize int
func (_e *JobStore_Expecter) Cleanup(expiryTime any, batchSize any) *JobStore_Cleanup_Call {
	return &JobStore_Cleanup_Call{Call: _e.mock.On("Cleanup", expiryTime, batchSize)}
}

func (_c *JobStore_Cleanup_Call) Run(run func(expiryTime int64, batchSize int)) *JobStore_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_Cleanup_Call) Return(err error) *JobStore_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobStore_Cleanup_Call) RunAndReturn(run func(expiryTime int64, batchSize int) error) *JobStore_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type JobStore
func (_mock *JobStore) Delete(id string) (string, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type JobStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *JobStore_Expecter) Delete(id any) *JobStore_Delete_Call {
	return &JobStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *JobStore_Delete_Call) Run(run func(id string)) *JobStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobStore_Delete_Call) Return(s string, err error) *JobStore_Delete_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JobStore_Delete_Call) RunAndReturn(run func(id string) (string, error)) *JobStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type JobStore
func (_mock *JobStore) Get(rctx request.CTX, id string) (*model.Job, error) {
	ret := _mock.Called(rctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) (*model.Job, error)); ok {
		return returnFunc(rctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) *model.Job); ok {
		r0 = returnFunc(rctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = returnFunc(rctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type JobStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - rctx request.CTX
//   - id string
func (_e *JobStore_Expecter) Get(rctx any, id any) *JobStore_Get_Call {
	return &JobStore_Get_Call{Call: _e.mock.On("Get", rctx, id)}
}

func (_c *JobStore_Get_Call) Run(run func(rctx request.CTX, id string)) *JobStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_Get_Call) Return(job *model.Job, err error) *JobStore_Get_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobStore_Get_Call) RunAndReturn(run func(rctx request.CTX, id string) (*model.Job, error)) *JobStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByStatus provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByStatus(rctx request.CTX, status string) ([]*model.Job, error) {
	ret := _mock.Called(rctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByStatus")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) ([]*model.Job, error)); ok {
		return returnFunc(rctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) []*model.Job); ok {
		r0 = returnFunc(rctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = returnFunc(rctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByStatus'
type JobStore_GetAllByStatus_Call struct {
	*mock.Call
}

// GetAllByStatus is a helper method to define mock.On call
//   - rctx request.CTX
//   - status string
func (_e *JobStore_Expecter) GetAllByStatus(rctx any, status any) *JobStore_GetAllByStatus_Call {
	return &JobStore_GetAllByStatus_Call{Call: _e.mock.On("GetAllByStatus", rctx, status)}
}

func (_c *JobStore_GetAllByStatus_Call) Run(run func(rctx request.CTX, status string)) *JobStore_GetAllByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByStatus_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByStatus_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByStatus_Call) RunAndReturn(run func(rctx request.CTX, status string) ([]*model.Job, error)) *JobStore_GetAllByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByType provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByType(rctx request.CTX, jobType string) ([]*model.Job, error) {
	ret := _mock.Called(rctx, jobType)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByType")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobType)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string) []*model.Job); ok {
		r0 = returnFunc(rctx, jobType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = returnFunc(rctx, jobType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByType'
type JobStore_GetAllByType_Call struct {
	*mock.Call
}

// GetAllByType is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobType string
func (_e *JobStore_Expecter) GetAllByType(rctx any, jobType any) *JobStore_GetAllByType_Call {
	return &JobStore_GetAllByType_Call{Call: _e.mock.On("GetAllByType", rctx, jobType)}
}

func (_c *JobStore_GetAllByType_Call) Run(run func(rctx request.CTX, jobType string)) *JobStore_GetAllByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByType_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByType_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByType_Call) RunAndReturn(run func(rctx request.CTX, jobType string) ([]*model.Job, error)) *JobStore_GetAllByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByTypeAndStatus provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByTypeAndStatus(rctx request.CTX, jobType string, status string) ([]*model.Job, error) {
	ret := _mock.Called(rctx, jobType, status)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTypeAndStatus")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, string) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobType, status)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, string) []*model.Job); ok {
		r0 = returnFunc(rctx, jobType, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string, string) error); ok {
		r1 = returnFunc(rctx, jobType, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByTypeAndStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByTypeAndStatus'
type JobStore_GetAllByTypeAndStatus_Call struct {
	*mock.Call
}

// GetAllByTypeAndStatus is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobType string
//   - status string
func (_e *JobStore_Expecter) GetAllByTypeAndStatus(rctx any, jobType any, status any) *JobStore_GetAllByTypeAndStatus_Call {
	return &JobStore_GetAllByTypeAndStatus_Call{Call: _e.mock.On("GetAllByTypeAndStatus", rctx, jobType, status)}
}

func (_c *JobStore_GetAllByTypeAndStatus_Call) Run(run func(rctx request.CTX, jobType string, status string)) *JobStore_GetAllByTypeAndStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByTypeAndStatus_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByTypeAndStatus_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByTypeAndStatus_Call) RunAndReturn(run func(rctx request.CTX, jobType string, status string) ([]*model.Job, error)) *JobStore_GetAllByTypeAndStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByTypePage provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByTypePage(rctx request.CTX, jobType string, offset int, limit int) ([]*model.Job, error) {
	ret := _mock.Called(rctx, jobType, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTypePage")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, int, int) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobType, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, int, int) []*model.Job); ok {
		r0 = returnFunc(rctx, jobType, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string, int, int) error); ok {
		r1 = returnFunc(rctx, jobType, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByTypePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByTypePage'
type JobStore_GetAllByTypePage_Call struct {
	*mock.Call
}

// GetAllByTypePage is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobType string
//   - offset int
//   - limit int
func (_e *JobStore_Expecter) GetAllByTypePage(rctx any, jobType any, offset any, limit any) *JobStore_GetAllByTypePage_Call {
	return &JobStore_GetAllByTypePage_Call{Call: _e.mock.On("GetAllByTypePage", rctx, jobType, offset, limit)}
}

func (_c *JobStore_GetAllByTypePage_Call) Run(run func(rctx request.CTX, jobType string, offset int, limit int)) *JobStore_GetAllByTypePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByTypePage_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByTypePage_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByTypePage_Call) RunAndReturn(run func(rctx request.CTX, jobType string, offset int, limit int) ([]*model.Job, error)) *JobStore_GetAllByTypePage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByTypesAndStatusesPage provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByTypesAndStatusesPage(rctx request.CTX, jobType []string, status []string, offset int, limit int) ([]*model.Job, error) {
	ret := _mock.Called(rctx, jobType, status, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTypesAndStatusesPage")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, []string, []string, int, int) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobType, status, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, []string, []string, int, int) []*model.Job); ok {
		r0 = returnFunc(rctx, jobType, status, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, []string, []string, int, int) error); ok {
		r1 = returnFunc(rctx, jobType, status, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByTypesAndStatusesPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByTypesAndStatusesPage'
type JobStore_GetAllByTypesAndStatusesPage_Call struct {
	*mock.Call
}

// GetAllByTypesAndStatusesPage is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobType []string
//   - status []string
//   - offset int
//   - limit int
func (_e *JobStore_Expecter) GetAllByTypesAndStatusesPage(rctx any, jobType any, status any, offset any, limit any) *JobStore_GetAllByTypesAndStatusesPage_Call {
	return &JobStore_GetAllByTypesAndStatusesPage_Call{Call: _e.mock.On("GetAllByTypesAndStatusesPage", rctx, jobType, status, offset, limit)}
}

func (_c *JobStore_GetAllByTypesAndStatusesPage_Call) Run(run func(rctx request.CTX, jobType []string, status []string, offset int, limit int)) *JobStore_GetAllByTypesAndStatusesPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByTypesAndStatusesPage_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByTypesAndStatusesPage_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByTypesAndStatusesPage_Call) RunAndReturn(run func(rctx request.CTX, jobType []string, status []string, offset int, limit int) ([]*model.Job, error)) *JobStore_GetAllByTypesAndStatusesPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllByTypesPage provides a mock function for the type JobStore
func (_mock *JobStore) GetAllByTypesPage(rctx request.CTX, jobTypes []string, offset int, limit int) ([]*model.Job, error) {
	ret := _mock.Called(rctx, jobTypes, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTypesPage")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, []string, int, int) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobTypes, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, []string, int, int) []*model.Job); ok {
		r0 = returnFunc(rctx, jobTypes, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, []string, int, int) error); ok {
		r1 = returnFunc(rctx, jobTypes, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetAllByTypesPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllByTypesPage'
type JobStore_GetAllByTypesPage_Call struct {
	*mock.Call
}

// GetAllByTypesPage is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobTypes []string
//   - offset int
//   - limit int
func (_e *JobStore_Expecter) GetAllByTypesPage(rctx any, jobTypes any, offset any, limit any) *JobStore_GetAllByTypesPage_Call {
	return &JobStore_GetAllByTypesPage_Call{Call: _e.mock.On("GetAllByTypesPage", rctx, jobTypes, offset, limit)}
}

func (_c *JobStore_GetAllByTypesPage_Call) Run(run func(rctx request.CTX, jobTypes []string, offset int, limit int)) *JobStore_GetAllByTypesPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *JobStore_GetAllByTypesPage_Call) Return(jobs []*model.Job, err error) *JobStore_GetAllByTypesPage_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetAllByTypesPage_Call) RunAndReturn(run func(rctx request.CTX, jobTypes []string, offset int, limit int) ([]*model.Job, error)) *JobStore_GetAllByTypesPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTypeAndData provides a mock function for the type JobStore
func (_mock *JobStore) GetByTypeAndData(rctx request.CTX, jobType string, data map[string]string, useMaster bool, statuses ...string) ([]*model.Job, error) {
	// string
	_va := make([]any, len(statuses))
	for _i := range statuses {
		_va[_i] = statuses[_i]
	}
	var _ca []any
	_ca = append(_ca, rctx, jobType, data, useMaster)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetByTypeAndData")
	}

	var r0 []*model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, map[string]string, bool, ...string) ([]*model.Job, error)); ok {
		return returnFunc(rctx, jobType, data, useMaster, statuses...)
	}
	if returnFunc, ok := ret.Get(0).(func(request.CTX, string, map[string]string, bool, ...string) []*model.Job); ok {
		r0 = returnFunc(rctx, jobType, data, useMaster, statuses...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(request.CTX, string, map[string]string, bool, ...string) error); ok {
		r1 = returnFunc(rctx, jobType, data, useMaster, statuses...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetByTypeAndData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTypeAndData'
type JobStore_GetByTypeAndData_Call struct {
	*mock.Call
}

// GetByTypeAndData is a helper method to define mock.On call
//   - rctx request.CTX
//   - jobType string
//   - data map[string]string
//   - useMaster bool
//   - statuses ...string
func (_e *JobStore_Expecter) GetByTypeAndData(rctx any, jobType any, data any, useMaster any, statuses ...any) *JobStore_GetByTypeAndData_Call {
	return &JobStore_GetByTypeAndData_Call{Call: _e.mock.On("GetByTypeAndData",
		append([]any{rctx, jobType, data, useMaster}, statuses...)...)}
}

func (_c *JobStore_GetByTypeAndData_Call) Run(run func(rctx request.CTX, jobType string, data map[string]string, useMaster bool, statuses ...string)) *JobStore_GetByTypeAndData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request.CTX
		if args[0] != nil {
			arg0 = args[0].(request.CTX)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 []string
		variadicArgs := make([]string, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg4 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4...,
		)
	})
	return _c
}

func (_c *JobStore_GetByTypeAndData_Call) Return(jobs []*model.Job, err error) *JobStore_GetByTypeAndData_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobStore_GetByTypeAndData_Call) RunAndReturn(run func(rctx request.CTX, jobType string, data map[string]string, useMaster bool, statuses ...string) ([]*model.Job, error)) *JobStore_GetByTypeAndData_Call {
	_c.Call.Return(run)
	return _c
}

// GetCountByStatusAndType provides a mock function for the type JobStore
func (_mock *JobStore) GetCountByStatusAndType(status string, jobType string) (int64, error) {
	ret := _mock.Called(status, jobType)

	if len(ret) == 0 {
		panic("no return value specified for GetCountByStatusAndType")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return returnFunc(status, jobType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = returnFunc(status, jobType)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(status, jobType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetCountByStatusAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCountByStatusAndType'
type JobStore_GetCountByStatusAndType_Call struct {
	*mock.Call
}

// GetCountByStatusAndType is a helper method to define mock.On call
//   - status string
//   - jobType string
func (_e *JobStore_Expecter) GetCountByStatusAndType(status any, jobType any) *JobStore_GetCountByStatusAndType_Call {
	return &JobStore_GetCountByStatusAndType_Call{Call: _e.mock.On("GetCountByStatusAndType", status, jobType)}
}

func (_c *JobStore_GetCountByStatusAndType_Call) Run(run func(status string, jobType string)) *JobStore_GetCountByStatusAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_GetCountByStatusAndType_Call) Return(n int64, err error) *JobStore_GetCountByStatusAndType_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *JobStore_GetCountByStatusAndType_Call) RunAndReturn(run func(status string, jobType string) (int64, error)) *JobStore_GetCountByStatusAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewestJobByStatusAndType provides a mock function for the type JobStore
func (_mock *JobStore) GetNewestJobByStatusAndType(status string, jobType string) (*model.Job, error) {
	ret := _mock.Called(status, jobType)

	if len(ret) == 0 {
		panic("no return value specified for GetNewestJobByStatusAndType")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.Job, error)); ok {
		return returnFunc(status, jobType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.Job); ok {
		r0 = returnFunc(status, jobType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(status, jobType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetNewestJobByStatusAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewestJobByStatusAndType'
type JobStore_GetNewestJobByStatusAndType_Call struct {
	*mock.Call
}

// GetNewestJobByStatusAndType is a helper method to define mock.On call
//   - status string
//   - jobType string
func (_e *JobStore_Expecter) GetNewestJobByStatusAndType(status any, jobType any) *JobStore_GetNewestJobByStatusAndType_Call {
	return &JobStore_GetNewestJobByStatusAndType_Call{Call: _e.mock.On("GetNewestJobByStatusAndType", status, jobType)}
}

func (_c *JobStore_GetNewestJobByStatusAndType_Call) Run(run func(status string, jobType string)) *JobStore_GetNewestJobByStatusAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_GetNewestJobByStatusAndType_Call) Return(job *model.Job, err error) *JobStore_GetNewestJobByStatusAndType_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobStore_GetNewestJobByStatusAndType_Call) RunAndReturn(run func(status string, jobType string) (*model.Job, error)) *JobStore_GetNewestJobByStatusAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewestJobByStatusesAndType provides a mock function for the type JobStore
func (_mock *JobStore) GetNewestJobByStatusesAndType(statuses []string, jobType string) (*model.Job, error) {
	ret := _mock.Called(statuses, jobType)

	if len(ret) == 0 {
		panic("no return value specified for GetNewestJobByStatusesAndType")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, string) (*model.Job, error)); ok {
		return returnFunc(statuses, jobType)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, string) *model.Job); ok {
		r0 = returnFunc(statuses, jobType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = returnFunc(statuses, jobType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_GetNewestJobByStatusesAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewestJobByStatusesAndType'
type JobStore_GetNewestJobByStatusesAndType_Call struct {
	*mock.Call
}

// GetNewestJobByStatusesAndType is a helper method to define mock.On call
//   - statuses []string
//   - jobType string
func (_e *JobStore_Expecter) GetNewestJobByStatusesAndType(statuses any, jobType any) *JobStore_GetNewestJobByStatusesAndType_Call {
	return &JobStore_GetNewestJobByStatusesAndType_Call{Call: _e.mock.On("GetNewestJobByStatusesAndType", statuses, jobType)}
}

func (_c *JobStore_GetNewestJobByStatusesAndType_Call) Run(run func(statuses []string, jobType string)) *JobStore_GetNewestJobByStatusesAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_GetNewestJobByStatusesAndType_Call) Return(job *model.Job, err error) *JobStore_GetNewestJobByStatusesAndType_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobStore_GetNewestJobByStatusesAndType_Call) RunAndReturn(run func(statuses []string, jobType string) (*model.Job, error)) *JobStore_GetNewestJobByStatusesAndType_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type JobStore
func (_mock *JobStore) Save(job *model.Job) (*model.Job, error) {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Job) (*model.Job, error)); ok {
		return returnFunc(job)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Job) *model.Job); ok {
		r0 = returnFunc(job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Job) error); ok {
		r1 = returnFunc(job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type JobStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - job *model.Job
func (_e *JobStore_Expecter) Save(job any) *JobStore_Save_Call {
	return &JobStore_Save_Call{Call: _e.mock.On("Save", job)}
}

func (_c *JobStore_Save_Call) Run(run func(job *model.Job)) *JobStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Job
		if args[0] != nil {
			arg0 = args[0].(*model.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobStore_Save_Call) Return(job1 *model.Job, err error) *JobStore_Save_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *JobStore_Save_Call) RunAndReturn(run func(job *model.Job) (*model.Job, error)) *JobStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOnce provides a mock function for the type JobStore
func (_mock *JobStore) SaveOnce(job *model.Job) (*model.Job, error) {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for SaveOnce")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Job) (*model.Job, error)); ok {
		return returnFunc(job)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Job) *model.Job); ok {
		r0 = returnFunc(job)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Job) error); ok {
		r1 = returnFunc(job)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_SaveOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOnce'
type JobStore_SaveOnce_Call struct {
	*mock.Call
}

// SaveOnce is a helper method to define mock.On call
//   - job *model.Job
func (_e *JobStore_Expecter) SaveOnce(job any) *JobStore_SaveOnce_Call {
	return &JobStore_SaveOnce_Call{Call: _e.mock.On("SaveOnce", job)}
}

func (_c *JobStore_SaveOnce_Call) Run(run func(job *model.Job)) *JobStore_SaveOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Job
		if args[0] != nil {
			arg0 = args[0].(*model.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobStore_SaveOnce_Call) Return(job1 *model.Job, err error) *JobStore_SaveOnce_Call {
	_c.Call.Return(job1, err)
	return _c
}

func (_c *JobStore_SaveOnce_Call) RunAndReturn(run func(job *model.Job) (*model.Job, error)) *JobStore_SaveOnce_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOptimistically provides a mock function for the type JobStore
func (_mock *JobStore) UpdateOptimistically(job *model.Job, currentStatus string) (bool, error) {
	ret := _mock.Called(job, currentStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOptimistically")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Job, string) (bool, error)); ok {
		return returnFunc(job, currentStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Job, string) bool); ok {
		r0 = returnFunc(job, currentStatus)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Job, string) error); ok {
		r1 = returnFunc(job, currentStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_UpdateOptimistically_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOptimistically'
type JobStore_UpdateOptimistically_Call struct {
	*mock.Call
}

// UpdateOptimistically is a helper method to define mock.On call
//   - job *model.Job
//   - currentStatus string
func (_e *JobStore_Expecter) UpdateOptimistically(job any, currentStatus any) *JobStore_UpdateOptimistically_Call {
	return &JobStore_UpdateOptimistically_Call{Call: _e.mock.On("UpdateOptimistically", job, currentStatus)}
}

func (_c *JobStore_UpdateOptimistically_Call) Run(run func(job *model.Job, currentStatus string)) *JobStore_UpdateOptimistically_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Job
		if args[0] != nil {
			arg0 = args[0].(*model.Job)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_UpdateOptimistically_Call) Return(b bool, err error) *JobStore_UpdateOptimistically_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *JobStore_UpdateOptimistically_Call) RunAndReturn(run func(job *model.Job, currentStatus string) (bool, error)) *JobStore_UpdateOptimistically_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type JobStore
func (_mock *JobStore) UpdateStatus(id string, status string) (*model.Job, error) {
	ret := _mock.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.Job, error)); ok {
		return returnFunc(id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.Job); ok {
		r0 = returnFunc(id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type JobStore_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id string
//   - status string
func (_e *JobStore_Expecter) UpdateStatus(id any, status any) *JobStore_UpdateStatus_Call {
	return &JobStore_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status)}
}

func (_c *JobStore_UpdateStatus_Call) Run(run func(id string, status string)) *JobStore_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobStore_UpdateStatus_Call) Return(job *model.Job, err error) *JobStore_UpdateStatus_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobStore_UpdateStatus_Call) RunAndReturn(run func(id string, status string) (*model.Job, error)) *JobStore_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusOptimistically provides a mock function for the type JobStore
func (_mock *JobStore) UpdateStatusOptimistically(id string, currentStatus string, newStatus string) (*model.Job, error) {
	ret := _mock.Called(id, currentStatus, newStatus)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusOptimistically")
	}

	var r0 *model.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*model.Job, error)); ok {
		return returnFunc(id, currentStatus, newStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *model.Job); ok {
		r0 = returnFunc(id, currentStatus, newStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(id, currentStatus, newStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobStore_UpdateStatusOptimistically_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusOptimistically'
type JobStore_UpdateStatusOptimistically_Call struct {
	*mock.Call
}

// UpdateStatusOptimistically is a helper method to define mock.On call
//   - id string
//   - currentStatus string
//   - newStatus string
func (_e *JobStore_Expecter) UpdateStatusOptimistically(id any, currentStatus any, newStatus any) *JobStore_UpdateStatusOptimistically_Call {
	return &JobStore_UpdateStatusOptimistically_Call{Call: _e.mock.On("UpdateStatusOptimistically", id, currentStatus, newStatus)}
}

func (_c *JobStore_UpdateStatusOptimistically_Call) Run(run func(id string, currentStatus string, newStatus string)) *JobStore_UpdateStatusOptimistically_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JobStore_UpdateStatusOptimistically_Call) Return(job *model.Job, err error) *JobStore_UpdateStatusOptimistically_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobStore_UpdateStatusOptimistically_Call) RunAndReturn(run func(id string, currentStatus string, newStatus string) (*model.Job, error)) *JobStore_UpdateStatusOptimistically_Call {
	_c.Call.Return(run)
	return _c
}
