// Code generated by mockery v2.53.6. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	mock "github.com/stretchr/testify/mock"
)

// NotificationStore is an autogenerated mock type for the NotificationStore type
type NotificationStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: id
func (_m *NotificationStore) Get(id string) (*lms_models.Notification, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.Notification, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.Notification); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: userID
func (_m *NotificationStore) GetByUser(userID string) ([]*lms_models.Notification, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*lms_models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*lms_models.Notification, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []*lms_models.Notification); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: id
func (_m *NotificationStore) MarkAsRead(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: n
func (_m *NotificationStore) Save(n *lms_models.Notification) (*lms_models.Notification, error) {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Notification) (*lms_models.Notification, error)); ok {
		return rf(n)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Notification) *lms_models.Notification); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Notification) error); ok {
		r1 = rf(n)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationStore creates a new instance of NotificationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationStore {
	mock := &NotificationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
