// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/lms_models"
	"github.com/iamleson98/sitename/server/public/model_helper"
	mock "github.com/stretchr/testify/mock"
)

// NewPaymentStore creates a new instance of PaymentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentStore {
	mock := &PaymentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PaymentStore is an autogenerated mock type for the PaymentStore type
type PaymentStore struct {
	mock.Mock
}

type PaymentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentStore) EXPECT() *PaymentStore_Expecter {
	return &PaymentStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type PaymentStore
func (_mock *PaymentStore) Get(id string) (*lms_models.Payment, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*lms_models.Payment, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *lms_models.Payment); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PaymentStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *PaymentStore_Expecter) Get(id any) *PaymentStore_Get_Call {
	return &PaymentStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *PaymentStore_Get_Call) Run(run func(id string)) *PaymentStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentStore_Get_Call) Return(payment *lms_models.Payment, err error) *PaymentStore_Get_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *PaymentStore_Get_Call) RunAndReturn(run func(id string) (*lms_models.Payment, error)) *PaymentStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTuition provides a mock function for the type PaymentStore
func (_mock *PaymentStore) GetByTuition(tuitionID string) ([]*lms_models.Payment, error) {
	ret := _mock.Called(tuitionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTuition")
	}

	var r0 []*lms_models.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*lms_models.Payment, error)); ok {
		return returnFunc(tuitionID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*lms_models.Payment); ok {
		r0 = returnFunc(tuitionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tuitionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentStore_GetByTuition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTuition'
type PaymentStore_GetByTuition_Call struct {
	*mock.Call
}

// GetByTuition is a helper method to define mock.On call
//   - tuitionID string
func (_e *PaymentStore_Expecter) GetByTuition(tuitionID any) *PaymentStore_GetByTuition_Call {
	return &PaymentStore_GetByTuition_Call{Call: _e.mock.On("GetByTuition", tuitionID)}
}

func (_c *PaymentStore_GetByTuition_Call) Run(run func(tuitionID string)) *PaymentStore_GetByTuition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentStore_GetByTuition_Call) Return(payments []*lms_models.Payment, err error) *PaymentStore_GetByTuition_Call {
	_c.Call.Return(payments, err)
	return _c
}

func (_c *PaymentStore_GetByTuition_Call) RunAndReturn(run func(tuitionID string) ([]*lms_models.Payment, error)) *PaymentStore_GetByTuition_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type PaymentStore
func (_mock *PaymentStore) Save(payment *lms_models.Payment) (*lms_models.Payment, error) {
	ret := _mock.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lms_models.Payment) (*lms_models.Payment, error)); ok {
		return returnFunc(payment)
	}
	if returnFunc, ok := ret.Get(0).(func(*lms_models.Payment) *lms_models.Payment); ok {
		r0 = returnFunc(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lms_models.Payment) error); ok {
		r1 = returnFunc(payment)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PaymentStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type PaymentStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - payment *lms_models.Payment
func (_e *PaymentStore_Expecter) Save(payment any) *PaymentStore_Save_Call {
	return &PaymentStore_Save_Call{Call: _e.mock.On("Save", payment)}
}

func (_c *PaymentStore_Save_Call) Run(run func(payment *lms_models.Payment)) *PaymentStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lms_models.Payment
		if args[0] != nil {
			arg0 = args[0].(*lms_models.Payment)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentStore_Save_Call) Return(payment1 *lms_models.Payment, err error) *PaymentStore_Save_Call {
	_c.Call.Return(payment1, err)
	return _c
}

func (_c *PaymentStore_Save_Call) RunAndReturn(run func(payment *lms_models.Payment) (*lms_models.Payment, error)) *PaymentStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type PaymentStore
func (_mock *PaymentStore) Search(opts modelhelper.PaymentFilterOpts) ([]*lms_models.Payment, int64, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*lms_models.Payment
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(modelhelper.PaymentFilterOpts) ([]*lms_models.Payment, int64, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(modelhelper.PaymentFilterOpts) []*lms_models.Payment); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(modelhelper.PaymentFilterOpts) int64); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(modelhelper.PaymentFilterOpts) error); ok {
		r2 = returnFunc(opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// PaymentStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type PaymentStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - opts modelhelper.PaymentFilterOpts
func (_e *PaymentStore_Expecter) Search(opts any) *PaymentStore_Search_Call {
	return &PaymentStore_Search_Call{Call: _e.mock.On("Search", opts)}
}

func (_c *PaymentStore_Search_Call) Run(run func(opts modelhelper.PaymentFilterOpts)) *PaymentStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 modelhelper.PaymentFilterOpts
		if args[0] != nil {
			arg0 = args[0].(modelhelper.PaymentFilterOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PaymentStore_Search_Call) Return(payments []*lms_models.Payment, n int64, err error) *PaymentStore_Search_Call {
	_c.Call.Return(payments, n, err)
	return _c
}

func (_c *PaymentStore_Search_Call) RunAndReturn(run func(opts modelhelper.PaymentFilterOpts) ([]*lms_models.Payment, int64, error)) *PaymentStore_Search_Call {
	_c.Call.Return(run)
	return _c
}
