// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPostAcknowledgementStore creates a new instance of PostAcknowledgementStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostAcknowledgementStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostAcknowledgementStore {
	mock := &PostAcknowledgementStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostAcknowledgementStore is an autogenerated mock type for the PostAcknowledgementStore type
type PostAcknowledgementStore struct {
	mock.Mock
}

type PostAcknowledgementStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PostAcknowledgementStore) EXPECT() *PostAcknowledgementStore_Expecter {
	return &PostAcknowledgementStore_Expecter{mock: &_m.Mock}
}

// BatchDelete provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) BatchDelete(acknowledgements []*model.PostAcknowledgement) error {
	ret := _mock.Called(acknowledgements)

	if len(ret) == 0 {
		panic("no return value specified for BatchDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*model.PostAcknowledgement) error); ok {
		r0 = returnFunc(acknowledgements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostAcknowledgementStore_BatchDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchDelete'
type PostAcknowledgementStore_BatchDelete_Call struct {
	*mock.Call
}

// BatchDelete is a helper method to define mock.On call
//   - acknowledgements []*model.PostAcknowledgement
func (_e *PostAcknowledgementStore_Expecter) BatchDelete(acknowledgements any) *PostAcknowledgementStore_BatchDelete_Call {
	return &PostAcknowledgementStore_BatchDelete_Call{Call: _e.mock.On("BatchDelete", acknowledgements)}
}

func (_c *PostAcknowledgementStore_BatchDelete_Call) Run(run func(acknowledgements []*model.PostAcknowledgement)) *PostAcknowledgementStore_BatchDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*model.PostAcknowledgement
		if args[0] != nil {
			arg0 = args[0].([]*model.PostAcknowledgement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_BatchDelete_Call) Return(err error) *PostAcknowledgementStore_BatchDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostAcknowledgementStore_BatchDelete_Call) RunAndReturn(run func(acknowledgements []*model.PostAcknowledgement) error) *PostAcknowledgementStore_BatchDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BatchSave provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) BatchSave(acknowledgements []*model.PostAcknowledgement) ([]*model.PostAcknowledgement, error) {
	ret := _mock.Called(acknowledgements)

	if len(ret) == 0 {
		panic("no return value specified for BatchSave")
	}

	var r0 []*model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*model.PostAcknowledgement) ([]*model.PostAcknowledgement, error)); ok {
		return returnFunc(acknowledgements)
	}
	if returnFunc, ok := ret.Get(0).(func([]*model.PostAcknowledgement) []*model.PostAcknowledgement); ok {
		r0 = returnFunc(acknowledgements)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*model.PostAcknowledgement) error); ok {
		r1 = returnFunc(acknowledgements)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_BatchSave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchSave'
type PostAcknowledgementStore_BatchSave_Call struct {
	*mock.Call
}

// BatchSave is a helper method to define mock.On call
//   - acknowledgements []*model.PostAcknowledgement
func (_e *PostAcknowledgementStore_Expecter) BatchSave(acknowledgements any) *PostAcknowledgementStore_BatchSave_Call {
	return &PostAcknowledgementStore_BatchSave_Call{Call: _e.mock.On("BatchSave", acknowledgements)}
}

func (_c *PostAcknowledgementStore_BatchSave_Call) Run(run func(acknowledgements []*model.PostAcknowledgement)) *PostAcknowledgementStore_BatchSave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*model.PostAcknowledgement
		if args[0] != nil {
			arg0 = args[0].([]*model.PostAcknowledgement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_BatchSave_Call) Return(postAcknowledgements []*model.PostAcknowledgement, err error) *PostAcknowledgementStore_BatchSave_Call {
	_c.Call.Return(postAcknowledgements, err)
	return _c
}

func (_c *PostAcknowledgementStore_BatchSave_Call) RunAndReturn(run func(acknowledgements []*model.PostAcknowledgement) ([]*model.PostAcknowledgement, error)) *PostAcknowledgementStore_BatchSave_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) Delete(acknowledgement *model.PostAcknowledgement) error {
	ret := _mock.Called(acknowledgement)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.PostAcknowledgement) error); ok {
		r0 = returnFunc(acknowledgement)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostAcknowledgementStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PostAcknowledgementStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - acknowledgement *model.PostAcknowledgement
func (_e *PostAcknowledgementStore_Expecter) Delete(acknowledgement any) *PostAcknowledgementStore_Delete_Call {
	return &PostAcknowledgementStore_Delete_Call{Call: _e.mock.On("Delete", acknowledgement)}
}

func (_c *PostAcknowledgementStore_Delete_Call) Run(run func(acknowledgement *model.PostAcknowledgement)) *PostAcknowledgementStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.PostAcknowledgement
		if args[0] != nil {
			arg0 = args[0].(*model.PostAcknowledgement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_Delete_Call) Return(err error) *PostAcknowledgementStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostAcknowledgementStore_Delete_Call) RunAndReturn(run func(acknowledgement *model.PostAcknowledgement) error) *PostAcknowledgementStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllForPost provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) DeleteAllForPost(postID string) error {
	ret := _mock.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostAcknowledgementStore_DeleteAllForPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllForPost'
type PostAcknowledgementStore_DeleteAllForPost_Call struct {
	*mock.Call
}

// DeleteAllForPost is a helper method to define mock.On call
//   - postID string
func (_e *PostAcknowledgementStore_Expecter) DeleteAllForPost(postID any) *PostAcknowledgementStore_DeleteAllForPost_Call {
	return &PostAcknowledgementStore_DeleteAllForPost_Call{Call: _e.mock.On("DeleteAllForPost", postID)}
}

func (_c *PostAcknowledgementStore_DeleteAllForPost_Call) Run(run func(postID string)) *PostAcknowledgementStore_DeleteAllForPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_DeleteAllForPost_Call) Return(err error) *PostAcknowledgementStore_DeleteAllForPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostAcknowledgementStore_DeleteAllForPost_Call) RunAndReturn(run func(postID string) error) *PostAcknowledgementStore_DeleteAllForPost_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) Get(postID string, userID string) (*model.PostAcknowledgement, error) {
	ret := _mock.Called(postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.PostAcknowledgement, error)); ok {
		return returnFunc(postID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.PostAcknowledgement); ok {
		r0 = returnFunc(postID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(postID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PostAcknowledgementStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - postID string
//   - userID string
func (_e *PostAcknowledgementStore_Expecter) Get(postID any, userID any) *PostAcknowledgementStore_Get_Call {
	return &PostAcknowledgementStore_Get_Call{Call: _e.mock.On("Get", postID, userID)}
}

func (_c *PostAcknowledgementStore_Get_Call) Run(run func(postID string, userID string)) *PostAcknowledgementStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_Get_Call) Return(postAcknowledgement *model.PostAcknowledgement, err error) *PostAcknowledgementStore_Get_Call {
	_c.Call.Return(postAcknowledgement, err)
	return _c
}

func (_c *PostAcknowledgementStore_Get_Call) RunAndReturn(run func(postID string, userID string) (*model.PostAcknowledgement, error)) *PostAcknowledgementStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetForPost provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) GetForPost(postID string) ([]*model.PostAcknowledgement, error) {
	ret := _mock.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for GetForPost")
	}

	var r0 []*model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*model.PostAcknowledgement, error)); ok {
		return returnFunc(postID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*model.PostAcknowledgement); ok {
		r0 = returnFunc(postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_GetForPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForPost'
type PostAcknowledgementStore_GetForPost_Call struct {
	*mock.Call
}

// GetForPost is a helper method to define mock.On call
//   - postID string
func (_e *PostAcknowledgementStore_Expecter) GetForPost(postID any) *PostAcknowledgementStore_GetForPost_Call {
	return &PostAcknowledgementStore_GetForPost_Call{Call: _e.mock.On("GetForPost", postID)}
}

func (_c *PostAcknowledgementStore_GetForPost_Call) Run(run func(postID string)) *PostAcknowledgementStore_GetForPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_GetForPost_Call) Return(postAcknowledgements []*model.PostAcknowledgement, err error) *PostAcknowledgementStore_GetForPost_Call {
	_c.Call.Return(postAcknowledgements, err)
	return _c
}

func (_c *PostAcknowledgementStore_GetForPost_Call) RunAndReturn(run func(postID string) ([]*model.PostAcknowledgement, error)) *PostAcknowledgementStore_GetForPost_Call {
	_c.Call.Return(run)
	return _c
}

// GetForPostSince provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) GetForPostSince(postID string, since int64, excludeRemoteID string, inclDeleted bool) ([]*model.PostAcknowledgement, error) {
	ret := _mock.Called(postID, since, excludeRemoteID, inclDeleted)

	if len(ret) == 0 {
		panic("no return value specified for GetForPostSince")
	}

	var r0 []*model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int64, string, bool) ([]*model.PostAcknowledgement, error)); ok {
		return returnFunc(postID, since, excludeRemoteID, inclDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int64, string, bool) []*model.PostAcknowledgement); ok {
		r0 = returnFunc(postID, since, excludeRemoteID, inclDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int64, string, bool) error); ok {
		r1 = returnFunc(postID, since, excludeRemoteID, inclDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_GetForPostSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForPostSince'
type PostAcknowledgementStore_GetForPostSince_Call struct {
	*mock.Call
}

// GetForPostSince is a helper method to define mock.On call
//   - postID string
//   - since int64
//   - excludeRemoteID string
//   - inclDeleted bool
func (_e *PostAcknowledgementStore_Expecter) GetForPostSince(postID any, since any, excludeRemoteID any, inclDeleted any) *PostAcknowledgementStore_GetForPostSince_Call {
	return &PostAcknowledgementStore_GetForPostSince_Call{Call: _e.mock.On("GetForPostSince", postID, since, excludeRemoteID, inclDeleted)}
}

func (_c *PostAcknowledgementStore_GetForPostSince_Call) Run(run func(postID string, since int64, excludeRemoteID string, inclDeleted bool)) *PostAcknowledgementStore_GetForPostSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_GetForPostSince_Call) Return(postAcknowledgements []*model.PostAcknowledgement, err error) *PostAcknowledgementStore_GetForPostSince_Call {
	_c.Call.Return(postAcknowledgements, err)
	return _c
}

func (_c *PostAcknowledgementStore_GetForPostSince_Call) RunAndReturn(run func(postID string, since int64, excludeRemoteID string, inclDeleted bool) ([]*model.PostAcknowledgement, error)) *PostAcknowledgementStore_GetForPostSince_Call {
	_c.Call.Return(run)
	return _c
}

// GetForPosts provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) GetForPosts(postIds []string) ([]*model.PostAcknowledgement, error) {
	ret := _mock.Called(postIds)

	if len(ret) == 0 {
		panic("no return value specified for GetForPosts")
	}

	var r0 []*model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]*model.PostAcknowledgement, error)); ok {
		return returnFunc(postIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []*model.PostAcknowledgement); ok {
		r0 = returnFunc(postIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(postIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_GetForPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForPosts'
type PostAcknowledgementStore_GetForPosts_Call struct {
	*mock.Call
}

// GetForPosts is a helper method to define mock.On call
//   - postIds []string
func (_e *PostAcknowledgementStore_Expecter) GetForPosts(postIds any) *PostAcknowledgementStore_GetForPosts_Call {
	return &PostAcknowledgementStore_GetForPosts_Call{Call: _e.mock.On("GetForPosts", postIds)}
}

func (_c *PostAcknowledgementStore_GetForPosts_Call) Run(run func(postIds []string)) *PostAcknowledgementStore_GetForPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_GetForPosts_Call) Return(postAcknowledgements []*model.PostAcknowledgement, err error) *PostAcknowledgementStore_GetForPosts_Call {
	_c.Call.Return(postAcknowledgements, err)
	return _c
}

func (_c *PostAcknowledgementStore_GetForPosts_Call) RunAndReturn(run func(postIds []string) ([]*model.PostAcknowledgement, error)) *PostAcknowledgementStore_GetForPosts_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingle provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) GetSingle(userID string, postID string, remoteID string) (*model.PostAcknowledgement, error) {
	ret := _mock.Called(userID, postID, remoteID)

	if len(ret) == 0 {
		panic("no return value specified for GetSingle")
	}

	var r0 *model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*model.PostAcknowledgement, error)); ok {
		return returnFunc(userID, postID, remoteID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *model.PostAcknowledgement); ok {
		r0 = returnFunc(userID, postID, remoteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(userID, postID, remoteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_GetSingle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingle'
type PostAcknowledgementStore_GetSingle_Call struct {
	*mock.Call
}

// GetSingle is a helper method to define mock.On call
//   - userID string
//   - postID string
//   - remoteID string
func (_e *PostAcknowledgementStore_Expecter) GetSingle(userID any, postID any, remoteID any) *PostAcknowledgementStore_GetSingle_Call {
	return &PostAcknowledgementStore_GetSingle_Call{Call: _e.mock.On("GetSingle", userID, postID, remoteID)}
}

func (_c *PostAcknowledgementStore_GetSingle_Call) Run(run func(userID string, postID string, remoteID string)) *PostAcknowledgementStore_GetSingle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_GetSingle_Call) Return(postAcknowledgement *model.PostAcknowledgement, err error) *PostAcknowledgementStore_GetSingle_Call {
	_c.Call.Return(postAcknowledgement, err)
	return _c
}

func (_c *PostAcknowledgementStore_GetSingle_Call) RunAndReturn(run func(userID string, postID string, remoteID string) (*model.PostAcknowledgement, error)) *PostAcknowledgementStore_GetSingle_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithModel provides a mock function for the type PostAcknowledgementStore
func (_mock *PostAcknowledgementStore) SaveWithModel(acknowledgement *model.PostAcknowledgement) (*model.PostAcknowledgement, error) {
	ret := _mock.Called(acknowledgement)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithModel")
	}

	var r0 *model.PostAcknowledgement
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.PostAcknowledgement) (*model.PostAcknowledgement, error)); ok {
		return returnFunc(acknowledgement)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.PostAcknowledgement) *model.PostAcknowledgement); ok {
		r0 = returnFunc(acknowledgement)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostAcknowledgement)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.PostAcknowledgement) error); ok {
		r1 = returnFunc(acknowledgement)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostAcknowledgementStore_SaveWithModel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithModel'
type PostAcknowledgementStore_SaveWithModel_Call struct {
	*mock.Call
}

// SaveWithModel is a helper method to define mock.On call
//   - acknowledgement *model.PostAcknowledgement
func (_e *PostAcknowledgementStore_Expecter) SaveWithModel(acknowledgement any) *PostAcknowledgementStore_SaveWithModel_Call {
	return &PostAcknowledgementStore_SaveWithModel_Call{Call: _e.mock.On("SaveWithModel", acknowledgement)}
}

func (_c *PostAcknowledgementStore_SaveWithModel_Call) Run(run func(acknowledgement *model.PostAcknowledgement)) *PostAcknowledgementStore_SaveWithModel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.PostAcknowledgement
		if args[0] != nil {
			arg0 = args[0].(*model.PostAcknowledgement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostAcknowledgementStore_SaveWithModel_Call) Return(postAcknowledgement *model.PostAcknowledgement, err error) *PostAcknowledgementStore_SaveWithModel_Call {
	_c.Call.Return(postAcknowledgement, err)
	return _c
}

func (_c *PostAcknowledgementStore_SaveWithModel_Call) RunAndReturn(run func(acknowledgement *model.PostAcknowledgement) (*model.PostAcknowledgement, error)) *PostAcknowledgementStore_SaveWithModel_Call {
	_c.Call.Return(run)
	return _c
}
