// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPostPriorityStore creates a new instance of PostPriorityStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostPriorityStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostPriorityStore {
	mock := &PostPriorityStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostPriorityStore is an autogenerated mock type for the PostPriorityStore type
type PostPriorityStore struct {
	mock.Mock
}

type PostPriorityStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PostPriorityStore) EXPECT() *PostPriorityStore_Expecter {
	return &PostPriorityStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type PostPriorityStore
func (_mock *PostPriorityStore) Delete(postID string) error {
	ret := _mock.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPriorityStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PostPriorityStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - postID string
func (_e *PostPriorityStore_Expecter) Delete(postID any) *PostPriorityStore_Delete_Call {
	return &PostPriorityStore_Delete_Call{Call: _e.mock.On("Delete", postID)}
}

func (_c *PostPriorityStore_Delete_Call) Run(run func(postID string)) *PostPriorityStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPriorityStore_Delete_Call) Return(err error) *PostPriorityStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPriorityStore_Delete_Call) RunAndReturn(run func(postID string) error) *PostPriorityStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetForPost provides a mock function for the type PostPriorityStore
func (_mock *PostPriorityStore) GetForPost(postID string) (*model.PostPriority, error) {
	ret := _mock.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for GetForPost")
	}

	var r0 *model.PostPriority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.PostPriority, error)); ok {
		return returnFunc(postID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.PostPriority); ok {
		r0 = returnFunc(postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostPriority)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostPriorityStore_GetForPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForPost'
type PostPriorityStore_GetForPost_Call struct {
	*mock.Call
}

// GetForPost is a helper method to define mock.On call
//   - postID string
func (_e *PostPriorityStore_Expecter) GetForPost(postID any) *PostPriorityStore_GetForPost_Call {
	return &PostPriorityStore_GetForPost_Call{Call: _e.mock.On("GetForPost", postID)}
}

func (_c *PostPriorityStore_GetForPost_Call) Run(run func(postID string)) *PostPriorityStore_GetForPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPriorityStore_GetForPost_Call) Return(postPriority *model.PostPriority, err error) *PostPriorityStore_GetForPost_Call {
	_c.Call.Return(postPriority, err)
	return _c
}

func (_c *PostPriorityStore_GetForPost_Call) RunAndReturn(run func(postID string) (*model.PostPriority, error)) *PostPriorityStore_GetForPost_Call {
	_c.Call.Return(run)
	return _c
}

// GetForPosts provides a mock function for the type PostPriorityStore
func (_mock *PostPriorityStore) GetForPosts(ids []string) ([]*model.PostPriority, error) {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetForPosts")
	}

	var r0 []*model.PostPriority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]*model.PostPriority, error)); ok {
		return returnFunc(ids)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []*model.PostPriority); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostPriority)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostPriorityStore_GetForPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForPosts'
type PostPriorityStore_GetForPosts_Call struct {
	*mock.Call
}

// GetForPosts is a helper method to define mock.On call
//   - ids []string
func (_e *PostPriorityStore_Expecter) GetForPosts(ids any) *PostPriorityStore_GetForPosts_Call {
	return &PostPriorityStore_GetForPosts_Call{Call: _e.mock.On("GetForPosts", ids)}
}

func (_c *PostPriorityStore_GetForPosts_Call) Run(run func(ids []string)) *PostPriorityStore_GetForPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPriorityStore_GetForPosts_Call) Return(postPrioritys []*model.PostPriority, err error) *PostPriorityStore_GetForPosts_Call {
	_c.Call.Return(postPrioritys, err)
	return _c
}

func (_c *PostPriorityStore_GetForPosts_Call) RunAndReturn(run func(ids []string) ([]*model.PostPriority, error)) *PostPriorityStore_GetForPosts_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type PostPriorityStore
func (_mock *PostPriorityStore) Save(priority *model.PostPriority) (*model.PostPriority, error) {
	ret := _mock.Called(priority)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.PostPriority
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.PostPriority) (*model.PostPriority, error)); ok {
		return returnFunc(priority)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.PostPriority) *model.PostPriority); ok {
		r0 = returnFunc(priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostPriority)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.PostPriority) error); ok {
		r1 = returnFunc(priority)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostPriorityStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type PostPriorityStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - priority *model.PostPriority
func (_e *PostPriorityStore_Expecter) Save(priority any) *PostPriorityStore_Save_Call {
	return &PostPriorityStore_Save_Call{Call: _e.mock.On("Save", priority)}
}

func (_c *PostPriorityStore_Save_Call) Run(run func(priority *model.PostPriority)) *PostPriorityStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.PostPriority
		if args[0] != nil {
			arg0 = args[0].(*model.PostPriority)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPriorityStore_Save_Call) Return(postPriority *model.PostPriority, err error) *PostPriorityStore_Save_Call {
	_c.Call.Return(postPriority, err)
	return _c
}

func (_c *PostPriorityStore_Save_Call) RunAndReturn(run func(priority *model.PostPriority) (*model.PostPriority, error)) *PostPriorityStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
