// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewPostPersistentNotificationStore creates a new instance of PostPersistentNotificationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostPersistentNotificationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostPersistentNotificationStore {
	mock := &PostPersistentNotificationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostPersistentNotificationStore is an autogenerated mock type for the PostPersistentNotificationStore type
type PostPersistentNotificationStore struct {
	mock.Mock
}

type PostPersistentNotificationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *PostPersistentNotificationStore) EXPECT() *PostPersistentNotificationStore_Expecter {
	return &PostPersistentNotificationStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) Delete(postIds []string) error {
	ret := _mock.Called(postIds)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(postIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPersistentNotificationStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type PostPersistentNotificationStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - postIds []string
func (_e *PostPersistentNotificationStore_Expecter) Delete(postIds any) *PostPersistentNotificationStore_Delete_Call {
	return &PostPersistentNotificationStore_Delete_Call{Call: _e.mock.On("Delete", postIds)}
}

func (_c *PostPersistentNotificationStore_Delete_Call) Run(run func(postIds []string)) *PostPersistentNotificationStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_Delete_Call) Return(err error) *PostPersistentNotificationStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPersistentNotificationStore_Delete_Call) RunAndReturn(run func(postIds []string) error) *PostPersistentNotificationStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByChannel provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) DeleteByChannel(channelIds []string) error {
	ret := _mock.Called(channelIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByChannel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(channelIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPersistentNotificationStore_DeleteByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByChannel'
type PostPersistentNotificationStore_DeleteByChannel_Call struct {
	*mock.Call
}

// DeleteByChannel is a helper method to define mock.On call
//   - channelIds []string
func (_e *PostPersistentNotificationStore_Expecter) DeleteByChannel(channelIds any) *PostPersistentNotificationStore_DeleteByChannel_Call {
	return &PostPersistentNotificationStore_DeleteByChannel_Call{Call: _e.mock.On("DeleteByChannel", channelIds)}
}

func (_c *PostPersistentNotificationStore_DeleteByChannel_Call) Run(run func(channelIds []string)) *PostPersistentNotificationStore_DeleteByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteByChannel_Call) Return(err error) *PostPersistentNotificationStore_DeleteByChannel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteByChannel_Call) RunAndReturn(run func(channelIds []string) error) *PostPersistentNotificationStore_DeleteByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTeam provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) DeleteByTeam(teamIds []string) error {
	ret := _mock.Called(teamIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(teamIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPersistentNotificationStore_DeleteByTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTeam'
type PostPersistentNotificationStore_DeleteByTeam_Call struct {
	*mock.Call
}

// DeleteByTeam is a helper method to define mock.On call
//   - teamIds []string
func (_e *PostPersistentNotificationStore_Expecter) DeleteByTeam(teamIds any) *PostPersistentNotificationStore_DeleteByTeam_Call {
	return &PostPersistentNotificationStore_DeleteByTeam_Call{Call: _e.mock.On("DeleteByTeam", teamIds)}
}

func (_c *PostPersistentNotificationStore_DeleteByTeam_Call) Run(run func(teamIds []string)) *PostPersistentNotificationStore_DeleteByTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteByTeam_Call) Return(err error) *PostPersistentNotificationStore_DeleteByTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteByTeam_Call) RunAndReturn(run func(teamIds []string) error) *PostPersistentNotificationStore_DeleteByTeam_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) DeleteExpired(maxSentCount int16) error {
	ret := _mock.Called(maxSentCount)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int16) error); ok {
		r0 = returnFunc(maxSentCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPersistentNotificationStore_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type PostPersistentNotificationStore_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - maxSentCount int16
func (_e *PostPersistentNotificationStore_Expecter) DeleteExpired(maxSentCount any) *PostPersistentNotificationStore_DeleteExpired_Call {
	return &PostPersistentNotificationStore_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", maxSentCount)}
}

func (_c *PostPersistentNotificationStore_DeleteExpired_Call) Run(run func(maxSentCount int16)) *PostPersistentNotificationStore_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int16
		if args[0] != nil {
			arg0 = args[0].(int16)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteExpired_Call) Return(err error) *PostPersistentNotificationStore_DeleteExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPersistentNotificationStore_DeleteExpired_Call) RunAndReturn(run func(maxSentCount int16) error) *PostPersistentNotificationStore_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) Get(params model.GetPersistentNotificationsPostsParams) ([]*model.PostPersistentNotifications, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*model.PostPersistentNotifications
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.GetPersistentNotificationsPostsParams) ([]*model.PostPersistentNotifications, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(model.GetPersistentNotificationsPostsParams) []*model.PostPersistentNotifications); ok {
		r0 = returnFunc(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.PostPersistentNotifications)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.GetPersistentNotificationsPostsParams) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostPersistentNotificationStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PostPersistentNotificationStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - params model.GetPersistentNotificationsPostsParams
func (_e *PostPersistentNotificationStore_Expecter) Get(params any) *PostPersistentNotificationStore_Get_Call {
	return &PostPersistentNotificationStore_Get_Call{Call: _e.mock.On("Get", params)}
}

func (_c *PostPersistentNotificationStore_Get_Call) Run(run func(params model.GetPersistentNotificationsPostsParams)) *PostPersistentNotificationStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.GetPersistentNotificationsPostsParams
		if args[0] != nil {
			arg0 = args[0].(model.GetPersistentNotificationsPostsParams)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_Get_Call) Return(postPersistentNotificationss []*model.PostPersistentNotifications, err error) *PostPersistentNotificationStore_Get_Call {
	_c.Call.Return(postPersistentNotificationss, err)
	return _c
}

func (_c *PostPersistentNotificationStore_Get_Call) RunAndReturn(run func(params model.GetPersistentNotificationsPostsParams) ([]*model.PostPersistentNotifications, error)) *PostPersistentNotificationStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingle provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) GetSingle(postID string) (*model.PostPersistentNotifications, error) {
	ret := _mock.Called(postID)

	if len(ret) == 0 {
		panic("no return value specified for GetSingle")
	}

	var r0 *model.PostPersistentNotifications
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.PostPersistentNotifications, error)); ok {
		return returnFunc(postID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.PostPersistentNotifications); ok {
		r0 = returnFunc(postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PostPersistentNotifications)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostPersistentNotificationStore_GetSingle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingle'
type PostPersistentNotificationStore_GetSingle_Call struct {
	*mock.Call
}

// GetSingle is a helper method to define mock.On call
//   - postID string
func (_e *PostPersistentNotificationStore_Expecter) GetSingle(postID any) *PostPersistentNotificationStore_GetSingle_Call {
	return &PostPersistentNotificationStore_GetSingle_Call{Call: _e.mock.On("GetSingle", postID)}
}

func (_c *PostPersistentNotificationStore_GetSingle_Call) Run(run func(postID string)) *PostPersistentNotificationStore_GetSingle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_GetSingle_Call) Return(postPersistentNotifications *model.PostPersistentNotifications, err error) *PostPersistentNotificationStore_GetSingle_Call {
	_c.Call.Return(postPersistentNotifications, err)
	return _c
}

func (_c *PostPersistentNotificationStore_GetSingle_Call) RunAndReturn(run func(postID string) (*model.PostPersistentNotifications, error)) *PostPersistentNotificationStore_GetSingle_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastActivity provides a mock function for the type PostPersistentNotificationStore
func (_mock *PostPersistentNotificationStore) UpdateLastActivity(postIds []string) error {
	ret := _mock.Called(postIds)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string) error); ok {
		r0 = returnFunc(postIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostPersistentNotificationStore_UpdateLastActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastActivity'
type PostPersistentNotificationStore_UpdateLastActivity_Call struct {
	*mock.Call
}

// UpdateLastActivity is a helper method to define mock.On call
//   - postIds []string
func (_e *PostPersistentNotificationStore_Expecter) UpdateLastActivity(postIds any) *PostPersistentNotificationStore_UpdateLastActivity_Call {
	return &PostPersistentNotificationStore_UpdateLastActivity_Call{Call: _e.mock.On("UpdateLastActivity", postIds)}
}

func (_c *PostPersistentNotificationStore_UpdateLastActivity_Call) Run(run func(postIds []string)) *PostPersistentNotificationStore_UpdateLastActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PostPersistentNotificationStore_UpdateLastActivity_Call) Return(err error) *PostPersistentNotificationStore_UpdateLastActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostPersistentNotificationStore_UpdateLastActivity_Call) RunAndReturn(run func(postIds []string) error) *PostPersistentNotificationStore_UpdateLastActivity_Call {
	_c.Call.Return(run)
	return _c
}
