// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewRemoteClusterStore creates a new instance of RemoteClusterStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoteClusterStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoteClusterStore {
	mock := &RemoteClusterStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RemoteClusterStore is an autogenerated mock type for the RemoteClusterStore type
type RemoteClusterStore struct {
	mock.Mock
}

type RemoteClusterStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RemoteClusterStore) EXPECT() *RemoteClusterStore_Expecter {
	return &RemoteClusterStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) Delete(remoteClusterID string) (bool, error) {
	ret := _mock.Called(remoteClusterID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(remoteClusterID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(remoteClusterID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(remoteClusterID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RemoteClusterStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - remoteClusterID string
func (_e *RemoteClusterStore_Expecter) Delete(remoteClusterID any) *RemoteClusterStore_Delete_Call {
	return &RemoteClusterStore_Delete_Call{Call: _e.mock.On("Delete", remoteClusterID)}
}

func (_c *RemoteClusterStore_Delete_Call) Run(run func(remoteClusterID string)) *RemoteClusterStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_Delete_Call) Return(b bool, err error) *RemoteClusterStore_Delete_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *RemoteClusterStore_Delete_Call) RunAndReturn(run func(remoteClusterID string) (bool, error)) *RemoteClusterStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) Get(remoteClusterID string, includeDeleted bool) (*model.RemoteCluster, error) {
	ret := _mock.Called(remoteClusterID, includeDeleted)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (*model.RemoteCluster, error)); ok {
		return returnFunc(remoteClusterID, includeDeleted)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) *model.RemoteCluster); ok {
		r0 = returnFunc(remoteClusterID, includeDeleted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(remoteClusterID, includeDeleted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type RemoteClusterStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - remoteClusterID string
//   - includeDeleted bool
func (_e *RemoteClusterStore_Expecter) Get(remoteClusterID any, includeDeleted any) *RemoteClusterStore_Get_Call {
	return &RemoteClusterStore_Get_Call{Call: _e.mock.On("Get", remoteClusterID, includeDeleted)}
}

func (_c *RemoteClusterStore_Get_Call) Run(run func(remoteClusterID string, includeDeleted bool)) *RemoteClusterStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_Get_Call) Return(remoteCluster *model.RemoteCluster, err error) *RemoteClusterStore_Get_Call {
	_c.Call.Return(remoteCluster, err)
	return _c
}

func (_c *RemoteClusterStore_Get_Call) RunAndReturn(run func(remoteClusterID string, includeDeleted bool) (*model.RemoteCluster, error)) *RemoteClusterStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) GetAll(offset int, limit int, filter model.RemoteClusterQueryFilter) ([]*model.RemoteCluster, error) {
	ret := _mock.Called(offset, limit, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int, model.RemoteClusterQueryFilter) ([]*model.RemoteCluster, error)); ok {
		return returnFunc(offset, limit, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, model.RemoteClusterQueryFilter) []*model.RemoteCluster); ok {
		r0 = returnFunc(offset, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, model.RemoteClusterQueryFilter) error); ok {
		r1 = returnFunc(offset, limit, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RemoteClusterStore_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - offset int
//   - limit int
//   - filter model.RemoteClusterQueryFilter
func (_e *RemoteClusterStore_Expecter) GetAll(offset any, limit any, filter any) *RemoteClusterStore_GetAll_Call {
	return &RemoteClusterStore_GetAll_Call{Call: _e.mock.On("GetAll", offset, limit, filter)}
}

func (_c *RemoteClusterStore_GetAll_Call) Run(run func(offset int, limit int, filter model.RemoteClusterQueryFilter)) *RemoteClusterStore_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 model.RemoteClusterQueryFilter
		if args[2] != nil {
			arg2 = args[2].(model.RemoteClusterQueryFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_GetAll_Call) Return(remoteClusters []*model.RemoteCluster, err error) *RemoteClusterStore_GetAll_Call {
	_c.Call.Return(remoteClusters, err)
	return _c
}

func (_c *RemoteClusterStore_GetAll_Call) RunAndReturn(run func(offset int, limit int, filter model.RemoteClusterQueryFilter) ([]*model.RemoteCluster, error)) *RemoteClusterStore_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPluginID provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) GetByPluginID(pluginID string) (*model.RemoteCluster, error) {
	ret := _mock.Called(pluginID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPluginID")
	}

	var r0 *model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.RemoteCluster, error)); ok {
		return returnFunc(pluginID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.RemoteCluster); ok {
		r0 = returnFunc(pluginID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pluginID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_GetByPluginID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPluginID'
type RemoteClusterStore_GetByPluginID_Call struct {
	*mock.Call
}

// GetByPluginID is a helper method to define mock.On call
//   - pluginID string
func (_e *RemoteClusterStore_Expecter) GetByPluginID(pluginID any) *RemoteClusterStore_GetByPluginID_Call {
	return &RemoteClusterStore_GetByPluginID_Call{Call: _e.mock.On("GetByPluginID", pluginID)}
}

func (_c *RemoteClusterStore_GetByPluginID_Call) Run(run func(pluginID string)) *RemoteClusterStore_GetByPluginID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_GetByPluginID_Call) Return(remoteCluster *model.RemoteCluster, err error) *RemoteClusterStore_GetByPluginID_Call {
	_c.Call.Return(remoteCluster, err)
	return _c
}

func (_c *RemoteClusterStore_GetByPluginID_Call) RunAndReturn(run func(pluginID string) (*model.RemoteCluster, error)) *RemoteClusterStore_GetByPluginID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) Save(rc *model.RemoteCluster) (*model.RemoteCluster, error) {
	ret := _mock.Called(rc)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.RemoteCluster) (*model.RemoteCluster, error)); ok {
		return returnFunc(rc)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.RemoteCluster) *model.RemoteCluster); ok {
		r0 = returnFunc(rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.RemoteCluster) error); ok {
		r1 = returnFunc(rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type RemoteClusterStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - rc *model.RemoteCluster
func (_e *RemoteClusterStore_Expecter) Save(rc any) *RemoteClusterStore_Save_Call {
	return &RemoteClusterStore_Save_Call{Call: _e.mock.On("Save", rc)}
}

func (_c *RemoteClusterStore_Save_Call) Run(run func(rc *model.RemoteCluster)) *RemoteClusterStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.RemoteCluster
		if args[0] != nil {
			arg0 = args[0].(*model.RemoteCluster)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_Save_Call) Return(remoteCluster *model.RemoteCluster, err error) *RemoteClusterStore_Save_Call {
	_c.Call.Return(remoteCluster, err)
	return _c
}

func (_c *RemoteClusterStore_Save_Call) RunAndReturn(run func(rc *model.RemoteCluster) (*model.RemoteCluster, error)) *RemoteClusterStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastPingAt provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) SetLastPingAt(remoteClusterID string) error {
	ret := _mock.Called(remoteClusterID)

	if len(ret) == 0 {
		panic("no return value specified for SetLastPingAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(remoteClusterID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteClusterStore_SetLastPingAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastPingAt'
type RemoteClusterStore_SetLastPingAt_Call struct {
	*mock.Call
}

// SetLastPingAt is a helper method to define mock.On call
//   - remoteClusterID string
func (_e *RemoteClusterStore_Expecter) SetLastPingAt(remoteClusterID any) *RemoteClusterStore_SetLastPingAt_Call {
	return &RemoteClusterStore_SetLastPingAt_Call{Call: _e.mock.On("SetLastPingAt", remoteClusterID)}
}

func (_c *RemoteClusterStore_SetLastPingAt_Call) Run(run func(remoteClusterID string)) *RemoteClusterStore_SetLastPingAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_SetLastPingAt_Call) Return(err error) *RemoteClusterStore_SetLastPingAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteClusterStore_SetLastPingAt_Call) RunAndReturn(run func(remoteClusterID string) error) *RemoteClusterStore_SetLastPingAt_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) Update(rc *model.RemoteCluster) (*model.RemoteCluster, error) {
	ret := _mock.Called(rc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.RemoteCluster) (*model.RemoteCluster, error)); ok {
		return returnFunc(rc)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.RemoteCluster) *model.RemoteCluster); ok {
		r0 = returnFunc(rc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.RemoteCluster) error); ok {
		r1 = returnFunc(rc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RemoteClusterStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - rc *model.RemoteCluster
func (_e *RemoteClusterStore_Expecter) Update(rc any) *RemoteClusterStore_Update_Call {
	return &RemoteClusterStore_Update_Call{Call: _e.mock.On("Update", rc)}
}

func (_c *RemoteClusterStore_Update_Call) Run(run func(rc *model.RemoteCluster)) *RemoteClusterStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.RemoteCluster
		if args[0] != nil {
			arg0 = args[0].(*model.RemoteCluster)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_Update_Call) Return(remoteCluster *model.RemoteCluster, err error) *RemoteClusterStore_Update_Call {
	_c.Call.Return(remoteCluster, err)
	return _c
}

func (_c *RemoteClusterStore_Update_Call) RunAndReturn(run func(rc *model.RemoteCluster) (*model.RemoteCluster, error)) *RemoteClusterStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastGlobalUserSyncAt provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) UpdateLastGlobalUserSyncAt(remoteID string, syncAt int64) error {
	ret := _mock.Called(remoteID, syncAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastGlobalUserSyncAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = returnFunc(remoteID, syncAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastGlobalUserSyncAt'
type RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call struct {
	*mock.Call
}

// UpdateLastGlobalUserSyncAt is a helper method to define mock.On call
//   - remoteID string
//   - syncAt int64
func (_e *RemoteClusterStore_Expecter) UpdateLastGlobalUserSyncAt(remoteID any, syncAt any) *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call {
	return &RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call{Call: _e.mock.On("UpdateLastGlobalUserSyncAt", remoteID, syncAt)}
}

func (_c *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call) Run(run func(remoteID string, syncAt int64)) *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call) Return(err error) *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call) RunAndReturn(run func(remoteID string, syncAt int64) error) *RemoteClusterStore_UpdateLastGlobalUserSyncAt_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopics provides a mock function for the type RemoteClusterStore
func (_mock *RemoteClusterStore) UpdateTopics(remoteClusterID string, topics string) (*model.RemoteCluster, error) {
	ret := _mock.Called(remoteClusterID, topics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopics")
	}

	var r0 *model.RemoteCluster
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*model.RemoteCluster, error)); ok {
		return returnFunc(remoteClusterID, topics)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *model.RemoteCluster); ok {
		r0 = returnFunc(remoteClusterID, topics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RemoteCluster)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(remoteClusterID, topics)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RemoteClusterStore_UpdateTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopics'
type RemoteClusterStore_UpdateTopics_Call struct {
	*mock.Call
}

// UpdateTopics is a helper method to define mock.On call
//   - remoteClusterID string
//   - topics string
func (_e *RemoteClusterStore_Expecter) UpdateTopics(remoteClusterID any, topics any) *RemoteClusterStore_UpdateTopics_Call {
	return &RemoteClusterStore_UpdateTopics_Call{Call: _e.mock.On("UpdateTopics", remoteClusterID, topics)}
}

func (_c *RemoteClusterStore_UpdateTopics_Call) Run(run func(remoteClusterID string, topics string)) *RemoteClusterStore_UpdateTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RemoteClusterStore_UpdateTopics_Call) Return(remoteCluster *model.RemoteCluster, err error) *RemoteClusterStore_UpdateTopics_Call {
	_c.Call.Return(remoteCluster, err)
	return _c
}

func (_c *RemoteClusterStore_UpdateTopics_Call) RunAndReturn(run func(remoteClusterID string, topics string) (*model.RemoteCluster, error)) *RemoteClusterStore_UpdateTopics_Call {
	_c.Call.Return(run)
	return _c
}
