// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// NewStatusStore creates a new instance of StatusStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusStore {
	mock := &StatusStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatusStore is an autogenerated mock type for the StatusStore type
type StatusStore struct {
	mock.Mock
}

type StatusStore_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusStore) EXPECT() *StatusStore_Expecter {
	return &StatusStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type StatusStore
func (_mock *StatusStore) Get(userID string) (*model.Status, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.Status, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.Status); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatusStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StatusStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *StatusStore_Expecter) Get(userID any) *StatusStore_Get_Call {
	return &StatusStore_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *StatusStore_Get_Call) Run(run func(userID string)) *StatusStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatusStore_Get_Call) Return(status *model.Status, err error) *StatusStore_Get_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *StatusStore_Get_Call) RunAndReturn(run func(userID string) (*model.Status, error)) *StatusStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIds provides a mock function for the type StatusStore
func (_mock *StatusStore) GetByIds(userIds []string) ([]*model.Status, error) {
	ret := _mock.Called(userIds)

	if len(ret) == 0 {
		panic("no return value specified for GetByIds")
	}

	var r0 []*model.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]*model.Status, error)); ok {
		return returnFunc(userIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []*model.Status); ok {
		r0 = returnFunc(userIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(userIds)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatusStore_GetByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIds'
type StatusStore_GetByIds_Call struct {
	*mock.Call
}

// GetByIds is a helper method to define mock.On call
//   - userIds []string
func (_e *StatusStore_Expecter) GetByIds(userIds any) *StatusStore_GetByIds_Call {
	return &StatusStore_GetByIds_Call{Call: _e.mock.On("GetByIds", userIds)}
}

func (_c *StatusStore_GetByIds_Call) Run(run func(userIds []string)) *StatusStore_GetByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatusStore_GetByIds_Call) Return(statuss []*model.Status, err error) *StatusStore_GetByIds_Call {
	_c.Call.Return(statuss, err)
	return _c
}

func (_c *StatusStore_GetByIds_Call) RunAndReturn(run func(userIds []string) ([]*model.Status, error)) *StatusStore_GetByIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalActiveUsersCount provides a mock function for the type StatusStore
func (_mock *StatusStore) GetTotalActiveUsersCount() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalActiveUsersCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatusStore_GetTotalActiveUsersCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalActiveUsersCount'
type StatusStore_GetTotalActiveUsersCount_Call struct {
	*mock.Call
}

// GetTotalActiveUsersCount is a helper method to define mock.On call
func (_e *StatusStore_Expecter) GetTotalActiveUsersCount() *StatusStore_GetTotalActiveUsersCount_Call {
	return &StatusStore_GetTotalActiveUsersCount_Call{Call: _e.mock.On("GetTotalActiveUsersCount")}
}

func (_c *StatusStore_GetTotalActiveUsersCount_Call) Run(run func()) *StatusStore_GetTotalActiveUsersCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusStore_GetTotalActiveUsersCount_Call) Return(n int64, err error) *StatusStore_GetTotalActiveUsersCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *StatusStore_GetTotalActiveUsersCount_Call) RunAndReturn(run func() (int64, error)) *StatusStore_GetTotalActiveUsersCount_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAll provides a mock function for the type StatusStore
func (_mock *StatusStore) ResetAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResetAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatusStore_ResetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAll'
type StatusStore_ResetAll_Call struct {
	*mock.Call
}

// ResetAll is a helper method to define mock.On call
func (_e *StatusStore_Expecter) ResetAll() *StatusStore_ResetAll_Call {
	return &StatusStore_ResetAll_Call{Call: _e.mock.On("ResetAll")}
}

func (_c *StatusStore_ResetAll_Call) Run(run func()) *StatusStore_ResetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusStore_ResetAll_Call) Return(err error) *StatusStore_ResetAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatusStore_ResetAll_Call) RunAndReturn(run func() error) *StatusStore_ResetAll_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdate provides a mock function for the type StatusStore
func (_mock *StatusStore) SaveOrUpdate(status *model.Status) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Status) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatusStore_SaveOrUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdate'
type StatusStore_SaveOrUpdate_Call struct {
	*mock.Call
}

// SaveOrUpdate is a helper method to define mock.On call
//   - status *model.Status
func (_e *StatusStore_Expecter) SaveOrUpdate(status any) *StatusStore_SaveOrUpdate_Call {
	return &StatusStore_SaveOrUpdate_Call{Call: _e.mock.On("SaveOrUpdate", status)}
}

func (_c *StatusStore_SaveOrUpdate_Call) Run(run func(status *model.Status)) *StatusStore_SaveOrUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Status
		if args[0] != nil {
			arg0 = args[0].(*model.Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatusStore_SaveOrUpdate_Call) Return(err error) *StatusStore_SaveOrUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatusStore_SaveOrUpdate_Call) RunAndReturn(run func(status *model.Status) error) *StatusStore_SaveOrUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdateMany provides a mock function for the type StatusStore
func (_mock *StatusStore) SaveOrUpdateMany(statuses map[string]*model.Status) error {
	ret := _mock.Called(statuses)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]*model.Status) error); ok {
		r0 = returnFunc(statuses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatusStore_SaveOrUpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdateMany'
type StatusStore_SaveOrUpdateMany_Call struct {
	*mock.Call
}

// SaveOrUpdateMany is a helper method to define mock.On call
//   - statuses map[string]*model.Status
func (_e *StatusStore_Expecter) SaveOrUpdateMany(statuses any) *StatusStore_SaveOrUpdateMany_Call {
	return &StatusStore_SaveOrUpdateMany_Call{Call: _e.mock.On("SaveOrUpdateMany", statuses)}
}

func (_c *StatusStore_SaveOrUpdateMany_Call) Run(run func(statuses map[string]*model.Status)) *StatusStore_SaveOrUpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]*model.Status
		if args[0] != nil {
			arg0 = args[0].(map[string]*model.Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StatusStore_SaveOrUpdateMany_Call) Return(err error) *StatusStore_SaveOrUpdateMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatusStore_SaveOrUpdateMany_Call) RunAndReturn(run func(statuses map[string]*model.Status) error) *StatusStore_SaveOrUpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExpiredDNDStatuses provides a mock function for the type StatusStore
func (_mock *StatusStore) UpdateExpiredDNDStatuses() ([]*model.Status, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpiredDNDStatuses")
	}

	var r0 []*model.Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*model.Status, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*model.Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StatusStore_UpdateExpiredDNDStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExpiredDNDStatuses'
type StatusStore_UpdateExpiredDNDStatuses_Call struct {
	*mock.Call
}

// UpdateExpiredDNDStatuses is a helper method to define mock.On call
func (_e *StatusStore_Expecter) UpdateExpiredDNDStatuses() *StatusStore_UpdateExpiredDNDStatuses_Call {
	return &StatusStore_UpdateExpiredDNDStatuses_Call{Call: _e.mock.On("UpdateExpiredDNDStatuses")}
}

func (_c *StatusStore_UpdateExpiredDNDStatuses_Call) Run(run func()) *StatusStore_UpdateExpiredDNDStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusStore_UpdateExpiredDNDStatuses_Call) Return(statuss []*model.Status, err error) *StatusStore_UpdateExpiredDNDStatuses_Call {
	_c.Call.Return(statuss, err)
	return _c
}

func (_c *StatusStore_UpdateExpiredDNDStatuses_Call) RunAndReturn(run func() ([]*model.Status, error)) *StatusStore_UpdateExpiredDNDStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastActivityAt provides a mock function for the type StatusStore
func (_mock *StatusStore) UpdateLastActivityAt(userID string, lastActivityAt int64) error {
	ret := _mock.Called(userID, lastActivityAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastActivityAt")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = returnFunc(userID, lastActivityAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StatusStore_UpdateLastActivityAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastActivityAt'
type StatusStore_UpdateLastActivityAt_Call struct {
	*mock.Call
}

// UpdateLastActivityAt is a helper method to define mock.On call
//   - userID string
//   - lastActivityAt int64
func (_e *StatusStore_Expecter) UpdateLastActivityAt(userID any, lastActivityAt any) *StatusStore_UpdateLastActivityAt_Call {
	return &StatusStore_UpdateLastActivityAt_Call{Call: _e.mock.On("UpdateLastActivityAt", userID, lastActivityAt)}
}

func (_c *StatusStore_UpdateLastActivityAt_Call) Run(run func(userID string, lastActivityAt int64)) *StatusStore_UpdateLastActivityAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StatusStore_UpdateLastActivityAt_Call) Return(err error) *StatusStore_UpdateLastActivityAt_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StatusStore_UpdateLastActivityAt_Call) RunAndReturn(run func(userID string, lastActivityAt int64) error) *StatusStore_UpdateLastActivityAt_Call {
	_c.Call.Return(run)
	return _c
}
