// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/lms_models"
	"github.com/iamleson98/sitename/server/public/model_helper"
	mock "github.com/stretchr/testify/mock"
)

// NewStudentClassStore creates a new instance of StudentClassStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentClassStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentClassStore {
	mock := &StudentClassStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StudentClassStore is an autogenerated mock type for the StudentClassStore type
type StudentClassStore struct {
	mock.Mock
}

type StudentClassStore_Expecter struct {
	mock *mock.Mock
}

func (_m *StudentClassStore) EXPECT() *StudentClassStore_Expecter {
	return &StudentClassStore_Expecter{mock: &_m.Mock}
}

// CountByStudent provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) CountByStudent(studentID string, status string) (int64, error) {
	ret := _mock.Called(studentID, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStudent")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return returnFunc(studentID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = returnFunc(studentID, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(studentID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_CountByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStudent'
type StudentClassStore_CountByStudent_Call struct {
	*mock.Call
}

// CountByStudent is a helper method to define mock.On call
//   - studentID string
//   - status string
func (_e *StudentClassStore_Expecter) CountByStudent(studentID any, status any) *StudentClassStore_CountByStudent_Call {
	return &StudentClassStore_CountByStudent_Call{Call: _e.mock.On("CountByStudent", studentID, status)}
}

func (_c *StudentClassStore_CountByStudent_Call) Run(run func(studentID string, status string)) *StudentClassStore_CountByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StudentClassStore_CountByStudent_Call) Return(n int64, err error) *StudentClassStore_CountByStudent_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *StudentClassStore_CountByStudent_Call) RunAndReturn(run func(studentID string, status string) (int64, error)) *StudentClassStore_CountByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StudentClassStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type StudentClassStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *StudentClassStore_Expecter) Delete(id any) *StudentClassStore_Delete_Call {
	return &StudentClassStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *StudentClassStore_Delete_Call) Run(run func(id string)) *StudentClassStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_Delete_Call) Return(err error) *StudentClassStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StudentClassStore_Delete_Call) RunAndReturn(run func(id string) error) *StudentClassStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByClass provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) DeleteByClass(classID string) error {
	ret := _mock.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByClass")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(classID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StudentClassStore_DeleteByClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByClass'
type StudentClassStore_DeleteByClass_Call struct {
	*mock.Call
}

// DeleteByClass is a helper method to define mock.On call
//   - classID string
func (_e *StudentClassStore_Expecter) DeleteByClass(classID any) *StudentClassStore_DeleteByClass_Call {
	return &StudentClassStore_DeleteByClass_Call{Call: _e.mock.On("DeleteByClass", classID)}
}

func (_c *StudentClassStore_DeleteByClass_Call) Run(run func(classID string)) *StudentClassStore_DeleteByClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_DeleteByClass_Call) Return(err error) *StudentClassStore_DeleteByClass_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StudentClassStore_DeleteByClass_Call) RunAndReturn(run func(classID string) error) *StudentClassStore_DeleteByClass_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByStudent provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) DeleteByStudent(studentID string) error {
	ret := _mock.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByStudent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(studentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StudentClassStore_DeleteByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByStudent'
type StudentClassStore_DeleteByStudent_Call struct {
	*mock.Call
}

// DeleteByStudent is a helper method to define mock.On call
//   - studentID string
func (_e *StudentClassStore_Expecter) DeleteByStudent(studentID any) *StudentClassStore_DeleteByStudent_Call {
	return &StudentClassStore_DeleteByStudent_Call{Call: _e.mock.On("DeleteByStudent", studentID)}
}

func (_c *StudentClassStore_DeleteByStudent_Call) Run(run func(studentID string)) *StudentClassStore_DeleteByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_DeleteByStudent_Call) Return(err error) *StudentClassStore_DeleteByStudent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StudentClassStore_DeleteByStudent_Call) RunAndReturn(run func(studentID string) error) *StudentClassStore_DeleteByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) Get(id string) (*lms_models.StudentClass, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.StudentClass
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*lms_models.StudentClass, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *lms_models.StudentClass); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.StudentClass)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type StudentClassStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *StudentClassStore_Expecter) Get(id any) *StudentClassStore_Get_Call {
	return &StudentClassStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *StudentClassStore_Get_Call) Run(run func(id string)) *StudentClassStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_Get_Call) Return(studentClass *lms_models.StudentClass, err error) *StudentClassStore_Get_Call {
	_c.Call.Return(studentClass, err)
	return _c
}

func (_c *StudentClassStore_Get_Call) RunAndReturn(run func(id string) (*lms_models.StudentClass, error)) *StudentClassStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClass provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) GetByClass(classID string) ([]*lms_models.StudentClass, error) {
	ret := _mock.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClass")
	}

	var r0 []*lms_models.StudentClass
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*lms_models.StudentClass, error)); ok {
		return returnFunc(classID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*lms_models.StudentClass); ok {
		r0 = returnFunc(classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.StudentClass)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_GetByClass_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClass'
type StudentClassStore_GetByClass_Call struct {
	*mock.Call
}

// GetByClass is a helper method to define mock.On call
//   - classID string
func (_e *StudentClassStore_Expecter) GetByClass(classID any) *StudentClassStore_GetByClass_Call {
	return &StudentClassStore_GetByClass_Call{Call: _e.mock.On("GetByClass", classID)}
}

func (_c *StudentClassStore_GetByClass_Call) Run(run func(classID string)) *StudentClassStore_GetByClass_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_GetByClass_Call) Return(studentClasss []*lms_models.StudentClass, err error) *StudentClassStore_GetByClass_Call {
	_c.Call.Return(studentClasss, err)
	return _c
}

func (_c *StudentClassStore_GetByClass_Call) RunAndReturn(run func(classID string) ([]*lms_models.StudentClass, error)) *StudentClassStore_GetByClass_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStudent provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) GetByStudent(studentID string) ([]*lms_models.StudentClass, error) {
	ret := _mock.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStudent")
	}

	var r0 []*lms_models.StudentClass
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*lms_models.StudentClass, error)); ok {
		return returnFunc(studentID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*lms_models.StudentClass); ok {
		r0 = returnFunc(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.StudentClass)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(studentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_GetByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStudent'
type StudentClassStore_GetByStudent_Call struct {
	*mock.Call
}

// GetByStudent is a helper method to define mock.On call
//   - studentID string
func (_e *StudentClassStore_Expecter) GetByStudent(studentID any) *StudentClassStore_GetByStudent_Call {
	return &StudentClassStore_GetByStudent_Call{Call: _e.mock.On("GetByStudent", studentID)}
}

func (_c *StudentClassStore_GetByStudent_Call) Run(run func(studentID string)) *StudentClassStore_GetByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_GetByStudent_Call) Return(studentClasss []*lms_models.StudentClass, err error) *StudentClassStore_GetByStudent_Call {
	_c.Call.Return(studentClasss, err)
	return _c
}

func (_c *StudentClassStore_GetByStudent_Call) RunAndReturn(run func(studentID string) ([]*lms_models.StudentClass, error)) *StudentClassStore_GetByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// GetExisting provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) GetExisting(studentID string, classID string) (*lms_models.StudentClass, error) {
	ret := _mock.Called(studentID, classID)

	if len(ret) == 0 {
		panic("no return value specified for GetExisting")
	}

	var r0 *lms_models.StudentClass
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*lms_models.StudentClass, error)); ok {
		return returnFunc(studentID, classID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *lms_models.StudentClass); ok {
		r0 = returnFunc(studentID, classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.StudentClass)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(studentID, classID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_GetExisting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExisting'
type StudentClassStore_GetExisting_Call struct {
	*mock.Call
}

// GetExisting is a helper method to define mock.On call
//   - studentID string
//   - classID string
func (_e *StudentClassStore_Expecter) GetExisting(studentID any, classID any) *StudentClassStore_GetExisting_Call {
	return &StudentClassStore_GetExisting_Call{Call: _e.mock.On("GetExisting", studentID, classID)}
}

func (_c *StudentClassStore_GetExisting_Call) Run(run func(studentID string, classID string)) *StudentClassStore_GetExisting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StudentClassStore_GetExisting_Call) Return(studentClass *lms_models.StudentClass, err error) *StudentClassStore_GetExisting_Call {
	_c.Call.Return(studentClass, err)
	return _c
}

func (_c *StudentClassStore_GetExisting_Call) RunAndReturn(run func(studentID string, classID string) (*lms_models.StudentClass, error)) *StudentClassStore_GetExisting_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) Save(sc *lms_models.StudentClass) (*lms_models.StudentClass, error) {
	ret := _mock.Called(sc)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.StudentClass
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lms_models.StudentClass) (*lms_models.StudentClass, error)); ok {
		return returnFunc(sc)
	}
	if returnFunc, ok := ret.Get(0).(func(*lms_models.StudentClass) *lms_models.StudentClass); ok {
		r0 = returnFunc(sc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.StudentClass)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lms_models.StudentClass) error); ok {
		r1 = returnFunc(sc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StudentClassStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type StudentClassStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - sc *lms_models.StudentClass
func (_e *StudentClassStore_Expecter) Save(sc any) *StudentClassStore_Save_Call {
	return &StudentClassStore_Save_Call{Call: _e.mock.On("Save", sc)}
}

func (_c *StudentClassStore_Save_Call) Run(run func(sc *lms_models.StudentClass)) *StudentClassStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lms_models.StudentClass
		if args[0] != nil {
			arg0 = args[0].(*lms_models.StudentClass)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_Save_Call) Return(studentClass *lms_models.StudentClass, err error) *StudentClassStore_Save_Call {
	_c.Call.Return(studentClass, err)
	return _c
}

func (_c *StudentClassStore_Save_Call) RunAndReturn(run func(sc *lms_models.StudentClass) (*lms_models.StudentClass, error)) *StudentClassStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SearchStudentUsers provides a mock function for the type StudentClassStore
func (_mock *StudentClassStore) SearchStudentUsers(opts modelhelper.StudentFilterOpts) (lms_models.UserSlice, int64, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchStudentUsers")
	}

	var r0 lms_models.UserSlice
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(modelhelper.StudentFilterOpts) (lms_models.UserSlice, int64, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(modelhelper.StudentFilterOpts) lms_models.UserSlice); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(lms_models.UserSlice)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(modelhelper.StudentFilterOpts) int64); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(modelhelper.StudentFilterOpts) error); ok {
		r2 = returnFunc(opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// StudentClassStore_SearchStudentUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchStudentUsers'
type StudentClassStore_SearchStudentUsers_Call struct {
	*mock.Call
}

// SearchStudentUsers is a helper method to define mock.On call
//   - opts modelhelper.StudentFilterOpts
func (_e *StudentClassStore_Expecter) SearchStudentUsers(opts any) *StudentClassStore_SearchStudentUsers_Call {
	return &StudentClassStore_SearchStudentUsers_Call{Call: _e.mock.On("SearchStudentUsers", opts)}
}

func (_c *StudentClassStore_SearchStudentUsers_Call) Run(run func(opts modelhelper.StudentFilterOpts)) *StudentClassStore_SearchStudentUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 modelhelper.StudentFilterOpts
		if args[0] != nil {
			arg0 = args[0].(modelhelper.StudentFilterOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StudentClassStore_SearchStudentUsers_Call) Return(userSlice lms_models.UserSlice, n int64, err error) *StudentClassStore_SearchStudentUsers_Call {
	_c.Call.Return(userSlice, n, err)
	return _c
}

func (_c *StudentClassStore_SearchStudentUsers_Call) RunAndReturn(run func(opts modelhelper.StudentFilterOpts) (lms_models.UserSlice, int64, error)) *StudentClassStore_SearchStudentUsers_Call {
	_c.Call.Return(run)
	return _c
}
