// Code generated by mockery v2.53.6. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	lms_models "github.com/iamleson98/sitename/server/public/lms_models"
	mock "github.com/stretchr/testify/mock"

	modelhelper "github.com/iamleson98/sitename/server/public/model_helper"
)

// TaskStore is an autogenerated mock type for the TaskStore type
type TaskStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *TaskStore) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *TaskStore) Get(id string) (*lms_models.Task, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*lms_models.Task, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *lms_models.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: task
func (_m *TaskStore) Save(task *lms_models.Task) (*lms_models.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Task) (*lms_models.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Task) *lms_models.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: opts
func (_m *TaskStore) Search(opts modelhelper.TaskFilterOpts) ([]*lms_models.Task, int64, error) {
	ret := _m.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*lms_models.Task
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(modelhelper.TaskFilterOpts) ([]*lms_models.Task, int64, error)); ok {
		return rf(opts)
	}
	if rf, ok := ret.Get(0).(func(modelhelper.TaskFilterOpts) []*lms_models.Task); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(modelhelper.TaskFilterOpts) int64); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(modelhelper.TaskFilterOpts) error); ok {
		r2 = rf(opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: task
func (_m *TaskStore) Update(task *lms_models.Task) (*lms_models.Task, error) {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *lms_models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(*lms_models.Task) (*lms_models.Task, error)); ok {
		return rf(task)
	}
	if rf, ok := ret.Get(0).(func(*lms_models.Task) *lms_models.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(*lms_models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskStore creates a new instance of TaskStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskStore {
	mock := &TaskStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
