// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/iamleson98/sitename/server/public/lms_models"
	"github.com/iamleson98/sitename/server/public/model_helper"
	mock "github.com/stretchr/testify/mock"
)

// NewWeeklyReviewStore creates a new instance of WeeklyReviewStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeeklyReviewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeeklyReviewStore {
	mock := &WeeklyReviewStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WeeklyReviewStore is an autogenerated mock type for the WeeklyReviewStore type
type WeeklyReviewStore struct {
	mock.Mock
}

type WeeklyReviewStore_Expecter struct {
	mock *mock.Mock
}

func (_m *WeeklyReviewStore) EXPECT() *WeeklyReviewStore_Expecter {
	return &WeeklyReviewStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type WeeklyReviewStore
func (_mock *WeeklyReviewStore) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WeeklyReviewStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WeeklyReviewStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *WeeklyReviewStore_Expecter) Delete(id any) *WeeklyReviewStore_Delete_Call {
	return &WeeklyReviewStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *WeeklyReviewStore_Delete_Call) Run(run func(id string)) *WeeklyReviewStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeeklyReviewStore_Delete_Call) Return(err error) *WeeklyReviewStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WeeklyReviewStore_Delete_Call) RunAndReturn(run func(id string) error) *WeeklyReviewStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type WeeklyReviewStore
func (_mock *WeeklyReviewStore) Get(id string) (*lms_models.WeeklyReview, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lms_models.WeeklyReview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*lms_models.WeeklyReview, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *lms_models.WeeklyReview); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.WeeklyReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WeeklyReviewStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type WeeklyReviewStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *WeeklyReviewStore_Expecter) Get(id any) *WeeklyReviewStore_Get_Call {
	return &WeeklyReviewStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *WeeklyReviewStore_Get_Call) Run(run func(id string)) *WeeklyReviewStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeeklyReviewStore_Get_Call) Return(weeklyReview *lms_models.WeeklyReview, err error) *WeeklyReviewStore_Get_Call {
	_c.Call.Return(weeklyReview, err)
	return _c
}

func (_c *WeeklyReviewStore_Get_Call) RunAndReturn(run func(id string) (*lms_models.WeeklyReview, error)) *WeeklyReviewStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type WeeklyReviewStore
func (_mock *WeeklyReviewStore) Save(wr *lms_models.WeeklyReview) (*lms_models.WeeklyReview, error) {
	ret := _mock.Called(wr)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *lms_models.WeeklyReview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lms_models.WeeklyReview) (*lms_models.WeeklyReview, error)); ok {
		return returnFunc(wr)
	}
	if returnFunc, ok := ret.Get(0).(func(*lms_models.WeeklyReview) *lms_models.WeeklyReview); ok {
		r0 = returnFunc(wr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.WeeklyReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lms_models.WeeklyReview) error); ok {
		r1 = returnFunc(wr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WeeklyReviewStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type WeeklyReviewStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - wr *lms_models.WeeklyReview
func (_e *WeeklyReviewStore_Expecter) Save(wr any) *WeeklyReviewStore_Save_Call {
	return &WeeklyReviewStore_Save_Call{Call: _e.mock.On("Save", wr)}
}

func (_c *WeeklyReviewStore_Save_Call) Run(run func(wr *lms_models.WeeklyReview)) *WeeklyReviewStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lms_models.WeeklyReview
		if args[0] != nil {
			arg0 = args[0].(*lms_models.WeeklyReview)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeeklyReviewStore_Save_Call) Return(weeklyReview *lms_models.WeeklyReview, err error) *WeeklyReviewStore_Save_Call {
	_c.Call.Return(weeklyReview, err)
	return _c
}

func (_c *WeeklyReviewStore_Save_Call) RunAndReturn(run func(wr *lms_models.WeeklyReview) (*lms_models.WeeklyReview, error)) *WeeklyReviewStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type WeeklyReviewStore
func (_mock *WeeklyReviewStore) Search(opts modelhelper.WeeklyReviewFilterOpts) ([]*lms_models.WeeklyReview, int64, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*lms_models.WeeklyReview
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(modelhelper.WeeklyReviewFilterOpts) ([]*lms_models.WeeklyReview, int64, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(modelhelper.WeeklyReviewFilterOpts) []*lms_models.WeeklyReview); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lms_models.WeeklyReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(modelhelper.WeeklyReviewFilterOpts) int64); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(modelhelper.WeeklyReviewFilterOpts) error); ok {
		r2 = returnFunc(opts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// WeeklyReviewStore_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type WeeklyReviewStore_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - opts modelhelper.WeeklyReviewFilterOpts
func (_e *WeeklyReviewStore_Expecter) Search(opts any) *WeeklyReviewStore_Search_Call {
	return &WeeklyReviewStore_Search_Call{Call: _e.mock.On("Search", opts)}
}

func (_c *WeeklyReviewStore_Search_Call) Run(run func(opts modelhelper.WeeklyReviewFilterOpts)) *WeeklyReviewStore_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 modelhelper.WeeklyReviewFilterOpts
		if args[0] != nil {
			arg0 = args[0].(modelhelper.WeeklyReviewFilterOpts)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeeklyReviewStore_Search_Call) Return(weeklyReviews []*lms_models.WeeklyReview, n int64, err error) *WeeklyReviewStore_Search_Call {
	_c.Call.Return(weeklyReviews, n, err)
	return _c
}

func (_c *WeeklyReviewStore_Search_Call) RunAndReturn(run func(opts modelhelper.WeeklyReviewFilterOpts) ([]*lms_models.WeeklyReview, int64, error)) *WeeklyReviewStore_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type WeeklyReviewStore
func (_mock *WeeklyReviewStore) Update(wr *lms_models.WeeklyReview) (*lms_models.WeeklyReview, error) {
	ret := _mock.Called(wr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *lms_models.WeeklyReview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lms_models.WeeklyReview) (*lms_models.WeeklyReview, error)); ok {
		return returnFunc(wr)
	}
	if returnFunc, ok := ret.Get(0).(func(*lms_models.WeeklyReview) *lms_models.WeeklyReview); ok {
		r0 = returnFunc(wr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lms_models.WeeklyReview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lms_models.WeeklyReview) error); ok {
		r1 = returnFunc(wr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WeeklyReviewStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WeeklyReviewStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - wr *lms_models.WeeklyReview
func (_e *WeeklyReviewStore_Expecter) Update(wr any) *WeeklyReviewStore_Update_Call {
	return &WeeklyReviewStore_Update_Call{Call: _e.mock.On("Update", wr)}
}

func (_c *WeeklyReviewStore_Update_Call) Run(run func(wr *lms_models.WeeklyReview)) *WeeklyReviewStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lms_models.WeeklyReview
		if args[0] != nil {
			arg0 = args[0].(*lms_models.WeeklyReview)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeeklyReviewStore_Update_Call) Return(weeklyReview *lms_models.WeeklyReview, err error) *WeeklyReviewStore_Update_Call {
	_c.Call.Return(weeklyReview, err)
	return _c
}

func (_c *WeeklyReviewStore_Update_Call) RunAndReturn(run func(wr *lms_models.WeeklyReview) (*lms_models.WeeklyReview, error)) *WeeklyReviewStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
